### ISSUE TITLE
Last passing PDF build offered even when out of date

### ISSUE THREAD

**Issue by hwine** [rtfd/readthedocs.org#1120]
Our [build logs](https://readthedocs.org/builds/moz-releng-docs/) correctly show PDF builds as failing. However, a PDF version is offered for download in the [docs](http://moz-releng-docs.readthedocs.org/en/latest/). Turns out that is the last successfully produced PDF -- from around July 2014. :(

My expectation would be that either:
- the user is notified that the non-html docs are out of date as part of download, or
- out of date alternate formats (PDF & ePub) are not downloadable if they aren't current.

**Comment by agjohnson** [comment]
-1 to halting downloads when builds are failing. If the builds are out of date, that is the authors problem, not the user. This would definitely be a bad user experience for users that want to download documentation.

We're doing a poor job of letting the authors know when PDFs fail, so maybe a better avenue is to increase messaging on pdf failures. Both to authors in email, but also on the project page or download page. On site messaging g might not mean much to anyone as downloads are hotlinked usually.

**Comment by hwine** [comment]
I would suggest that downloading ancient PDF thinking it's current with displayed HTML is a worse user experience. 

Keeping the user informed lets them make the choice, and decouples this from issue 1121

**Comment by agjohnson** [comment]
Again, that's an authorship problem, not a user problem. We wouldn't 404 on access to docs when builds are failing in another other scenario, so I don't see this being different. We prefer access to documentation remains intact for readers, even if that means an out of date, archived pdf.

However, your point is still valid. The real issue is that we are failing at making sure authors know their builds are failing.

**Comment by hwine** [comment]
We agree what's happening now is bad for users. Good.

I would vote for transparency to the user. I can badge my doc status on a website -- why shouldn't each artifact (html, epub, pdf) be "auto badged" on the rtd site if that build type has failed? (I.e. 404 is one response, having a dimmed icon or missing icon is another.)

Right now, the experience for both authors and users is surprising. What's your recommendation on the quickest way to restore "principle of least surprise"?

**Comment by agjohnson** [comment]
I think that the first stop gap should be adding a PDF build error email. This should be relatively easy and would put some pressure on project maintainers to fix the issue.

I generally like the idea of a "stale" badge display concept as well, something I'm not 100% sure we're tracking at the moment. +1 on more transparency to end users, not to mention social pressure :). Though the secondary badge is a slippery slope due to the way the builds were architected.

PDF builds were architected in a strange way, they were added as second class build objects. Ideally, we would have treated builds as an encompassing object that included child html and pdf builds. So, right now, an HTML build can pass and the PDF can fail, but RTD equates the build with the HTML build, so it will seem to pass. This happens across the site in many places and could be addressed instead of furthering the split between html builds and pdf builds.

We have plans to tackle some of this in a larger build refactor, so don't want to send anyone down the wrong path with this. I'd like to get this resolved soon, so if no one else can get to this, I'll likely jump in sometime this week or next.

**Comment by agjohnson** [comment]
The build refactor is in production and accomplishes part of what was discussed above. The builds for HTML and PDF are now a single build, which if it fails, will notify the author of failure and trigger the standard build failure badge. I believe this addresses the original scenario.

I still like the idea of tracking build output objects, so that we can give an idea of freshness to the user for those objects on the downloads page. We have plans for this already as a broader concept, but it's sitting on our roadmap at the moment.

**Comment by agjohnson** [comment]
Closing this issue, as the original issue is mostly solved. Still no plans to overhaul our downloads on our roadmap at this point either.
