### ISSUE TITLE
Changing my subdomain on readthedocs.org

### ISSUE THREAD

**Issue by cheerfulstoic** [rtfd/readthedocs.org#1142]
Sorry if this is the wrong place, but I couldn't find an E-Mail address

I've been trying out readthedocs.org (which seems great so far, BTW) and wanted to try out documentation for:

https://github.com/neo4jrb/neo4j

I ended up with this address:
http://neo4j.readthedocs.org/en/latest/

I don't want to bogart the `neo4j` subdomain though, since this is just the ruby driver for neo4j.  Is there a way to change it?

Thanks

**Comment by ericholscher** [comment]
We don't offer folks a way to change it by default, since it breaks all
existing links to your project. I can update it for you, or you can just
re-create the project and it will generate a new slug for you. Let me know
if you want me to update it, and what you want it to be.

On Wed, Feb 4, 2015 at 4:41 AM, Brian Underwood <notifications@github.com>
wrote:

> Sorry if this is the wrong place, but I couldn't find an E-Mail address
>
> I've been trying out readthedocs.org (which seems great so far, BTW) and
> wanted to try out documentation for:
>
> https://github.com/neo4jrb/neo4j
>
> I ended up with this address:
> http://neo4j.readthedocs.org/en/latest/
>
> I don't want to bogart the neo4j subdomain though, since this is just the
> ruby driver for neo4j. Is there a way to change it?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1142>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Or
http://ericholscher.com

**Comment by cheerfulstoic** [comment]
Ah, deleting and recreating the project.  That would have been smart ;)  I'll do that now, thanks!

**Comment by cheerfulstoic** [comment]
That worked, though one thing to point out: I tried changing the project name earlier and as a separate (or so I thought) issue, my builds weren't showing up on the site, which was particularly frustrating because it was my first time.  But I wonder if you change your product name if that makes the site not update anymore...
