### ISSUE TITLE
CSV-based tables on RTD

### ISSUE THREAD

**Issue by gigster99** [rtfd/readthedocs.org#1150]
RTD does not line wrap CSV tables. Here is an example of a CSV table with line wrapping as executed by Online rST:

http://rst.ninjs.org/?n=5523984685b576e5f5b14f727b33c354&theme=nature

We also checked with the Sphinx development team. They installed the CSV table above on an internal test Sphinx implementation and produced the same results as by Online rST.

We have many tables that need to be handled as by Online rST and Sphinx. Would you ask the Sphinx team for advice, or use the appropriate code from OnLine rST to produce the same results on RTD?

https://github.com/anru/rsted

Thank you.
We also plan to use readthedocs.com but cannot do so until this issue is resolved (assuming that readthedocs.com implements the same core service as readthedocs.org).
BTW, it also needs to work for lists - long lines do not wrap on RTD but do wrap on Online rST.
/g

**Comment by agjohnson** [comment]
The difference comes from the CSS for the RTD theme, it's not an issue with sphinx directly. If you wish to override this behavior, you can include additional CSS that sets table content to wrap instead scrolling on the table.

Here's an example of adding additional css includes:
http://stackoverflow.com/a/23466546

I'm not sure there is a good case to wrap tables instead of making the content scrolling for everyone. It should be easy enough to overload this if you are using large tables that you want wrapped.

**Comment by hbshrestha** [comment]
What was the solution to this issue? I am facing the same issue that I cannot wrap the text in table created using csv-table directive in rst file for the sphinx documentation.
