### ISSUE TITLE
Should be able to disable "2nd class" outputs in admin settings

### ISSUE THREAD

**Issue by hwine** [rtfd/readthedocs.org#1154]
At the moment, PDF and ePub formats are "2nd class" outputs of the system, in that the author does not get notified of production failures specific to those formats. (see, e.g. #1121 which impacted users as described in #1120)

Since lossless conversion to the 2nd class formats can't be guaranteed, an author may need to invest additional time to produce source that will convert cleanly. I think that choice should be up to the author, not a (hidden) cost of using read the docs.

Adding checkboxes to enable/disable production of these alternate formats to the administration page would be one way to implement.

**Comment by agjohnson** [comment]
I agree. I'm not sure of the statistics of the number of users producing pdf/epub output, but i think exposing these as options some how to the user would reduce confusion -- especially since pdf builds can be intermittent problematic in our build evironment.

We're trying to reduce the config options, as the user experience is awful, but this might be a large enough configuration option to warrant a UI element for configuration.

**Comment by tisdall** [comment]
@agjohnson it seems like pdf/epub are defaulted to on, so wouldn't it be all projects end up producing those?  Or am I missing something?

**Comment by agjohnson** [comment]
@tisdall i suppose i meant *using* pdf output, this is the number I'm not sure of. You are correct that all projects default with pdf/epub output enabled.

**Comment by ericholscher** [comment]
Our builder code knows how build all the types separately. The main thing
we need is a UI for selecting them. A PR with this would definitely be
accepted. It's on our long list of things to do otherwise.

On Wed, May 6, 2015 at 1:57 PM, Anthony <notifications@github.com> wrote:

> @tisdall <https://github.com/tisdall> i suppose i meant *using* pdf
> output, this is the number I'm not sure of. You are correct that all
> projects default with pdf/epub output enabled.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1154#issuecomment-99607491>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by gregmuellegger** [comment]
This is done with the merge of #1344.

**Comment by tisdall** [comment]
@gregmuellegger, thank you!
