### ISSUE TITLE
Translations needs updates

### ISSUE THREAD

**Issue by yfdyh000** [rtfd/readthedocs.org#1157]
I just updated the zh-CN translation. I found the translations have not been updated (push to Transifex & pull to Github) for a long time, anyone can perform it.

And, what is 'One-offs' & 'Term'? it on https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/templates/djangome/oneoffs.html, but I don't understand it.

**Comment by yfdyh000** [comment]
@agjohnson @ericholscher

**Comment by gregmuellegger** [comment]
The oneoffs template is no longer used. I created #1423 to remove it. Also we already noted in #1199 that we need to update the translations to a more currrent date. That's why I'm closing this ticket now and keep track of it in #1199.

Cheers for the report :)

**Comment by ericholscher** [comment]
We do need to update the translations. However, we should do a full sweep
of the code to kill old strings, and make sure everything is marked as
translatable, so that we can actually make the i18n experience good.

This is something I've been wanting to build a proper workflow around,
since it's always been rather ad hoc. Another thing to add to the list, but
we should at least have a ticket open about it.

On Fri, Jul 10, 2015 at 7:30 AM, Gregor Müllegger <notifications@github.com>
wrote:

> Closed #1157 <https://github.com/rtfd/readthedocs.org/issues/1157>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1157#event-352983512>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com
