### ISSUE TITLE
Tree view won't scroll

### ISSUE THREAD

**Issue by shaunerikson** [rtfd/readthedocs.org#1159]
I am unable to get the index area to scroll downward when the number of topics extends below the bottom of the browser window.  This just started happening in the last few days.

In the attached picture, the number of topics under the "Sequelize" topic is much more than 5, but I can't make them visible.

![image](https://cloud.githubusercontent.com/assets/8966548/6228625/21d53fce-b663-11e4-8293-c941d6010d50.png)

**Comment by agjohnson** [comment]
The stickiness of the navigation was being added by the mkdocs template, we needed to add the javascript bit that applies navigation stickiness, initially and on resize, based on the window height vs nav height.

This bug was related to another fix to the nav menu I just made, which removed a mkdocs specific fix to the nav. I just deployed new js that allows scrolling + sticky menus on mkdocs.

**Comment by shaunerikson** [comment]
Works for me now, thanks!
