### ISSUE TITLE
Extend and document API v2

### ISSUE THREAD

**Issue by stygiansabyss** [rtfd/readthedocs.org#1175]
I have seen this detailed in the issues here but I can't find any place that details how to use this.  I have been trying to get API details through Guzzle but I am not having a lot of luck on how to format URLs (builds for example).

Are there any docs for the v2 API endpoints?

**Comment by gregmuellegger** [comment]
I think there is no documentation so far on the API v2 endpoints. However I'm not sure if that would benefit anyone as it seems to me that they more are targeted at internal use of RTD.

What would you like to do with the API? I guess for most user facing purposes the API v1 is just fine (like crawling through the details of a specific project etc).

**Comment by stygiansabyss** [comment]
I was hoping to build a dashboard that would allow me to trigger builds for my sites.  Things like scrutinizer, travis CI and rtd.

**Comment by gregmuellegger** [comment]
Ok, I don't think it is possible so far to use the API to create a new project. But we are ofcourse happy to accept any patches in that regard.

I think triggering a build is already possible using the post-commit-hook described on your project's page: `curl -X POST http://readthedocs.org/build/<project-slug>`

**Comment by gregmuellegger** [comment]
If you really want to push this idea further it might be good to open a new ticket for every aspect that you want to add to the API. We are happy to review any individual request.

**Comment by ericholscher** [comment]
The idea here is to have API V2 eventually replace the old V1 API. It's
using REST framework instead of tastypie, and actually allow RTD to be
orchestrated like this. It's not currently working, but most new code
should go into V2, and we should be actively working towards this.

Add it to the massive list of things to do, but it's definitely something
we're interested in supporting.

On Fri, Jul 10, 2015 at 7:34 AM, Gregor Müllegger <notifications@github.com>
wrote:

> Ok, I don't think it is possible so far to use the API to create a new
> project. But we are ofcourse happy to accept any patches in that regard.
>
> I think triggering a build is already possible using the post-commit-hook
> described on your project's page: curl -X POST
> http://readthedocs.org/build/<project-slug>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1175#issuecomment-120423866>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by Artic2017** [comment]
.
