### ISSUE TITLE
literalinclude with lineno-start option doesn't seem to work

### ISSUE THREAD

**Issue by ronichoudhury** [rtfd/readthedocs.org#1201]
When I build my Sphinx documentation locally, ``literalinclude`` blocks using the ``lineno-start`` option work properly.  However, the same docs built at the RTD site don't work properly - the expected include block is simply missing [0].

Is there a step I am forgetting?  Or perhaps the version of Sphinx I use locally is not the same as what RTD uses?

Thanks!

[0] http://tangelo.readthedocs.org/en/v0.9/tutorials/db-vis.html#establishing-orm-classes, and then search for "appearing in our data" - there should be a code listing right after that

**Comment by kghosesbg** [comment]
I have a worse problem: the moment I use either :lineno-start or :lineno-match:, my entire code block disappears. This is Sphinx v1.2.3

**Comment by kghosesbg** [comment]
Actually, this is solved by moving to the latest version v1.3.1

**Comment by gregmuellegger** [comment]
@ronichoudhury We updated Sphinx 1.3.1 in https://github.com/rtfd/readthedocs.org/commit/0ac37e2902d8e65864c60a38fedfdd114dec957f so I assume this issue is fixed now.

I've rebuilt your documentation and it seems to be fixed: http://tangelo.readthedocs.org/en/v0.9/tutorials/db-vis.html#establishing-orm-classes

**Comment by ronichoudhury** [comment]
Looks great.  Thanks @gregmuellegger!
