### ISSUE TITLE
julia project missing?

### ISSUE THREAD

**Issue by nolta** [rtfd/readthedocs.org#1296]
The julia docs haven't been updated for several days, and the [julia project page](https://readthedocs.org/projects/julia/) ends in the "maze".

**Comment by ericholscher** [comment]
Hmm, quite odd. I went ahead and recreated it so that your builds will work
again.

I restored a database backup from the 17th and Julia wasn't in there, so
it's been missing for over a week. I looked through the web server logs,
and saw julia-i18n got deleted around May 12th, but don't see an entry for
Julia itself. I'm wondering if there was a foreign key to the i18n project,
or the main project got renamed somewhere in there. Quite odd. I'll do a
bit more digging tomorrow.

On Mon, May 25, 2015 at 5:37 PM, Mike Nolta <notifications@github.com>
wrote:

> The julia docs haven't been updated for several days, and the julia
> project <https://readthedocs.org/projects/julia/> ends in the "maze".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1296>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by nolta** [comment]
Thanks!

**Comment by pao** [comment]
Would this issue https://github.com/JuliaLang/julia/issues/11527 happen to be related to the database problem, or is this completely unrelated weirdness?

**Comment by agjohnson** [comment]
@pao The issue you are noticing is likely completely unrelated. I believe this is ticket can be closed, but will defer to @ericholscher

**Comment by pao** [comment]
Thanks (and thanks for following up on the referenced issue!)

**Comment by agjohnson** [comment]
Closing this, it looks resolved
