### ISSUE TITLE
Support building docs written in Perl's POD

### ISSUE THREAD

**Issue by xtaran** [rtfd/readthedocs.org#1319]
It would be nice if it would be possible to publish documentation written in Perl's POD ("Plain Old Documentation") format. [`pod2html`](http://perldoc.perl.org/pod2html.html) is probably the right command to base on for that. (The referenced documentation likely has been built with `pod2html` itself, too.)

That would help a lot of perl-based projects to use ReadTheDocs.

There is also a [POD to Markdown converter](https://metacpan.org/release/Pod-Markdown) in Perl so Mkdocs could be used as second step. But that would still require some additional support from ReadTheDocs.

**Comment by ericholscher** [comment]
We have a mostly working version of a Perl Sphinx domain, and are on the way to adding support for Perl autoapi docs. Though @agjohnson would know more.

**Comment by agjohnson** [comment]
So I started tackling this problem a few months ago and gave a talk at PDX.pm on it. There were two paths I explored.

The first path was using standard POD tool chain to output something that could be used by RTD, like @xtaran mentions above. The problem with this approach is that POD, and Markdown, are only really proxies to HTML output. In the end, this route is just recreating CPAN/MetaCPAN with our theme, which doesn't seem worth it, IMO.

The power of RTD comes from Sphinx and rST. My prototype includes a Sphinx domain for the parsing, display, and linking of Perl language constructs inside rST. rST replaces POD in my solution, providing a hybrid POD/rST which should be parseable going back to older versions of Perl. Though rST-ified POD introduces additional problems, like how to display on CPAN/MetaCPAN, rST provides a substantial amount of additional power to documentation authors.

My work is a hacked up pile of shit that I can get released this week hopefully. This feature, if implemented, would live inside our autoapi extension.

I'll create a ticket there with more insight into all of this and hopefully get some conversation going there.

**Comment by xtaran** [comment]
ReadTheDocs being able to ship POD rendered as HTML would be _far_ more than "CPAN/MetaCPAN can do". CPAN doesn't have any VCS triggers/hook as it haven't any VCS integration besides linking to externally hosted VCS repositories.

CPAN is only for stuff which has been _released_ on CPAN. ReadTheDocs doesn't have such a restriction.

In general, from my point of view the primary advantage of ReadTheDocs compared to just using Github + CPAN is to get documentation rendered _including_ a nice index with every _push_. CPAN, well, at least MetaCPAN already has such an index, but is by far less agile. You don't want to make a release just to fix a single typo. On the other hand, Github has some POD renderer and is agile, but lacks the generated index.

My project currently uses separate Markdown files for documentation. It's a commandline tool and no library (i.e. no Perl module), so there is no inline documentation and no API to document. I'd like to switch to POD to have less non-perl dependencies (i.e. getting rid of the mkdocs build dependency) to make the project more suitable for CPAN, but I'd like to keep the neat agile index and Github integration which ReadTheDocs offers. rST is definitely out of scope for me. It would only add disadvantages without adding any advantages for my (nearly) pure-perl project.

IMHO there won't be many Perl written projects which would drop inline POD for inline Markdown or even inline rST because POD is very central to Perl's documentation infrastructure. So from my point of view _that_ is not worth implementing it.

**Comment by agjohnson** [comment]
I'd be curious to get more input on this from some more Perl folks.

As it stands, `pod2html` is a non-starter. Read the Docs doesn't aim to just host arbitrary HTML from documentation tools -- that can happen anywhere on the internet. In addition, most maintainers would just use development releases to attempt the workflow you are suggesting. I don't see adoption from the Perl community being very wide in this case -- either case really.

Our primary focus is on using Sphinx as an authoring tool, and unifying the experience around Sphinx. Because of that, if we build anything to support Perl, it will be something that adopts Sphinx. The only reason not to parse POD in this case, is that I don't believe there are any modules that support this in Python currently -- this is something the community would have to maintain, as we likely would not. If it existed, we'd happily use that as well.

Either way, this won't address this specific use case of trying to avoid using non-Perl tools for documentation. This requirement isn't one we're particularly interested in supporting.

Happy to talk more about implementation details on the linked ticket: rtfd/sphinx-autoapi#5

Closing this ticket here, as the implementation will be strictly separated from RTD.
