### ISSUE TITLE
Allow not executing setup.py

### ISSUE THREAD

**Issue by sils1297** [rtfd/readthedocs.org#1332]
Readthedocs executes our setup.py for each build. This is completely useless for our mkdocs generated documentation and on top fails in a python2 environment. (In python3 everything falls apart completely :))

Maybe provide an option to turn that off or only do this when it's actually useful for documentaiton generation?

**Comment by agjohnson** [comment]
Not sure what you mean by failing on python2 or 3 -- examples of failure here would be helpful. Installation is required for sphinx documentation, which is our primary focus. I don't see any reports of it failing there. Likely you're hitting failures because you're setup.py is performing some action that should be mocked.

The mkdocs builder could probably be written to skip the setup step, it isn't required at all here.

Anyways, have you seen http://docs.readthedocs.org/en/latest/builds.html?highlight=setup.py#understanding-what-s-going-on ? This should bypass the installation step.

**Comment by sils1297** [comment]
> Anyways, have you seen http://docs.readthedocs.org/en/latest/builds.html?highlight=setup.py#understanding-what-s-going-on ? This should bypass the installation step.

We have that virtualenv option turned off and it still tries to build it if you mean that.

> Not sure what you mean by failing on python2 or 3 -- examples of failure here would be helpful. 

Sorry for not being clearer. Our project uses python 3 code that is incompatible to python2. Thus executing our setup.py with python2 obviously fails. However with python2 environment active the documentation builds fine. With the python3 environment it fails but this is probably another issue from this one.

**Comment by ericholscher** [comment]
If you turn off the ``Install Project`` in the Advanced Settings on your project, it will now not be installed.
