### ISSUE TITLE
Builder looks for  conf.py not  only in doc/docs and top-level, but also in directory named 'docker' .

### ISSUE THREAD

**Issue by tuxknight** [rtfd/readthedocs.org#1351]
Here is my own notes written in RST
  
    https://github.com/tuxknight/notes

It contains a conf.py in top-level directory and each sub-directory has its own conf.py .

According to the strategy metioned in  [official document](https://docs.readthedocs.org/en/latest/builds.html#sphinx) , the builder will look for conf.py  first in  doc/docs and then default to top-level documentation.

But in my case, it chooses the wrong conf.py which is in a directory named ‘docker' .

It could fix by setting the location of 'conf.py' as 'conf.py' . But it really wired that the builder chose the 'docker/confi.py' for default.

**Comment by gregmuellegger** [comment]
I think the main usecase for readthedocs is to support a documentation for a software package which lives sidebyside to it. So it assumes that the docs reside in a directory in the repository.

However the exact logic to find the `conf.py` is to search first inside of directories called `doc`, or `docs`. That does not exist in your case. So it searches the whole project. If there would only be one `conf.py` everything would work. But you have multiple onces in the repo, so it tries to prioritize one.

The way to do is to see if a path includes the substring `doc`, and **doc**ker does match that :) That's why it's behaving a little strange in your case.

Please add the path to the `conf.py` that you want to use for building on readthedocs in the admin panel.
