### ISSUE TITLE
Cannot use a customized markdown parser in sphinx

### ISSUE THREAD

**Issue by tqchen** [rtfd/readthedocs.org#1527]
I tried to use my customized markdown parser derived from recommonmark here https://github.com/dmlc/xgboost/blob/master/doc/conf.py#L44  But seems it do not take effect.

 Specifically, there has been some url remapping that did not happen. Maybe because readthedocs overrides this option afterwards?

**Comment by gregmuellegger** [comment]
We use [this template](https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl#L22) to create RTD specific config that will be appended to the `conf.py`. So your settings will get overwritten.

Maybe we can set the `source_parser` so that your setting won't get overwritten. I created #1531 to discuss this.
