### ISSUE TITLE
Minimize logic in our standard conf.py

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs.org#1534]
We currently have 2 `conf.py` files we generated:
- One we append to every build
- One we generate for users without a conf.py in their repo

I think we should remove a lot of the magic in our general `conf.py`, and keep it in the auto-generated one. The idea is that users can throw a repo with rst & md files, and we will generate docs for them without any configuration. But once they start using their own `conf.py` and building locally, we should keep the production settings as close to the local as possible.

Most of the Sphinx version requirements that we have are in our appended `conf.py` as well -- so if we remove some of the stuff that requires version checking (itself a specific version requirements, ironically), it should make RTD work with past releases again.

Refs #1531

**Comment by gregmuellegger** [comment]
:+1:

Related: #885

**Comment by gregmuellegger** [comment]
Hm, when using Sphinx for the documentation, aren't people going to build it locally first anyways before pushing it to readthedocs? Do you know of actual cases where people do not have a `conf.py` in their repository?

**Comment by stsewd** [comment]
Is this issue still relevant? I'm not sure of what lines we could remove since it just:

- Pass the source prefix to the context
- Set the rtd theme when there isn't one or when the default is given
- Add the rtd static path

If I understand correctly the html_context is used by the themes.
https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl

**Comment by stsewd** [comment]
We don't have much logic now I believe, most of the stuff is metadata from the build/rtd to feed the theme and the extension.

Closing now, feel free to reopen if you consider.
