### ISSUE TITLE
Support setup.py in nonstandard locations

### ISSUE THREAD

**Issue by soltanmm** [rtfd/readthedocs.org#1567]
[gRPC](https://github.com/grpc/grpc) is interested in hosting our docs on `readthedocs.org`, but from what we can tell there's no way to handle our directory structure. Due to the multi-language nature of the project, the Python subproject is not located at the git repository top-level and thus the `setup.py` file is not located at the git repository top-level. As much as we like readthedocs, and want to use it, it appears that we can't. Is there something we overlooked?

**Comment by gregmuellegger** [comment]
Directly running your setup.py will probably not work, that is right. But I can suggest a workaround for that. Create a `requirements.txt` file that contains the dependencies for your project (if there are any that are not listed in setup.py) and then give it the path to your package directory inside the project. I tried this at the top level of your project:

```
$ cat requirements.readthedocs.txt 
src/python/grpcio/

$ pip install -r requirements.readthedocs.txt          
Processing ./src/python/grpcio
Collecting enum34==1.0.4 (from grpcio==0.10.0a0->-r requirements.readthedocs.txt (line 1))
  Downloading enum34-1.0.4.tar.gz
Collecting futures==2.2.0 (from grpcio==0.10.0a0->-r requirements.readthedocs.txt (line 1))
  Downloading futures-2.2.0-py2.py3-none-any.whl
Collecting protobuf==3.0.0a3 (from grpcio==0.10.0a0->-r requirements.readthedocs.txt (line 1))
  Downloading protobuf-3.0.0a3.tar.gz (88kB)
    100% |████████████████████████████████| 90kB 892kB/s 
Requirement already satisfied (use --upgrade to upgrade): setuptools in /home/gregor/.virtualenvs/tmp-c0c1e324c634c3a/lib/python2.7/site-packages (from protobuf==3.0.0a3->grpcio==0.10.0a0->-r requirements.readthedocs.txt (line 1))
Building wheels for collected packages: enum34, protobuf
  Running setup.py bdist_wheel for enum34
  Stored in directory: /home/gregor/.cache/pip/wheels/d1/b2/2c/b51348698bd1921a226cf48d790b282d86fb4bcf9728afd6b3
  Running setup.py bdist_wheel for protobuf
  Stored in directory: /home/gregor/.cache/pip/wheels/eb/03/a7/4957f6b33d38cbf9c5ee52e8956cbfd2ec2c300b7243478b09
Successfully built enum34 protobuf
Installing collected packages: enum34, futures, protobuf, grpcio
  Running setup.py install for grpcio
    Complete output from command /home/gregor/.virtualenvs/tmp-c0c1e324c634c3a/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-1Axuwb-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-o9EuDK-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/gregor/.virtualenvs/tmp-c0c1e324c634c3a/include/site/python2.7/grpcio:

...
```

The build finally failed because of a gcc error. But that is probably my local setup. So try creating the requirements file and add the path for it in the corresponding field in your project admin panel on readthedocs.org (in the Advanced Settings tab).

We are currently working on a new build runner which will address this problem as well. So we will be able to support your usecase cleanly probably somewhere in the next couple of weeks. Stay tuned :)

**Comment by ericholscher** [comment]
We should document the use of the requirements file in this way in the FAQ

**Comment by soltanmm** [comment]
Alright, we'll take a look at that option for now. Thanks!

cc @nathanielmanistaatgoogle

**Comment by ericholscher** [comment]
The work around for this is now documented in #1582
