### ISSUE TITLE
Automatic build doesn't run after changing git repo location

### ISSUE THREAD

**Issue by tillig** [rtfd/readthedocs.org#1569]
Our documentation used to be at https://github.com/autofac/Autofac.git but we moved it to https://github.com/autofac/Documentation.git for easier maintenance.

After updating the repo URL in the ReadTheDocs admin dashboard, I was able to force a build, but since then the build fails to automatically build after changes to the repo.

Is there something I need to do to signal the system to stop watching the old repo and watch the new one?

**Comment by gregmuellegger** [comment]
We use GitHub post commit hooks in order to know when you changed something in your repository. When you move the docs from one repo into another then you need to setup the hooks in the new repository. Therefore go into the admin panel on GitHub for your project and look for "Webhooks & services". See this document for more information: https://docs.readthedocs.org/en/latest/webhooks.html

You can also find the URL that you need to use in GitHub on your Read the docs project homepage in the bottom right corner.

**Comment by tillig** [comment]
Yup, that did it. Thanks!
