### ISSUE TITLE
Docblock Support

### ISSUE THREAD

**Issue by robertmain** [rtfd/readthedocs.org#1607]
Is there any particular reason that read the docs doesn't just support standard docblock?

**Comment by ericholscher** [comment]
What is "standard docblock support"?

**Comment by robertmain** [comment]
It's a fairly common syntax throughout most languages, it also means you
can reuse your docblock documentation rather than adding another markdown
file to your project

**Comment by agjohnson** [comment]
@robertmain Because there is no standard for these blocks across languages, and without language specific parsing of these files, all we get is a list of comment blocks. For proper reference documentation, we need to contextualize these blocks -- what namespace/class/object/whatever is this comment block in? -- and so need language specific parsing for each implementation.

We've added basic jsdoc support on rtfd/sphinx-autoapi, we'd love to have something from the php community there too. If phpdoc can output a serialized format with some context around these blocks, it should be easy. I've opened rtfd/sphinx-autoapi#29 to continue this discussion. This is a little off our roadmap currently, so feel free to start work on it.
