### ISSUE TITLE
How to disable the "You are not using the most up to date version" warning

### ISSUE THREAD

**Issue by lennartkoopmann** [rtfd/readthedocs.org#1616]
Thanks for making ReadTheDocs happen first of all. I just discovered that the .com offering launched so you can expect us from [Graylog](http://www.graylog.org/) to upgrade soon.

We are releasing v1.2 of our software as an RC these days. When activating the `1.2` branch in RTD I noticed this warning on the RTD pages of `1.0` and `1.1`:

> You are not using the most up to date version of the library. 1.2 is the newest version.

The current default version is `1.1` so everybody who opens the documentation is seeing that warning. This is misleading because `1.2` is not stable yet.
- Can we disable that warning somehow?
- Can we change the copy/text of the warning? The warning makes sense once `1.2` is released GA but we are not documenting a _library_.

Thanks again and let me know if you need any more information.

**Comment by agjohnson** [comment]
@lennartkoopmann great! we're slowly rolling out more information about readthedocs.com, so stay tuned

Looking into this a bit, I thought there was a clear way to disable that feature, but there doesn't seem to be. Maybe this should live as an RTD theme option, and the javascript improved on to detect if the theme can take the warning.

The block gets added here, but it doesn't do much to detect whether it should add the block, and it skips i18n altogether:
https://github.com/rtfd/readthedocs.org/blob/f7a05381cfe96fb8480e2f5dccba45fc7127957d/readthedocs/core/static-src/core/js/doc-embed/version-compare.js#L9-L32

**Comment by ThomasWaldmann** [comment]
We have same problem:
- bad wording (our sw is not a library)
- that note seems to recommend that our 1.1.0b1 beta is better than our 1.0.7 stable release.

**Comment by wohali** [comment]
Gentle bump on this with a few additional thoughts:

1. A way to customize the use of the word 'library', since many projects using readthedocs aren't libraries
1. Proper i18n (possibly as a way to solve the last point)
1. A way to completely disable the warning
1. Possibly a "whitelist" of versions not to tag. For instance, Apache CouchDB supports (n, n-1) versions. So, the latest release in our 1.x and 2.x lines are supported. We wouldn't want to show the warning on our 1.7.0 page (if it's the latest 1.x release), but we would want to show it on 1.6.1 and 2.1.0 (if 2.1.1 is the latest 2.1.1 release).

**Comment by humitos** [comment]
> We are releasing v1.2 of our software as an RC these days. When activating the 1.2 branch in RTD I noticed this warning on the RTD pages of 1.0 and 1.1

After https://github.com/rtfd/readthedocs.org/pull/3331 got merged, if `1.0` and `1.1` are tags, this shouldn't be a problem anymore :)
