### ISSUE TITLE
OpenCL Header

### ISSUE THREAD

**Issue by RyanHope** [rtfd/readthedocs.org#1646]
I am trying to document a package the depends on pyopencl. pyopencl fails to compile because the opencl header can not be found. Installing the Intel OpenCL package on the server should be enough to get pyopencl to build...

https://software.intel.com/en-us/articles/opencl-drivers

**Comment by gregmuellegger** [comment]
We cannot support building arbitrary C modules because of the issues with needing to install all the header files etc. Please follow our guide on this from the FAQs: http://docs.readthedocs.org/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

You can mock out the dependencies that you cannot get to work on readthedocs.org. Please also remove the packages that you mock out from your requirements.txt that is used during the readthedocs.org build
