### ISSUE TITLE
Server error on "Social Accounts" page

### ISSUE THREAD

**Issue by str4d** [rtfd/readthedocs.org#1668]
I added GitHub to my social accounts page, and when it returned to Read the Docs, it simply showed the fail whale:

```
          .
         ":"
       ___:____     |"\/"|
     ,'        `.    \  /
     |  O        \___/  |
   ~^~^~^~^~^~^~^~^~^~^~^~^~

   Fail.  Check back in a bit!
```

Now whenever I navigate to https://readthedocs.org/accounts/social/connections/ the whale is there, and I cannot sync projects from GitHub. My username on RtD is the same as here.

**Comment by gregmuellegger** [comment]
Thanks for the report!
@ericholscher @agjohnson could you provide us with stacktrace from the server logs somehow?

**Comment by firectrl** [comment]
i have the same question like it.
how can i do the next?

**Comment by markus-sara** [comment]
Hi, I have the same problem: "Fail.  Check back in a bit!" on the social/connections page.
This started after signup with new account and adding the first github connection. This was beginning of October, so waiting does not help :-(

Since I have not done any work, I would be happy to delete my account and start over, but I see no way to do that.

Please advise (or delete my account: mvd-sara). If you need a stack trace for debugging, I am happy to repeat the problem on demand.

Thanks in advance, Markus.

**Comment by sandino** [comment]
Hi, same problem as of markus-sara, but I couldn't add a github connection.

**Comment by agjohnson** [comment]
Okay, finally had time to dig this one up. It's an issue with `django-allauth`, the underlying issue is GitHub accounts without a name set. I've raised a PR at: pennersr/django-allauth#1212

**Comment by agjohnson** [comment]
Addressing this with #1850, we will hopefully have that out next week some time.

**Comment by sandino** [comment]
But the issue is still there, I still cannot open the page https://readthedocs.org/accounts/social/connections/

**Comment by agjohnson** [comment]
#1850 has yet to be deployed.

**Comment by agjohnson** [comment]
Everything has been deployed, this should be resolved now. Feel free to reopen if this bug is still present.

**Comment by markus-sara** [comment]
Thanks, works for me!
