### ISSUE TITLE
No index.md generated

### ISSUE THREAD

**Issue by aalonsog** [rtfd/readthedocs.org#1680]
Hi, 

suddenly and using Markdown builder, it doesn't generate the index.md file from my README.md file.

The result is that I get a 

404 Not Found
nginx/1.4.6 (Ubuntu)

in the main page of my docs. 

Thanks!

**Comment by ericholscher** [comment]
This was done because it broke a number of things downstream of that copy. For instance, links to the "Edit on GitHub" were broken because the file didn't actually exist. The best way to fix this is to actually include an index.md inside your repo.

Also, we should be serving README.html as the root index of pages from our nginx config, so that should continue to work. Do you have the URL that is breaking?

**Comment by aalonsog** [comment]
Hi, many thanks for your reply :)

This is happening in the three repos I have linked: 

http://fiware-pep-proxy.readthedocs.org/en/latest/
http://fiware-cloud-portal.readthedocs.org/en/latest/
http://fiware-idm.readthedocs.org/en/latest/

Yes, /README is working for all of them, I was trying to configure a redirect from / to /README (that's a good solution for me), but I didn't succeed... Do you know if is it possible?

I also tried including the index.md directly (and it works) but this way I loose the readme in github.... I don't want to have two files duplicated.

**Comment by aalonsog** [comment]
Finally I have created a sym link with the index.md pointing to README.md. 

So for me the issue can be closed :)

Thanks!
