### ISSUE TITLE
Windows support for builders

### ISSUE THREAD

**Issue by vasily-v-ryabov** [rtfd/readthedocs.org#1711]
I'm trying to build the docs for the [pywinauto](https://github.com/pywinauto/pywinauto) package that is Windows only and relies on pyWin32 package (see [ReadTheDocs pywinauto project](https://readthedocs.org/projects/pywinauto/)).

It looks like ReadTheDocs builder runs on Linux by default. Are there plans to enable Windows Python to build the docs?

Current builder produces obviously incomplete docs.
[Docs built on my local Win7](http://pywinauto.github.io/docs/contents.html)
[Docs built by ReadTheDocs](http://pywinauto.readthedocs.org/en/latest/contents.html)

On ReadTheDocs there is no `ChangeLog` section and every page inside `Source code reference` is empty (like [that](http://pywinauto.readthedocs.org/en/latest/code/pywinauto.findwindows.html) in compare with [a good one](http://pywinauto.github.io/docs/code/pywinauto.findwindows.html)).

I'm not sure current Linux builder is able to build our docs. Using Windows builder would be much more convenient.

**Comment by agjohnson** [comment]
We, the core team, don't have any plans to take this on right now, but you are more than welcome to support this use case yourself. We'd be happy to discuss what this means in terms of work.

RTD uses symlinking extensively, which will require some architectural changes to support Windows. We aren't familiar with Windows, and don't really have any use cases for using Windows builders, so we would rely on the community to support this feature if it was important enough.

You can also look into the [sphinx-autoapi](http://github.com/rtfd/sphinx-autoapi) package we are working on, it parses source code rather than executing it to determine docstrings. This might get around the dependency on Windows, though the autoapi feature does not have feature parity with autodoc yet.
