### ISSUE TITLE
Support setuptools/distribute extras dependencies

### ISSUE THREAD

**Issue by domenkozar** [rtfd/readthedocs.org#173]
For example, I have in one of my projects:

      extras_require={
          'test': ['webtest', 'nose', 'coverage'],
          'develop': ['bpython', 'z3c.checkversions [buildout]'],
      },

For API documentation, 'test' packages need to be installed, would be nice if rtd supported this feature :)

**Comment by vrde** [comment]
Hello form the future! I agree with @remcohaszing, `extras_require` is the standard approach, can someone from rtfd reopen this issue?

**Comment by ericholscher** [comment]
What do you want to be able to do that you can't do now? Can't you just specify the extras_require in your requirements file?

**Comment by vrde** [comment]
hi @ericholscher!

Instead of `requirements.txt`, I'd like to use my `setup.py` to specify dependencies to build the docs. Right now in our project we have duplication between [`setup.py`](https://github.com/bigchaindb/bigchaindb/blob/develop/setup.py#L25) and [`requirements.txt`](https://github.com/bigchaindb/bigchaindb/blob/develop/docs/requirements.txt). Yes, it's not duplicated anymore if we remove the dependencies from `setup.py`, but I really like the idea to keep everything in a single place.

In the advanced settings I can only set the path to the `requirements.txt`, but it'd be a nice idea to support also dependencies specified in `extras_require`.

![image](https://cloud.githubusercontent.com/assets/134680/13524404/4628f608-e1fb-11e5-87b7-3e50ca108bca.png)

**Comment by agjohnson** [comment]
I'm going to reopen this. I think stronger integration with `setup.py` would be a good thing for module maintainers, and other folks that have no other need for requirements files. This functionality likely won't make it into project options, but would be a good addition to our `readthedocs.yaml` and https://github.com/rtfd/readthedocs-build

Leaving it open here for now, though it will likely require work in multiple repos. If anyone wants to tackle this, there is some previous work adding similar options to the yaml spec here and in readthedocs-build.

**Comment by Themanwithoutaplan** [comment]
I'm not a fan of the setuptools extensions of setup.py but it would be nice to see `pip install -e .` being used as this will pickup any dependencies required where `python setup.py install` will not. :-(

**Comment by kdeldycke** [comment]
Discussion about this issue now moved to https://github.com/rtfd/readthedocs.org/issues/2368 I guess.
