### ISSUE TITLE
PDF generation for Sphinx and RST documentation is not working as expected.

### ISSUE THREAD

**Issue by Jacob-SAE** [rtfd/readthedocs.org#1861]
https://readthedocs.org/projects/sae-manual/

This is our project URL. For some reason the PDF is only generating with indices at the bottom and none of the content in the index.rst .

I can't for the life of me figure if there is something completely obvious that I'm missing; however, I've tried it with a completely empty repo and I'm still having trouble generating a working PDF.

**Comment by agjohnson** [comment]
Does this work locally for you? You'll need to install latex and pdf generation tooling.

**Comment by Jacob-SAE** [comment]
This will build locally without issue for my full documentation.

**Comment by agjohnson** [comment]
I'm a little confused what the issue is here. The PDF output seemingly has everything your HTML docs do and I see the content from this index.rst:

https://github.com/SharpAuctionEngine/SAE-Manual/blob/master/docs/source/index.rst

in the output PDF.

**Comment by Jacob-SAE** [comment]
I'm attempting to view the documentation I have listed on http://sae-manual.readthedocs.org/en/latest/# , in PDF format. I view it locally and it appears fine; however, when I view the PDF at https://media.readthedocs.org/pdf/sae-manual/latest/sae-manual.pdf

I see an empty PDF that is 7 pages long; whereas, the locally generated PDF is 70+ pages long.

**Comment by agjohnson** [comment]
This seems to be a local caching issue then, I get a PDF with more than 7 pages.

**Comment by Jacob-SAE** [comment]
Indeed it was. I checked a few other sources and they weren't having an issue either.

Terribly sorry for the inconvenience, certainly blew it out of proportion.

Thank you for your assistance @agjohnson

**Comment by agjohnson** [comment]
Sure, no problem.

I will note that this appears to be an open source documentation project for otherwise closed source software, which goes against the spirit of the Read the Docs community site. The community site exists as a resource for the open source community, though we have no explicit policy against commercial use at the moment. If you do find RTD helpful, or appreciate our support, consider donating or contacting us about a paid plan or support contract.
