### ISSUE TITLE
New account created when linking accounts

### ISSUE THREAD

**Issue by dirn** [rtfd/readthedocs.org#1875]
After logging into my account (dirn) I saw that there were no social accounts linked. This seemed strange, but I hadn't logged in for quite some time so I figured the authorization had expired. When I linked my GitHub account, I was switched to a new account (andy2).

My guess is that this happened as a result of having a different email on GitHub than I use for Read the Docs. (I changed my GitHub email address a few months ago; perhaps this is why the account didn't appear as linked anymore.)

Currently I'm unable to link the GitHub account or associate the new email address with my real account because they are associated with andy2. Can someone please remove that account so I can associate everything with dirn?

I can confirm via each email address if needed for verification.

**Comment by AaronSachs** [comment]
Running into the same here.

**Comment by Matthewrbowker** [comment]
Happened to me as well.  Attempting to fix resulted in my linked github account being unaccessable.

**Comment by agjohnson** [comment]
I haven't had luck replicating this yet. There seems to be something up with our usage of `django-allauth`, whether that is configuration on our end, or a bug we're triggering. I don't know the exact case why `django-allauth` will log out an authed user in this case, but it shouldn't be. This may be due to an email lookup or email mismatch between the GitHub/Bitbucket account, but I haven't had luck reproducing that case. `django-allauth` performs a lookup on verified email addresses, and if none exist, it forces logout and signup. #1850 introduces an updated version of `allauth`, though I haven't dug into recent changes to see if there are any changes there that would address this issue.

**Comment by arleslie** [comment]
Running into this issue as well.
@agjohnson my email is the same on my github and readthedocs.org.

**Comment by aydindemircioglu** [comment]
same here. 

steps to reproduce for me:

created a new account, connected it, seemed everything ok.
next day, link is not there. "You currently have no social network accounts connected to this account."
clicking on 'connect to github' yields "The social account is already connected to a different account."
switched to github, revoked the authority for readthedocs.
back to readthedocs. click on "connect to github" puts me to github.com and authorization request.
authorized. back to readthedocs, i get "The social account is already connected to a different account."
but i have only one github account and only one readthedocs account. :/

**Comment by dirn** [comment]
@agjohnson can anything be done to free up my email address and GitHub account so I can associate them with my (original) RTD account?

**Comment by jonafato** [comment]
I'm also having this issue. My account (jonafato) had no social accounts linked, so I logged in with github and ended up with a new account (jon2). Is there any way I can merge these two together?

**Comment by Matthewrbowker** [comment]
What is amazing is that there has been no answer from the readthedocs.org people on this issue when it affects such a large number of accounts.

**Comment by agjohnson** [comment]
@Matthewrbowker see my reply above. No new news yet.

**Comment by fbennett** [comment]
Also reported  at #2042

**Comment by ericholscher** [comment]
Yea, sorry about this whole mix up. It's a really silly thing that Allauth was auto-creating accounts when attaching a GitHub account. This seemed to happen when your GitHub account had a different email than your RTD account. I will be deploying a fix today that turns off this behavior.

Sorry again!

**Comment by dirn** [comment]
You got it fixed. That's the important part. I think it took me all of 2 minutes to do the steps above, so it wasn't a huge deal.

**Comment by agjohnson** [comment]
Reopening. Still noticing double accounts from allauth.

**Comment by ericholscher** [comment]
Newly created ones?

**Comment by agjohnson** [comment]
Aye, attached #2078 above.

**Comment by Kemp-J** [comment]
I appear to be having the same issue but with Bitbucket - attempting to link accounts via the "Import a project" page logs me out and sends me here to create a new account: https://readthedocs.org/accounts/social/signup/

Of course, I'm then not allowed to create said account because my email address is already on file. In my case my RtD and Bitbucket email addresses are the same.

**Comment by senarvi** [comment]
I never managed to link my GitHub account. It had a different e-mail address, but changing it to the same address I use in RTD didn't help.

**Comment by ericholscher** [comment]
Yea -- I have tried to recreate this locally using accounts with different email addresses locally and on GitHub -- it's quite hard to reproduce, which makes it hard to fix.

**Comment by ericholscher** [comment]
Believe this should now actually be fixed! Please let us know if anyone hits this again.

**Comment by agjohnson** [comment]
Also, a little background here: it was the buttons on the project import page which were previously setting the get args in the form `action`, which is invalid and overridden by hidden form elements. #2244 fixes this and should be deployed shortly.

**Comment by KI7MT** [comment]
I'm still having this problem. Tried all the suggested work-arounds with no luck.

**Comment by Dmitri-Sintsov** [comment]
I am also still having this problem. When I login as questpc, it does not display linked github project and does not allow to add social account from github because it already exists and also does not allow to import project because it also already exists (on that hidden github-linked account)

I also managed to build my project manually by using the URL suggested in #2052 
https://readthedocs.org/accounts/github/login/?process=login

(with browser session logged to github, of course).

But I did not try to do anything with that hidden account (neither change a email / password, nor unlinking project), just built the project manually.

I do not need to build my docs too much often. But I was worrying really a lot that linked project might be completely unaccessible. That would be really huge tragedy.
