### ISSUE TITLE
USERTrust certificate not supported by Ubuntu

### ISSUE THREAD

**Issue by arxanas** [rtfd/readthedocs.org#1885]
I'm getting the same error as in #1757, but there didn't seem to any resolution besides fixing the git URL. As far as I can tell, the Git URL is correct, because I can clone from it and visit the page in my browser fine. My project is at https://readthedocs.org/projects/projkit/. Any help?

**Comment by agjohnson** [comment]
We receive a certificate error when attempting to clone your repo:

```
$ git clone https://gitlab.eecs.umich.edu/eecs281/projkit.git
Cloning into 'projkit'...
fatal: unable to access 'https://gitlab.eecs.umich.edu/eecs281/projkit.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
```

Looks like this is due to the certificate you are using, which isn't supported in Ubuntu currently: https://bugs.launchpad.net/ubuntu/+source/ca-certificates/+bug/1481401

It shouldn't be much to add this ca cert however, we'll look into the changes in the coming weeks.

**Comment by arxanas** [comment]
Thanks for looking into this!

**Comment by arxanas** [comment]
The documentation successfully cloned and built, so this issue is no longer arising. Thanks for the help!
