### ISSUE TITLE
403 Forbidden Error

### ISSUE THREAD

**Issue by bucaran** [rtfd/readthedocs.org#1907]
I added a mkdocs.yml file to the root of my project, set the branch rtfd should point at to "readthedocs" just to test things out. The build indicates it was succesful, but I get a 403 Forbidden error.

* https://readthedocs.org/projects/shark/

* https://github.com/bucaran/shark/blob/readthedocs/mkdocs.yml

What am I doing wrong?

**Comment by bucaran** [comment]
It is fixed now. Basically, you must have an `index.md` inside your `docs_dir` directory.

Thanks! I love RTFD.

**Comment by Akanksha0919** [comment]
I am facing 403 forbidden issue with mkdocs
the individual htmls for different modules are working fine but the sandwich icon showing all "pages" gives 403 forbidden error
![image](https://github.com/readthedocs/readthedocs.org/assets/65400521/82eff34a-6f27-42db-a4d8-980f5ea121b1)

all the links have their own index.html which works fine but the page links on sandwich icon don't work. what do you think , is this the issue of permissions? because in mkdocs.yml file i have the following code : 
site_name: dynamic pricing documentation

theme:
  name: "material"

nav:
  - Intro Docs: index.md
  - evaluation documentation: evaluation.md
  - metrics documentation: metrics.md
  
plugins:
  - mkdocstrings

I think the only thing that is crucial to connecting to these md pages is the nav and plugin: mkdocstrings

how can i resolve this 403 forbidden error
