### ISSUE TITLE
Investigate whitenoise for file serving locally

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs.org#1911]
Whitenoise is a nice production ready Python media server. In production we use nginx, but it would be great to serve files from whitenoise instead of Django. 

https://github.com/evansd/whitenoise

This might also allow us to work around using the SendFile functionality, and just have it all be done in python. Main area is here: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/core/views.py#L502

**Comment by humitos** [comment]
@ericholscher do we still want to research about this? the link you pointed is dead.

**Comment by browniebroke** [comment]
The permalink for the broken from around that date:
https://github.com/rtfd/readthedocs.org/blob/e4958838a512b095d0bc8cdf8617c30cc9e489d4/readthedocs/core/views.py#L502

I don't know where this code lives now, but a quick search seems to point here:

https://github.com/rtfd/readthedocs.org/blob/8b7c2797f8ba152d277336146b708f246c1f1ad9/readthedocs/core/views/serve.py#L149

Just a small precision that Whitenoise does **static** file, not so much media files in the usual Django terminology. 

Finally, for local development, I found [this section](http://whitenoise.evans.io/en/stable/django.html#using-whitenoise-in-development) of the docs. One notable change is that `runserver` should be started with the `--nostatic` option.

**Comment by davidfischer** [comment]
To be 100% honest, I don't think whitenoise buys us a lot in our production setup. Whitenoise really shines with [static files in Django](http://whitenoise.evans.io/en/stable/django.html) (as opposed to user uploaded or generated files which Django calls "media files"). The biggest advantages of whitenoise I can see are:

* It handles generation (via `collectstatic`) of compressed versions of files for fast serving. This means that web servers like nginx don't need to compress the file on the fly (they typically cache it afterwards) before serving it.
* Whitenoise sets cache headers long in the future where appropriate.

The first advantage (compressed files) would buy us very little. It would require us to run `collectstatic` on all our webs as opposed to just one as every web would need access to all the static files and compressed versions. Since we are already serving these from Azure storage, this wouldn't buy us much. Azure storage is already optimized to serve static files reasonably fast.

It also wouldn't yield any advantages for build outputs -- only what Django calls static files. Since build outputs aren't generated with `collectstatic` we would need to generate compressed versions of those files ourselves to get the compression advantages. For some of our files (PDFs notably), these are already compressed and so savings would be nonexistent. For build artifacts, we are serving them from nginx not Django and nginx is reasonably optimized for serving static content and so again Whitenoise isn't going to somehow serve them faster.

Setting the cache headers would actually buy us a bit more but again not a ton. This would yield good advantages for static files on readthedocs.org but not really anything on HTML docs. Currently our CDN settings are a bit dumb and they don't let us set far future cache headers on files like `/static/css/core.79b638b7e64a.css` which should actually be able to be cached forever. When the file changes, the hash will change. However, HTML docs pages don't link to versions with this unique hash. When docs are built, they link to the unhashed version (eg. `https://media.readthedocs.org/css/readthedocs-doc-embed.css`) so that we can upgrade these files without building docs. So these improvements might help readthedocs.org serve a little faster but it won't really help at all with build outputs (HTML docs).

In general, I think Whitenoise is a huge advantage for a setup involving docker containers that are scaled horizontally or anything similar like Heroku. I'm not sure it buys us a lot in our setup. I'm in favor of just closing this.

**Comment by davidfischer** [comment]
If we ever do decide to switch from storage for static files currently Azure storage to whitenoise, it shouldn't be that big of a deal but again the advantages are small. The work we already did to cleanly separate "static" files from "media" files would still be necessary (`collectstatic` used to write to a subdir of `media`). We would need to change our deploy process to run `collectstatic` on all web servers and then change the origin server for the CDN to be the .org origin servers instead of Azure storage.

**Comment by humitos** [comment]
Thanks David for all the data brought here. I'm closing this issue here. We can revisit if we consider in the future.
