### ISSUE TITLE
Upgrade tastypie to 0.13.0 release

### ISSUE THREAD

**Issue by jakirkham** [rtfd/readthedocs.org#1921]
> Updated tastypie from 0.11.1 to current master (commit 1e1aff3dd4dcd21669e9c68bd7681253b286b856) as 0.11.x is not compatible with Django 1.8. No suprises expected but we should ask for a proper release, see release notes: https://github.com/django-tastypie/django-tastypie/blob/master/docs/release_notes/v0.12.0.rst

Saw this note in the changelog. That commit was released as v0.13.0.

**Comment by ericholscher** [comment]
This is not a problem with our project, please direct it to tastypie.

**Comment by jakirkham** [comment]
Sorry that could have been more clear. That quotes text came from RTD's Changelog in the docs.

**Comment by agjohnson** [comment]
Reopening, we should try to use tastypie 0.13.0 instead of pinning a changeset:
https://github.com/rtfd/readthedocs.org/blob/e4958838a512b095d0bc8cdf8617c30cc9e489d4/requirements/pip.txt#L11

**Comment by jakirkham** [comment]
Alternatively, that changeset is 0.12.2.

**Comment by ericholscher** [comment]
More over, we should remove our dependency on API V1 and remove Tastypie as a runtime dependency at all. Though we'll need to keep v1 around for a while for backwards compat.

**Comment by berkerpeksag** [comment]
I've upgraded tastypie to 0.12.2 in https://github.com/rtfd/readthedocs.org/commit/5dfc2af555c0d09f3e96af8d901436cb6202fb8c. Since 0.13 doesn't provide important bug fixes for Read the Docs I think this can be closed now. Or perhaps we can change the issue title to "Deprecate API v1"?

I think the only place that uses the API v1 is `readthedocs/projects/management/commands/import_project_from_live.py` and it looks like it can be ported to API v2 easily.

**Comment by stsewd** [comment]
Tastypie is already updated to 0.13.0 https://github.com/rtfd/readthedocs.org/blob/master/requirements/pip.txt#L15

This can be closed.

**Comment by humitos** [comment]
Closing. Tastypie can't be upgraded more because tests fails and it doesn't worth the work since we need to deprecate it
