### ISSUE TITLE
support for my project

### ISSUE THREAD

**Issue by henrykironde** [rtfd/readthedocs.org#1927]
My project https://github.com/henrykironde/deletedret/tree/docbuild build well locally but has failed to build and create the desired docs on your server.

**Comment by agjohnson** [comment]
Please provide more information, this doesn't describe an actionable bug.

**Comment by henrykironde** [comment]
This is the docs home for the project  http://deletedret.readthedocs.org/en/docbuild/index.html.
If you try to go to the Submodules you should be able to see the code with the documentation, 
However in am only getting the Submodules names.  I have attached a sample image. and you could check my local committed HTML files here https://github.com/henrykironde/deletedret/tree/docbuild/docs/_build/html


![local-sampleout](https://cloud.githubusercontent.com/assets/5192965/12340437/e3ce5c3e-bae8-11e5-8c25-e1e077cae00a.png)

**Comment by agjohnson** [comment]
Your latest build shows failures due to missing dependencies during the html sphinx passes: http://readthedocs.org/projects/deletedret/builds/3637778/

Read more on our docs about mocking dependencies, my guess is you have C dependencies which we do not provide headers for. This requires mocking and removing those dependencies from your requirements.

**Comment by henrykironde** [comment]
I am closing this issue because i found the fix. 
Since readthedocs doesn't take care of the requirements by default, Use the project's setting in readthedoc( advanced settings) and check 
`"Install Project:"  Install your project inside a virtualenv using setup.py install`

and you may also give the path of the Requirements file:
