### ISSUE TITLE
django-guardian: style is broken

### ISSUE THREAD

**Issue by brianmay** [rtfd/readthedocs.org#2006]
Hello,

Something happened to break the style on the django-guardian project. It looks fine when built locally, however it is broken on [readthedocs](http://django-guardian.readthedocs.org/en/latest/installation.html).

This has resulted in several bug reports. https://github.com/django-guardian/django-guardian/issues/397 and https://github.com/django-guardian/django-guardian/issues/398.

I have asked about this on [stack overflow](http://stackoverflow.com/questions/35470532/readthedocs-broken-how-to-fix) however the only response I have had is a rating of -1.

As this looks like a readthedocs bug, I am now reporting a bug here.

Thanks.

**Comment by agjohnson** [comment]
Not sure what have changed, but your theme isn't loading the required css. We detect our theme by name and load the relevant css:
https://github.com/rtfd/readthedocs-sphinx-ext/blob/57ab2a5d93447b10bd952e514349bb1a39e1ebcb/readthedocs_ext/readthedocs.py#L75-L78

You are getting `badge_only.css` because it isn't our theme. You might have luck altering paths and using 'sphinx_rtd_theme' as the theme name.

**Comment by brianmay** [comment]
Oops. Hadn't realized the project was setting the theme to one included in the project. Have fixed this now by using ``sphinx_rtd_theme`` as per your suggestion, so will close this issue.
