### ISSUE TITLE
/latest/ URL 404

### ISSUE THREAD

**Issue by synkarius** [rtfd/readthedocs.org#2035]
## Details

Hello. I am the chief maintainer of the Caster project. Something I did with Git months ago (not sure what exactly) caused the following bug with ReadTheDocs:

The following URL is always a 404:
http://caster.readthedocs.org/en/latest/
-- but none of the others are. For instance, this works:
http://caster.readthedocs.org/en/latest/README/

It doesn't matter if I rebuild the docs. The same problem occurs.

* Project: http://caster.readthedocs.org

**Comment by ericholscher** [comment]
That's because we're looking for an `index.html` or `README.html` page -- we aren't able to configure nginx to look for a `README/index.html` page, so you need to make sure you create an index page. We were previously automatically copying the README over into the index, but that seemed hacky, and was removed.
