### ISSUE TITLE
Pre release version tags not parsed correctly

### ISSUE THREAD

**Issue by fasaxc** [rtfd/readthedocs.org#2036]
## Details

We made a tag 1.3.0-pre.5 but that was treated as a stable release instead of a pre (and promoted to the stable version of the docs).  PEP-440 says that it should be interpreted as a synonym for 1.3.0rc5:

> Pre-releases should allow a . , - , or _ separator between the release segment and the pre-release segment
> 
> Pre-releases allow the additional spellings of alpha , beta , c , pre , and preview for a , b , rc , rc , and rc respectively. 

If this issue is for a specific project or build, include the following:
- Project: project-calico
- Build #:

**Comment by fasaxc** [comment]
I think we'd prefer semver too.  FYI, the docs do explicitly say PEP-440 is the expected format.

**Comment by janmeier** [comment]
We'd like this as well for @sequelize/sequelize. The default for prereleases on npm is `-X` e.g. `4.0.0.-7`

**Comment by mcapuccini** [comment]
+1

**Comment by humitos** [comment]
from @fasaxc comment,

> We made a tag 1.3.0-pre.5 but that was treated as a stable release instead of a pre (and promoted to the stable version of the docs). PEP-440 says that it should be interpreted as a synonym for 1.3.0rc5:

This should be supported since what's RTD is doing is something like this:

```
>>> from packaging.version import Version
>>> Version('1.3.0-pre.5')
<Version('1.3.0rc5')>
```

The [code that is ran](https://github.com/rtfd/readthedocs.org/blob/a0a29e8bbb454d9296b91492d31ecbee396fe1fa/readthedocs/projects/version_handling.py#L165-L181) is similar to this one:

```
In [1]: from readthedocs.projects.version_handling import determine_stable_version

In [2]: from collections import namedtuple

# I'm creating this namedtuple here to simulate a Version model from RTD
In [3]: Version = namedtuple('Version', ('verbose_name',))

In [4]: version_list = [Version('latest'), Version('1.3.0-pre.5'), Version('1.2'), Version('1.3.0')]

In [5]: determine_stable_version(version_list)
Out[5]: Version(verbose_name='1.3.0')
```

----

from @janmeier comment,

> We'd like this as well for . The default for prereleases on npm is to append -X e.g. 4.0.0-7

This would be a post release for PEP-440: https://www.python.org/dev/peps/pep-0440/#implicit-post-releases

```
>>> Version('4.0.0-7')
<Version('4.0.0.post7')>
>>> 
```

Now, running this:

```
In [8]: version_list = [Version('latest'), Version('4.0.0-7'), Version('3.4.5'), Version('4.0.0-rc1'), Version('4.0.0')]

In [9]: determine_stable_version(version_list)
Out[9]: Version(verbose_name='4.0.0-7')

In [10]: 
```

It seems that `4.0.0-7` is the stable version for RTD, which I think it's correct considering PEP-440 but it's not the behavior wanted by @janmeier, since he is marking a PRE release with that name.

Another extended example using the post release (`4.0.0-7`):

```
In [10]: version_list = [Version('latest'), Version('4.0.0-7'), Version('3.4.5'), Version('4.0.0-rc1'), Version('4.0.0'), Version('4.0.1')]

In [11]: determine_stable_version(version_list)
Out[11]: Version(verbose_name='4.0.1')
```

Which I think it's also correct.

So, from my understanding everything should work following these rules.

**Comment by agjohnson** [comment]
Does anyone feel like QA'ing this on RTD or a local instance and determining if this is indeed still valid? I feel like this may have changed with some other work at some point.

**Comment by stsewd** [comment]
I did some local testing, this issue seems to be fixed.

As seen on the image, the stable version points to the commit with the 1.2.0 tag, and there is 2 pre-release tags.

![screenshot-2018-1-1 versions read the docs](https://user-images.githubusercontent.com/4975310/34470765-c92d73d4-ef06-11e7-841c-42073620c43e.png)

**Comment by humitos** [comment]
Thanks @stsewd for testing it. I'm closing this issue. Feel free to reopen it if you consider.
