### ISSUE TITLE
RTD autogenerates accounts, locking people out of projects

### ISSUE THREAD

**Issue by pmitros** [rtfd/readthedocs.org#2042]
I created an account on readthedocs.org yesterday or the day before. I linked it to my github repo. Everything was going fine until today. When I log in, it shows no projects, and says another account is already connected to my github repo. I appear to be permanently locked out. Username on both is `pmitros`.

Is there any way to fix it?

**Comment by fbennett** [comment]
I have the same issue, I think. I created an account this morning (four or five hours ago), then linked it to a GitHub account pushed docs for a project, and confirmed that the build went through successfully. BUT I noticed that the user ID showing in the upper-right corner of the page at some point showed as "frank2" rather than the "fbennett" ID that I had set when signing up.

I am able to log in to the "fbennett" account, but it is empty. Known passwords do not work on the "frank2" account (which I have no memory of creating). Because the slug for the project (citeproc-js) now exists, I am unable to manage the project on RTD.

(One additonal thought: when I cut-and-pasted the URL for the docs, I noticed that it was HTTP, not HTTPS. I didn't check when creating the account etc, but I was on HTTP, might it have been a MIM attack?)

In my case I'm not fussy about IDs, if I can get in again. Either transferring citeproc-js to fbennett, or moving the mail address from "fbennett" to "frank2" would be fine. Hope one of those is possible - but something odd does seem to be happening with logins.

**Comment by fbennett** [comment]
@pmitros: In my case, I visited https://readthedocs.org and searched for my project, then clicked on the icon under "Owners" to the right. That told me the project owner's ID. Had no luck logging in with that ID, but by logging out, calling up the "log in" page, and then clicking "reset it", I was able to send reset requests to some alternative mail addresses, one of which was on the account. After resetting the password, I was able to manage the project again.

**Comment by pmitros** [comment]
Thank you. That is useful. I found an alternative account and it did appear to have an autogenerated username (my first name). That's something I never use as a username. I'm not able to reset the password there, however:

* RTD profile page gives the username, but not the email
* Password reset page appears to require email
* There doesn't appear to be a recover email address option

**Comment by pmitros** [comment]
Ahhh.... I see. It's set to my primary github email account. Wow. That's some convoluted bug.

**Comment by fbennett** [comment]
It's a relief to know that I wasn't imagining things!

It all seems to work fine otherwise, but this definitely wants fixing. Bushwhacking is a bad first-run experience.

**Comment by ericholscher** [comment]
Yea, this appears to be an issue with django-allauth, which we use for the third party auth. We haven't been able to figure out exactly why it's happening.

**Comment by ericholscher** [comment]
I actually think it's just this: https://github.com/rtfd/readthedocs.org/pull/2052 -- which seems like a crazy thing to default on, but alas. Hopefully this fixes it!

**Comment by pmitros** [comment]
@ericholscher Thank you for fixing this, and for maintaining RTD. I was able to reassociate github with my normal account. 

(Another issue this highlights is the lack of a was a way to reset passwords by username. )
