### ISSUE TITLE
[Bug] Google Analytics is being missed

### ISSUE THREAD

**Issue by rmk135** [rtfd/readthedocs.org#2077]
## [Bug] Google Analytics is being missed

Hello Dear RTD Team!

I keep documentation for my open source project on RTD.org website and it works well for me (thanks a lot for this), but yesterday I found one interesting issues that looks like a bug, as from my side.

The issue is about missing Google Analytics initialization on the pages of my docs. I checked "Admin -> Advanced Settings -> Analytics code" and looks like my GA key is still in place. 

Also I made a quick look through the code of the pages (including JS) and I didn't find any initialization of GA with my GA key. Instead I found initialization of GA with different key, that is, perhaps, your tracking code that is global for all doc placements:

```
_gaq.push(["rtfd._setAccount","UA-17997319-1"]
```

I'm not sure is it possible to track GA analytics into 2 different accounts on the same page, but 100 kudos for you if this can be fixed ;)

Thanks,
Roman

* Project: dependency-injector

**Comment by agjohnson** [comment]
Yup, that's ours, however we do set a secondary GA tracker if you supply the tracker id. You'll find it set up in http://dependency-injector.readthedocs.org/en/stable/_static/readthedocs-dynamic-include.js, which is included by each doc page.

I'm going to close this issue here, however if you are noticing you aren't tracking anything in GA, that might be a separate issue. I'll assume that is with our implementation on our Sphinx extension, and can be addressed there[1] -- feel free to open a new ticket there

1: https://github.com/rtfd/readthedocs-sphinx-ext

**Comment by bcb** [comment]
@agjohnson that file holds the readthedocs tracking code, not the user's one.
