### ISSUE TITLE
Clickable repository URL is incorrect with `git` scheme

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2085]
When a project has a URL scheme of `git://...`, the clickable link is instead linked to `git//...`, which will result in a copied link of `http://git//...`

**Comment by etataurov** [comment]
This is caused by Django's `urlize` filter. Not sure what the best fix would be. Custom filter?

**Comment by humitos** [comment]
I just imported this repository to my local instance: `git//github.com/humitos/turtle-confusion-es.git` and the links to Edit or View in github work great.

The problem is in the project home page at RTD, `http://localhost:8000/projects/turtle-confusion/`, 

![captura de pantalla_2017-12-28_10-44-15](https://user-images.githubusercontent.com/244656/34415336-116dea96-ebbc-11e7-9a9c-c577bb76c6a2.png)

the URL linked there is: http://git//github.com/humitos/turtle-confusion-es.git

What should be the solution? Just replace the `git://` sheme by `https://` or what?

**Comment by stsewd** [comment]
I think this doesn't need to be a link, instead just show as _normal text_ (maybe with some style as background). Something like GitHub does.

![gh](https://user-images.githubusercontent.com/4975310/35486660-3ebdd074-043f-11e8-8280-fdccf1e22a4a.png)

Given that this _link_ is basically the clone url of the repo, not the project page, and there is already a field for that.

**Comment by humitos** [comment]
@stsewd mmm... Interesting. In the case that we don't want to make it a link, I'd say that we need to reorder them by showing the "Home Page" first and then "Repository" (excactly in the opposite order than now)

On the other hand, in the case of Github it makes sense to not be a link since you want to copy and clone the repo, but I think that use case is not applicable to RTD. I mean, I suppose that not many RTD users clone repos from RTD; but they may explore the repo more often.

**Comment by stsewd** [comment]
@humitos if the repo is from GitLab, Bitbuckert or GitHub, we could get a link, but if there is a public repo from other service (or a custom GitLab installation for example), what could we do then?

We also could generate the home page link when the project is created (in case of the known services). What do you think?

**Comment by stsewd** [comment]
@humitos now I came with a more simple solution p:. What about just checking the protocol? If it's `https?://` we put a link, otherwise, just plain text.

**Comment by humitos** [comment]
@stsewd I like the idea; if you want to propose a PR, I can review it :)
