### ISSUE TITLE
Permission denied error while building my project

### ISSUE THREAD

**Issue by bharath12345** [rtfd/readthedocs.org#2088]
## Details

I followed the documentation to install. Created a new project and gave the https url of my [public repo](https://github.com/bharath12345/bharath12345.github.io) to build the doc. However the build fails with the following error. It does not seem to be unix user permission issue. How to go beyond this error to have a successful build?

`Traceback (most recent call last):
  File "/home/gbd/readthedocs.org/readthedocs/doc_builder/environments.py", line 136, in run
    env=environment,
  File "/usr/local/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied`

**Comment by agjohnson** [comment]
This looks like a local installation. You'll find more information in your log files. Not much we can do to support external installations however, our core team doesn't have the focus for this outside contracted support.

**Comment by humitos** [comment]
This issue is being marked as `Community Effort`. The core team will try to facilitate resolution with this issue, but without the resources to support external installations outside of our production environment, we must rely on the community to help.

You can read more information on our philosophy around supporting Read the Docs as an open source and volunteer run effort here: http://docs.readthedocs.io/en/latest/open-source-philosophy.html

Besides that, you also can use Stack Overflow for this problem and receive more help from the community.
