### ISSUE TITLE
Mock C extension module: the case of Pyqt

### ISSUE THREAD

**Issue by SylvainCorlay** [rtfd/readthedocs.org#2093]
I have not been able to successfully make shims for `PyQt`. (Some projects shim some of the pyqt submodules but not all of it.)

I imagine that the special case of pyqt (4 or 5) is sufficiently common for it to be useful for other people, hence the issue.

Is there anyone who has a good example of how to mock pyqt for readthedocs? Would it be in scope for readthedocs to handle pyqt?

**Comment by agjohnson** [comment]
I have thought about an extension that provided automatic mocking for common modules that require mocking. It's nothing I've ever bothered to write though. It would still require the user not install those dependencies first, which is where most users hit issues in the first place.

I've also thought maybe RTD should inspect dependencies and warn, but that's definitely a ways off our current roadmap.

To successfully mock out qt dependencies, make sure you aren't setting any qt dependencies via `setup.py` and/or `requirements.txt`. You should be able to mock out the modules normally, afaik.

**Comment by humitos** [comment]
Hi @SylvainCorlay! I wanted to check with you if you still have this issue? If you already solve it, can you please share your solution?

Besides, I found similar situation on these issues https://github.com/rtfd/readthedocs.org/issues/2387 and https://github.com/rtfd/readthedocs.org/issues/2511 that you may find useful.

I'm closing this issue since it's quite old and there was no updates. Please, feel free to reopen it if you consider.
