### ISSUE TITLE
swig not available

### ISSUE THREAD

**Issue by andy-maier** [rtfd/readthedocs.org#2094]
## Details

I am trying to build a project (pywbem) that has a dependency on the python package "M2Crypto". I do have a requirements.txt file that specifies that dependency, and it being attempted to be installed. 

However, M2Crypto needs the "swig" utility during its install, and swig does not seem to be available on readthedocs.org.

Because swig is a fairly standard tool that is needed by a number of Python packages, may I ask for it to be installed on RTD?
- Project: pywbem
- Build #: 3853463

**Comment by agjohnson** [comment]
You can also mock out dependencies, see our FAQ on our docs for more information. `swig` can be added via it's APT package, feel free to open a PR against our docker build images here: https://github.com/rtfd/readthedocs-docker-images/blob/master/base/Dockerfile

**Comment by tgoodlet** [comment]
@agjohnson I'm assuming you're referring to the *mocking* docs [here](http://read-the-docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules).
So now I'm quite confused.

The [`pip` documentation](https://packaging.python.org/requirements/#requirements-files) clearly implies that you need to include deps you expect to be auto-analyzed in your `install_requires` in order for `pip install mypackage` (where `mypackage` has some direct dep that requires SWIG or other C exts) to work. 

You've suggested mocking the dependency.  Afaict your definition of mocking also implies that you do not include the dep in `install_requires`. This of course breaks install from `pypi` (since I don't believe there's any way to have `pip` install with a `requirements.txt` that was somehow packaged with the `sdist`). 

So is it that `pip install mypackage` and readthedocs are not compatible when you have a C dep? The only other approach I can imagine is that RTD gives you the some kind of env variable or other to allow your `setup.py` to avoid inserting your dep at runtime.

**Comment by tgoodlet** [comment]
For anyone else running into this it seems you can also hack around it using the ['READTHEDOCS' env var](http://read-the-docs.readthedocs.io/en/latest/faq.html#how-do-i-change-behavior-for-read-the-docs) to conditionally modify `install_requires` in your `setup.py`.

**Comment by humitos** [comment]
@tgoodlet these are the docker files for 

* the `latest` version: https://github.com/rtfd/readthedocs-docker-images/blob/master/Dockerfile
* the current one at production: https://github.com/rtfd/readthedocs-docker-images/blob/2.x-upgrade/Dockerfile

There is another person that did this: https://github.com/jhale/readthedocs-docker-images/commit/36408c6598934a4d16e70e47ede9263b20ff75f3 and I think it should be enough.

**Comment by humitos** [comment]
Closing in favor of https://github.com/rtfd/readthedocs-docker-images/issues/15
