### ISSUE TITLE
My RTD Server Always Builds The Old Commit

### ISSUE THREAD

**Issue by MrMYHuang** [rtfd/readthedocs.org#2186]
I installed RTD server on CentOS 7 on my computer (hostname dsrl2) by this tutorial:
http://docs.readthedocs.io/en/latest/install.html

Then, I manually imported a sphinx git repo 'st' on a path on my dsrl2 to my RTD server. The import URL I gave is: ssh://dsrl2/home2/grad97/myh/git/st/.git
The repo has only one branch 'master.'
My RTD server built the document successfully.
However, my problem is: after I made some file changes and commits to the repo. I tried to use curl to rebuild the document of the latest commit by command:
curl http://the-ip-of-dsrl2:8000/build/st -d ""
The debug message of my RTD server showed that it did build the document. However, it built the document of the old commit, not the latest commit!
Does anyone know what the wrong is?

I also notice a strange time problem. The time showing in the RTD server console debug message are 13 hour earlier than the time showed from Linux 'date' command.
For example, if I run the curl command to build the document at a time 17:02 (05:02 pm) showed from date command, there is a debug message showed in the RTD server console
[03/May/2016 04:02:55]"GET /build/st HTTP/1.1" 200 31
Is this time problem related to the previous commit problem?

**Comment by myhlivecom** [comment]
I am continuing finding the commit problem. I find the webhook:
curl http://the-ip-of-dsrl2:8000/build/st -d ""
will invoke a python function 'generic_build' to rebuild the documents of the imported git repo.
(The imported git repo is located in e.g.:
/home2/grad97/myh/git/rtd/checkout/readthedocs.org/user_builds/st/checkouts/latest
)
I looked into generic_build source code. It seems that generic_build doesn't pull or fetch commits from the original repo to the imported git repo before rebuild documents.
So, is this a limitation of the RTD server that it can't rebuild the latest commit in the original repo if the repo is imported MANUALLY from places EXCEPT GitHub, Bitbucket, ...?

**Comment by myhlivecom** [comment]
I looked into RTD source files and hacked the Git backend to solve the commit problem.
The file I hacked is:
readthedocs/vcs_support/backends/git.py
Search "def fetch" in git.py and replace its following line:
code, out, err = self.run('git', 'fetch', '--tags', '--prune')
with
code, out, err = self.run('git', 'fetch', '--prune', '--prune')
(Don't reduce '--tags' to empty string. Otherwise, the fetch would fail)

So, in this time, I rethink the commit problem should be:
generic_build (or function calls in it) update the imported git repo (in somewhere of source files I don't find). The update uses git.py to fetch commits from the original repo. However, git.py only fetches tagged commits due to '--tags' option. If master branch of the original repo points to a (the latest) commit without a tag, git.py will not fetch the commit to the imported repo. So, my workaround is to modify fetch in git.py, removing '--tags', so git.py will fetch all commits.

**Comment by myhlivecom** [comment]
Another time problem in this issue has been also resolved. The problem is related to the Django timezone setting TIME_ZONE. The default timezone value of the RTD server is located in:
readthedocs/settings/base.py
User can overwrite the default by creating the file:
readthedocs/settings/local_settings.py
and overwriting TIME_ZONE variable.

**Comment by myhlivecom** [comment]
Does anyone know why the git backend, git.py, fetch only tagged commits with '--tags' option? Is this a bug?

**Comment by agjohnson** [comment]
This bug is being marked as community effort. The core team will try to facilitate resolution with this issue, but without the resources to support external installations outside of our production environment, we must rely on the community to help.

You can read more information on our philosophy around supporting Read the Docs as an open source and volunteer run effort here:
http://docs.readthedocs.io/en/latest/open-source-philosophy.html

If anyone has any update or fix here, I'm sure the help would be appreciated.

**Comment by shidarin** [comment]
I suspect this issue can be closed.

@MrMYHuang you need to upgrade your server's version of git. Prior to git 1.9, fetch --tags would fetch *only* tags and not other references. After 1.9 it fetches tags in addition to other references. See [this StackOverflow answer](https://stackoverflow.com/questions/1204190/does-git-fetch-tags-include-git-fetch)

Based on RTD source code you found, I suspect the RTD server requires a minimum of git 1.9. Once I upgraded git on my server, RTD builds will now update the branches before a build.

**Comment by MrMYHuang** [comment]
Thank you, shidarin.
