### ISSUE TITLE
Download Link Could Be Missed in sphinx_rtd_theme Sidebar

### ISSUE THREAD

**Issue by MrMYHuang** [rtfd/readthedocs.org#2192]
I find in a rare case, the generated HTML docs using sphinx_rtd_theme miss a download link in the sidebar. For example, http://docs.readthedocs.io has a sidebar with PDF, HTML, and ePub download links. Once, I found my RTD server correctly built all PDF, HTML, ePub downloads, however, the generated HTML docs sidebar showed only HTML and ePub download links. The link to PDF download was missing! After I checked the build log, I found the cause: RTD server built docs in this order: HTML, ePub, PDF. On other word, the HTML docs was built before the PDF doc. If there is no existing built PDF during building the HTML docs, sphinx_rtd_theme won't write the PDF download link into the sidebar of HTML docs.
A workaround is: after a success build with PDF, rebuild the HTML docs once.

This bug could be resolved by reordering the HTML build to the last one, e.g. the order:
PDF, ePub, HTML.

**Comment by agjohnson** [comment]
Your issue is likely that your server wasn't correctly responding to the API
requests to add this information. There is a preliminary pass to add this info
in the templates, but the response from the server rebuilds this menu.

Something is wrong with your installation. Marking this community effort, as
core team doesn't have the resources to support external installations.

**Comment by myhlivecom** [comment]
Hi agjohnson,

I also think this maybe a problem of my installation. Actually, at first, I imported my sphinx document to my RTD, my RTD failed to build the PDF version, because I didn't install full Tex Live. Then, I installed the full Tex Live, and my RTD rebuilt the PDF version successfully. However, the PDF download link was still missing in sphinx_rtd_theme Sidebar. The download link appeared after the second rebuild of the PDF version.

Though there is a workaround for this download link missing problem, I still hope that if changing the build order of RTD is not too difficult to code, please someone change it. It may save times of other people to figure out and work around this problem in their RTD servers.

**Comment by stsewd** [comment]
@MrMYHuang RTD gets that information dynamically from an API endpoint, so is always fresh, doesn't matter the build order. And I wasn't able to replicate this on my local installation.

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).
