### ISSUE TITLE
Why is RTDs configuration file named readthedocs.yml without leading dot?

### ISSUE THREAD

**Issue by Paebbels** [rtfd/readthedocs.org#2211]
I found the ReadTheDocs [configuration file](https://docs.readthedocs.io/en/latest/yaml-config.html) documentation. The config file `readthedocs.yml` is currently in beta state.

Why did you name it so, especially without a leading dot?
All other cloud based services, configured by a `*.yml` file I know of, are using this format: `.service.yml`.

**Comment by agjohnson** [comment]
There's no strong reason for it one way or the other, and certainly no standard for this. A number of services and local tooling use non-hidden files, so we followed suit. This is not just a configuration for our service, this file was meant to eventually allow for local execution as well -- to produce a similar command chain as our servers.

I could certainly see having an alternative naming for folks that would rather have these files hidden though. This would be implemented on https://github.com/rtfd/readthedocs-build. Closing the issue here, if anyone wants to take this on, the work should be fairly minimal to support a secondary `.readthedocs.yml` file.

**Comment by Paebbels** [comment]
As far as I can see, it's already implemented. One just needs to extend the file pattern...

[`config_files = list(find_all(path, CONFIG_FILENAME))`](https://github.com/rtfd/readthedocs-build/blob/master/readthedocs_build/config/config.py#L331)

**Comment by skirpichev** [comment]
https://github.com/rtfd/readthedocs-build/pull/17 add support for .readthedocs.yml.
