### ISSUE TITLE
readthedocssinglehtmllocalmedia build gets killed

### ISSUE THREAD

**Issue by jnikula** [rtfd/readthedocs.org#2227]
## Details
- Project URL: https://readthedocs.org/projects/kernel/
- Build URL (if applicable): https://readthedocs.org/projects/kernel/builds/4044873/
- Read the Docs username (if applicable): jani
## Excepted Result

Build passes, duh. ;)
## Actual Result

The build gets killed while building "readthedocssinglehtmllocalmedia" with code 137. I presume this is due to too much resources being used. I added quite a bit of documents to build.

python /home/docs/checkouts/readthedocs.org/user_builds/kernel/envs/sphinx-wip/bin/sphinx-build -T -b readthedocssinglehtmllocalmedia -d _build/doctrees-readthedocssinglehtmllocalmedia -D language=en . _build/localmedia

The "readthedocsdirhtml" build that I want and also the "json" build pass fine. I do not know what "readthedocssinglehtmllocalmedia" is needed for. Is there a way to skip that?

I'm experimenting with migrating the Linux Kernel Documentation to using Sphinx, and trying to ensure the build stays compatible with readthedocs. If there's no way to bypass the readthedocssinglehtmllocalmedia build, I'd appreciate more resources, if only during this experimenting and evaluation.

**Comment by timgraham** [comment]
I also see this issue on some builds of [Django's docs](http://readthedocs.org/projects/django/builds/) which are fairly large.

**Comment by atodorov** [comment]
I'm also seeing this on my docs https://readthedocs.org/projects/mutation-testing-patterns/builds/. This started happening right after I switched to sphinx-rtd-theme. My docs collection isn't big, there are only a few files.

@timgraham, @jnikula guys I see your projects now build successfully. Did you change anything ?

**Comment by jnikula** [comment]
@atodorov As this was for testing only, I just cut down the number of documents to make it pass.

**Comment by timgraham** [comment]
I haven't changed anything for Django.

**Comment by humitos** [comment]
@jnikula the problem was that the building took more than 10 minutes and that it's the limit time for the celery task, so it gets killed. After you removing a couple of docs, it was built in less time so it passed. Check https://github.com/rtfd/readthedocs.org/issues/2591 for reference.

@atodorov I think your problem is because you are using an old version of Sphinx. Check this other issues: https://github.com/rtfd/readthedocs.org/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20traverse%20 that propose a solution by upgrading the Sphinx version.

I will close this issue as duplicated of #2591. Feel free to reopen if you consider.
