### ISSUE TITLE
Add ability to set "Domain has SSL" on a domain to force us to redirect to https

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs.org#2236]
Currently when you hit https://python-hyper.org/projects/hpack/ the redirect points at http. We assume all domains are HTTP only, because we don't do SSL internally. At least add metadata to the Domain that so we can properly redirect to https.

**Comment by nijel** [comment]
This would be really great to have this configurable, at least until https://github.com/rtfd/readthedocs.org/issues/2652 is implemented.

**Comment by humitos** [comment]
Just want to mention before #4483 gets merged and deployed, than hitting https://python-hyper.org/hpack/en/latest/ I'm not redirected to HTTP only. I'm not sure if we have changed something since Jun...

cc @davidfischer

**Comment by davidfischer** [comment]
This domain appears to have a different setup. It is not setup with the normal [Read the Docs custom domain instructions](https://docs.readthedocs.io/en/latest/alternate_domains.html#cname-support). This domain is using a naked domain (an A record, not a CNAME) and is probably doing their own proxying to Read the Docs.

I believe that this issue is more about generating "http" links (as opposed to "https" links).

**Comment by davidfischer** [comment]
> I believe that this issue is more about generating "http" links (as opposed to "https" links).

Actually I think I read this one wrong. You are right @humitos and this issue doesn't seem to be an issue anymore in terms of redirects.
