### ISSUE TITLE
Is it possible to get read the docs to run a custom python script as part of the build?

### ISSUE THREAD

**Issue by TimKam** [rtfd/readthedocs.org#2276]
Specifically, I'd like to run a script that:
* Builds the txt files of my Sphinx project.
* Processes the these txt files further.
* Replaces the content in the  `html/_sources` directory with these files. 

I have this script in place locally, but don't know if and how I can get it executed by the read the docs sever as part of the build process.

**Comment by zxiiro** [comment]
It's a hack but you can add your scripts to the bottom of conf.py. I have some shell scripts that I run by inserting subprocess.call() into conf.py.

**Comment by agjohnson** [comment]
Sounds like you want to include your methods as a hook into one of the Sphinx events. Use a `setup` function in your `conf.py` to interact with the state around the Sphinx application:

```python
def setup(app):
    ...
```

**Comment by TimKam** [comment]
Thank you very much @zxiiro , @agjohnson .
In case somebody else will have the same question: [here is a link to the section in the Sphinx documentation](http://www.sphinx-doc.org/en/stable/extdev/appapi.html#sphinx-core-events) that lists the core events you can tap into.

**Comment by willingc** [comment]
@TimKam Thanks for the link. Are you ready to close this issue?

**Comment by bradjc** [comment]
Is this possible when using Mkdocs?

**Comment by wvxvw** [comment]
All of these are really bad solutions...

I have a `setup.py apidoc` command that does what the name suggests, i.e. it calls the `sphinx.ext.apidoc.main` to generate RST files, which then should be processed by `setup.py build_sphinx`.

While `.readthedocs.yaml` tried to automate few things, it made basic and already existing automation impossible... why?

Configuration *is not* the place to run scripts. But, a command to generate documentation is. Why do it backwards?

Please make it possible to do it right instead of adding another layer of duct tape around the problem.

**Comment by astrojuanlu** [comment]
Hi @wvxvw , thanks for your interest on Read the Docs! For `apidoc` in particular, I think this extension does exactly what you need https://github.com/sphinx-contrib/apidoc without having to add a custom command. Let us know in #8133 if it works.
