### ISSUE TITLE
Build stack on Triggered state

### ISSUE THREAD

**Issue by NikitaEgorov** [rtfd/readthedocs.org#2401]
## Details
- Project URL: Local RTD Instance

I try to start local instance RTD
All builds stack on Triggered

**Comment by humitos** [comment]
This issue is being marked as `Community Effort`. The core team will try to facilitate resolution with this issue, but without the resources to support external installations outside of our production environment, we must rely on the community to help.

You can read more information on our philosophy around supporting Read the Docs as an open source and volunteer run effort here: http://docs.readthedocs.io/en/latest/open-source-philosophy.html

Besides that, you also can use Stack Overflow for this problem and receive more help from the community.
