### ISSUE TITLE
Build has been running for hours

### ISSUE THREAD

**Issue by xoorath** [rtfd/readthedocs.org#2407]
## Details
- Project URL: https://readthedocs.org/projects/xo-math
- Build URL (if applicable): https://readthedocs.org/projects/xo-math/builds/4392009/
- Read the Docs username (if applicable): xoorath
## Expected Result

Build to finish or time out.
## Actual Result

Build still installing, 14 hours later. Of course this isn't a problem for me, but thought you ought to know.

**Comment by satra** [comment]
- Project URL: https://readthedocs.org/projects/nipype
- Build URL (if applicable): https://readthedocs.org/projects/nipype/builds/4463006/
- Read the Docs username (if applicable): satra

there are several which say building (https://readthedocs.org/projects/nipype/builds) - it would be nice if they time out automatically or gave the user an option to cancel. clicking on the build returns a spinning wheel.

**Comment by humitos** [comment]
I marked this one as `Enhancement` since we need a better way to handle a Building that wasn't success for whatever reason and mark them as `Failed` instead of showing the spinning forever (which actually there is nothing running there).

I don't see this as a really Bug or that we need to do something else to help the users to build their docs but inform that the build has failed and showing the last command output instead.

**Comment by ericholscher** [comment]
This is a bug that we have, when a process gets killed uncleanly, the build state never gets re-updated. It is a known issue, so I'm going to close this specific issue, and hopefully we'll fix it soon.

**Comment by xoorath** [comment]
@ericholscher Could you link to the issue that tracks this problem?

**Comment by ericholscher** [comment]
#2471
