### ISSUE TITLE
Crate Project Disabled

### ISSUE THREAD

**Issue by Autophagy** [rtfd/readthedocs.org#2408]
Hi! The Crate project (https://readthedocs.org/projects/crate/) was disabled for excessive resource usage. We're sorry - we are unsure what was causing this to happen. Would it be possible to re-enable the project and inform of us why this occurred?

Thank you!

**Comment by ericholscher** [comment]
It was actually disabled because it was being hosted on our
infrastructure while removing all mention of Read the Docs and
stripping our branding. I'm happy to turn it back on if you all give
proper attribution to us for hosting it. Also in general we ask that
people who are running companies migrate to our paid hosted
service. I'm happy to help you migrate over when it makes sense.

**Comment by therealpadams** [comment]
Gold Membership now opted for all of our projects. Sorry for the trouble, @ericholscher!

**Comment by ericholscher** [comment]
:+1: -- should be working again. Thanks!
