### ISSUE TITLE
Building docs seems to fail randomly

### ISSUE THREAD

**Issue by uweschmitt** [rtfd/readthedocs.org#2425]
## Details
- Project URL: http://datapool.readthedocs.org
- Build URLs (if applicable): https://readthedocs.org/projects/datapool/builds/4443902/ and https://readthedocs.org/projects/datapool/builds/4443941/
- Read the Docs username (if applicable):  `uweschmitt`
## Expected Result

Without changing any setup related files the build randomly fails. I see the following output from the first step which is either:

(build 4443941 which succeeds):

```
python3 -mvirtualenv --no-site-packages --no-download /home/docs/checkouts/readthedocs.org/user_builds/datapool/envs/latest
Using base prefix '/usr'
New python executable in /home/docs/checkouts/readthedocs.org/user_builds/datapool/envs/latest/bin/python3
Not overwriting existing python script /home/docs/checkouts/readthedocs.org/user_builds/datapool/envs/latest/bin/python (you must use /home/docs/checkouts/readthedocs.org/user_builds/datapool/envs/latest/bin/python3)
Installing setuptools, pip, wheel...done.

```

or from the failing build 4443902

```
python3 -mvirtualenv --no-site-packages --no-download /home/docs/checkouts/readthedocs.org/user_builds/datapool/envs/latest
Using base prefix '/usr'
New python executable in /home/docs/checkouts/readthedocs.org/user_builds/datapool/envs/latest/bin/python3
Also creating executable in /home/docs/checkouts/readthedocs.org/user_builds/datapool/envs/latest/bin/python
Installing setuptools, pip, wheel...done.
```

The main difference is **Not overwriting existing python script** versus **Also creating executable in**. Which leads to a total different behaviour in the following steps.

**Comment by humitos** [comment]
`pyzmq` seems to be something that should be mocked since it's a C library dependency. Take a look at this error in this build https://readthedocs.org/projects/datapool/builds/4443902/

`build/temp.linux-x86_64-3.4/scratch/vers.c:4:17: fatal error: zmq.h: No such file or directory`

Here is an explanation about how to solve it: http://docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

On the other hand, in this build https://readthedocs.org/projects/datapool/builds/4443941/ `pyzmq` was compiled without no problem (I don't know why really) and that's why your build has passed. So, the _randomly_ situation is that in one of the build there was a missing C library dependency and in the following build it was there. Now, we need to know _why_ that happened?

Anyway, the correct way of building your docs is by mocking the C libraries.

Finally, it seems that your last builds are working properly. @uweschmitt  are you still having this problem?

**Comment by humitos** [comment]
I found that there is also a `docs/requirements.txt` that doesn't include that `pyzmq` and build the documentation on my local development instance correctly by using it and with `python3.5`

**Comment by uweschmitt** [comment]
Thanks for answering ! Currently I can live with the situation that the build fails from time to time and that I have to wait or retrigger a build. First I'll fix the `docs/requirements.txt` and see what happens. I leave it up to you to close this issue and/or to dig deeper into the cause of this random behaviour.

**Comment by humitos** [comment]
I'm marking this as `Needed: more information` to see if we can get some servers log or get a clue regarding the C library missing and then appeared.

**Comment by uweschmitt** [comment]
What makes me curios is the "Not overwriting existing python script" vs "Also creating executable" in the outputs I pasted above. This happens before `zmq` is required...

**Comment by agjohnson** [comment]
Builds look more stable now on this project, and we haven't collected any build information. Closing this but feel free to reopen if there is anything we should look at.
