### ISSUE TITLE
Build #4342378 stuck in Building state

### ISSUE THREAD

**Issue by mitya57** [rtfd/readthedocs.org#2468]
## Details
- Project URL: https://readthedocs.org/projects/secretstorage/
- Build URL (if applicable): https://readthedocs.org/projects/secretstorage/builds/4342378/
- Read the Docs username (if applicable): mitya57
## Expected Result

The build either completes, or fails, or times out.
## Actual Result

The build is stuck in _Building_ state for more than a month. All other builds went fine.

**Comment by afabiani** [comment]
Have a similar issue here

https://readthedocs.org/projects/geonode/builds/4537979/

the "latest" branch works while the "master" one stucks on "cat conf.py"

**Comment by conor10** [comment]
All of my builds are stuck on "cat conf.py", doesn't make a difference for me whether I build latest or master, see #2476

**Comment by markcmiller86** [comment]
I am running into this *constantly*. My doc tree builds fine running Sphynx directly on another linux platform and I get literally *no* feedback what is going on in RTD. I am finding it very unusuable.

**Comment by conor10** [comment]
Yes it's a shame, it's great when it's working. I'm manually building & deploying my docs to GitHub Pages to work around the issue. RTD was always getting stuck at exactly the same point in my build.

``
cat conf.py
``

Although looks as though my build history console output is now missing too, so I can no longer see what causing the build failures :(

**Comment by gtalarico** [comment]
Same issues.
Worked fine every time, then after last build it keeps getting stuck on 
``cat conf.py``

/revitpythonwrapper
Build #4641434
latest (adf3db113c0feaddc4fa2279d36fe090f8d5dbba)

![image](https://cloud.githubusercontent.com/assets/9513968/20153110/330fcaa2-a68f-11e6-84a2-c2e6a016a1bd.png)

**Comment by gtalarico** [comment]
following up made a trivial change to project settings, and it got rebuilt successfully.
previous build still stuck:

![image](https://cloud.githubusercontent.com/assets/9513968/20153497/f0a120ce-a690-11e6-8eba-d6d1c56bff8c.png)

**Comment by conor10** [comment]
I've tried modifying all sorts of different build settings, still hasn't made a difference for me unfortunately.

**Comment by fulopattila122** [comment]
@gtalarico and what was that magic _trivial change_? :)

**Comment by humitos** [comment]
@mitya57 one of the problem I see here is your `conf.py` makes the server goes into a:

`RecursionError: maximum recursion depth exceeded`

because you are returning the same `Mock()` class instead of `MagicMock()` at this line: https://github.com/mitya57/secretstorage/blob/master/docs/conf.py#L79

After changing that in my local clone of your repository, I was able to build it without any problem.

Can other people having this issue confirm that you are not running into the same problem?

**Comment by mitya57** [comment]
@humitos 
> because you are returning the same `Mock()` class instead of `MagicMock()`

Oh, that was because that was documented in the FAQ before #2530 was merged. I have updated it now. If you kill the outstanding running build, I think we can mark the issue resolved.

**Comment by humitos** [comment]
@mitya57 there is no way to kill a building (see #2471) but that is not a problem for this since it's just a UX issue. I mean, the building process doesn't exist anymore in the server, there is nothing running but the thing is it is not communicated properly to the Front End. I saw an issue for that, but I'm not finding it right now.

Thank you. I'm closing this issue.

Feel free to re-open if any of you still have the problem.
