### ISSUE TITLE
Support elastic search 2.x+

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2539]
Elastic search 2.x is not supported currently, because of conflicting mappings:

```Conflicting field mappings: Mapping for field page:id conflicts with: project:id. Check parameters: index, type```

This should be resolved to support 2.x upgrades

**Comment by humitos** [comment]
@agjohnson can you give more details on this?

Today, the latest version of elasticsearch is 5.4.0 (https://www.elastic.co/downloads/elasticsearch) and it's the same version for python wrapper (https://pypi.python.org/pypi/elasticsearch/5.4.0).

I tried upgrading both and I found minor incompatibilities in the python code. I changed this

    from elasticsearch.helpers import bulk_index

for

    from elasticsearch.helpers import bulk

but there are problems regarding the API since it's incompatible and needs to be updated. In particular the `body` creation at https://github.com/humitos/readthedocs.org/blob/a0a29e8bbb454d9296b91492d31ecbee396fe1fa/readthedocs/search/lib.py#L17-L39 and the parsing response at https://github.com/humitos/readthedocs.org/blob/a0a29e8bbb454d9296b91492d31ecbee396fe1fa/readthedocs/search/views.py#L47-L58

**Comment by humitos** [comment]
On the other hand, I think that we are not using `pyelasticsearch` at all from https://github.com/humitos/readthedocs.org/blob/a0a29e8bbb454d9296b91492d31ecbee396fe1fa/requirements/pip.txt#L40

**Comment by humitos** [comment]
Closing this one in favor of #3373
