### ISSUE TITLE
Sidebar does not show TOC on RTD, but shows when built locally with RTD theme

### ISSUE THREAD

**Issue by vsajip** [rtfd/readthedocs.org#2555]
## Details

* Project URL: https://bitbucket.org/vinay.sajip/python-gnupg
* Build URL (if applicable): http://gnupg.readthedocs.io/en/latest/
* Read the Docs username (if applicable): vsajip

## Expected Result

The TOC should be shown in the sidebar.

![Correct appearance](http://i.imgur.com/wQayAUL.png)

## Actual Result

The TOC is not shown in the sidebar.

![Incorrect appearance](http://i.imgur.com/eNMO99K.png)

**Comment by cdeil** [comment]
The Astropy project might be having the same issue.
Details here: https://github.com/astropy/astropy/issues/5679

Since a few days (not sure exactly when), our sidebar no longer appears on RTD.
Locally it's there and there hasn't been a change on our side.

We've wiped and re-built, and the build log doesn't show anything suspicious as far as I can tell:
https://readthedocs.org/projects/astropy/builds/4872087/

Can someone from RTD please have a look, and maybe give a tip how we might be able to debug this?

**Comment by cdeil** [comment]
Here's a screenshot showing how the sidebar is currently completely missing:

<img width="463" alt="screen shot 2017-01-08 at 18 02 37" src="https://cloud.githubusercontent.com/assets/852409/21751767/ba3b020a-d5cc-11e6-9743-5dfcf2feb0d0.png">

As mentioned at https://github.com/astropy/astropy/issues/5679#issuecomment-271162389 , actually the `<div class="sphinxsidebar">` is missing in the HTML!???

**Comment by humitos** [comment]
@vsajip I just re-triggered your docs and they are building properly. I see the sidebar there http://gnupg.readthedocs.io/en/latest/

@cdeil I can also see the sidebar at http://docs.astropy.org/en/latest/ and http://docs.astropy.org/en/stable/

I don't know what happened in your previous builds :)

**Comment by vsajip** [comment]
Thanks. Will close the issue now. May reopen if it happens again. A bit worrying that no cause was identified. 😞
