### ISSUE TITLE
GitHub webhook creation fails when there is an existing webhook

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2561]
GitHub used to return a 201 response on a duplicate webhook, but now returns a `422` response. Existing logic expects GitHub to handle overwrite, but we need to handle this on our end instead.

Error response on failure:

```
{
  "message": "Validation Failed",
  "errors": [{
    "resource": "Hook",
    "code": "custom",
    "message": "Hook already exists on this repository"
  }],
  "documentation_url": "https://developer.github.com/v3/repos/hooks/#create-a-hook"
}
```

**Comment by stsewd** [comment]
From the documentation

> Creating hooks for a service that already has one configured will update the existing hook

https://developer.github.com/v3/repos/hooks/#create-a-hook

When does this happens anyway? I think the webhooks are only created on import time.

**Comment by humitos** [comment]
This happen at

https://github.com/rtfd/readthedocs.org/blob/b12e1885dc7f6da6b9719054e3654019b1e0fe65/readthedocs/oauth/services/github.py#L182-L273

I think is issue is old and github doesn't behaves as it mentioned in the description. @stsewd  Would you like to do a quick test by hitting the webhook endpoint and writting a test case for this?

**Comment by stsewd** [comment]
@humitos what I mean was when the _second_ call to create a webhook happens, I will test the webhook creation manually.

**Comment by stsewd** [comment]
So, I tested manually and indeed GitHub returns a error code 422 when there is already a webhook, but there is no use case right now that generate this.

Because, the webhooks are only created when a user import a new project, there is an option for resync a webhook (this works fine), and an option fro create a new webhook, but this option just gives an link to manually configurate the webhook on GitHub, so I don't know if is worth to check for this case.

@humitos I don't know how to write a test for this, since it needs to hit the GitHub API.

**Comment by humitos** [comment]
@agjohnson how did you get that error? what was the workflow/steps?

> Because, the webhooks are only created when a user import a new project

What happen if you import the project, delete it and import it again? I suppose that could be the use case since I don't think RTD is removing the webhook from the repository (which I think we _should_ do, right?)

> @humitos I don't know how to write a test for this, since it needs to hit the GitHub API.

We use mocks for this (https://docs.python.org/3/library/unittest.mock.html) so we can emulate a response from github as it would be real but it's a fake instead. Example at https://github.com/rtfd/readthedocs.org/blob/a9d98a2856e378988a42a40e054b2ca7cbba3b3a/readthedocs/rtd_tests/tests/test_oauth.py#L399-L404

**Comment by stsewd** [comment]
> What happen if you import the project, delete it and import it again?

@humitos it creates another webhook, and the old one still remains on the repo

**Comment by humitos** [comment]
We are now updating the webhook properly if we have it in our database. Also, if the webhook is in our database and does not exist in the service, when we try to update it we get a 404 and we re-create it. This is done in #3931.

I'm closing this one.
