### ISSUE TITLE
Pillow dependency in conda build fails to install because of dependency conflict.

### ISSUE THREAD

**Issue by cpaulik** [rtfd/readthedocs.org#2594]
I might have a similar problem to https://github.com/rtfd/readthedocs.org/issues/2566 since the strict dependency on pillow==3.0.0 breaks the build. My local version of conda asks to downgrade the jpeg library but that is probably because I have `conda-forge` in my default channels.

## Details

* Project URL: https://readthedocs.org/projects/ascat
* Build URL (if applicable): https://readthedocs.org/projects/ascat/builds/4908635/

## Expected Result

Build should succeed since it works locally without pillow.

## Actual Result

Conda fails to install with a dependency conflict

**Comment by humitos** [comment]
Yeah, this is a known issue and we are trying to get to the final solution. In the issue that you linked, we are considering not pinning packages in conda environment at all since conda users have more experience** (I suppose) and could solve installation issues by themselves (installing the default dependencies like sphinx, the RTD theme and so) and also going in that direction will avoid all of this kind of incompatibility problems that some users are reporting.

(**) the pip environment is using pinned versions since RTD allows to build the documentation just by having a `docs` folder with a bunch of `.rst` files and knowing nothing about virtual env, sphinx or so.

I'm closing this one since it's a duplicated of #2566.

I suggest you to give your opinion in the linked issue regarding "why you consider is a good idea to not pin versions in conda environments" so we start collecting users ideas and we can reach a final decision on this. Thanks!
