### ISSUE TITLE
Build fails on read the doc #support

### ISSUE THREAD

**Issue by henrykironde** [rtfd/readthedocs.org#2668]
I am trying to build this project docs https://github.com/henrykironde/retriever/tree/docsfail.
Locally builds pass, however on readthedocs service, the build fails

I have tried to set up the path but I think there is something missing. 

```
python3.5 -mvirtualenv --system-site-packages --no-download /home/docs/checkouts/readthedocs.org/user_builds/deletedret/envs/latest
python /home/docs/checkouts/readthedocs.org/user_builds/deletedret/envs/latest/bin/pip install --use-wheel -U --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/deletedret/.cache/pip -I sphinx==1.3.5 Pygments==2.1.3 setuptools==20.1.1 docutils==0.12 mkdocs==0.15.0 mock==1.0.1 pillow==2.6.1 git+https://github.com/rtfd/readthedocs-sphinx-ext.git@0.6-alpha#egg=readthedocs-sphinx-ext sphinx-rtd-theme==0.1.9 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.1.1
python /home/docs/checkouts/readthedocs.org/user_builds/deletedret/envs/latest/bin/pip install --exists-action=w --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/deletedret/.cache/pip -r/home/docs/checkouts/readthedocs.org/user_builds/deletedret/checkouts/latest/requirements.txt
python setup.py install --force
cat conf.py

python /home/docs/checkouts/readthedocs.org/user_builds/deletedret/envs/latest/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html

```

**Comment by humitos** [comment]
@henrykironde what's your project in RTD? what's the build that it's failing? what's the error?

**Comment by henrykironde** [comment]
project is retriever
https://readthedocs.org/projects/retriever/
builds https://readthedocs.org/projects/retriever/builds/

**Comment by humitos** [comment]
I think it's because It reaches the timeout `Build took 598 seconds `, which is 10 minutes. More information in #2591 

I'm closing this one as duplicated.

**Comment by humitos** [comment]
I found something else here, the build is failing because of the timeout but that is not the main reason I think. I tried this in my own RTD local instance and I notice that this command takes 100% CPU

    /bin/sh -c cd /home/humitos/readthedocs/readthedocs.org/user_builds/retriever/checkouts/latest/docs && PATH=/home/humitos/readthedocs/readthedocs.org/user_builds/retriever/envs/latest/bin:$PATH python /home/humitos/readthedocs/readthedocs.org/user_builds/retriever/envs/latest/bin/sphinx-build -T -b json -d _build/doctrees-json -D language=en . _build/json

I saw that you are doing some _extra_ things in the `docs/conf.py` and that seems to be the problem. You are downloading a bunch of files (`scripts`, `.csv`, `.xls` and more). You can check the whole output from my own computer at http://pastebin.com/HGGvHcU4 maybe it helps you to fix your issue.

Besides, I noticed this message in the build tab:

    stty: 'standard input': Inappropriate ioctl for device

Not sure if it has something to do, but leaving it here for reference, just in case.

So, increasing the timeout is not an option here, I think.

**Comment by humitos** [comment]
`check_for_updates`: https://github.com/weecology/retriever/blob/master/lib/repository.py#L30
