### ISSUE TITLE
Undefined mysqli_connect 

### ISSUE THREAD

**Issue by Yellobounty** [rtfd/readthedocs.org#2696]
## Details
Hello i host a project and is working fine, all of a sudden, it started showing undefined mysqli_connect error, what can causes that
* Project URL: 
* Build URL (if applicable):
* Read the Docs username (if applicable): 

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

**Comment by humitos** [comment]
@Yellobounty can you provide more information about your project (url, username, etc)?

Although, I think it's a problem that you can fix with http://docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

(I'm guessing, because the report needs more information)

**Comment by humitos** [comment]
Closing. Stale issue.
