### ISSUE TITLE
Build Caught in forever loop: Triggered for 5+ days

### ISSUE THREAD

**Issue by rtmclay** [rtfd/readthedocs.org#2748]
## Details

* Project URL: lmod.readthedocs.io
* Build URL (if applicable):5185142 and 5184979
* Read the Docs username (if applicable):   rtmclay

## Expected Result

Build the documentation.

## Actual Result

Build # 5185142 (and 5184979) Just say:  Triggered and nothing else.  They have been in that state for over 5 days.  I am at a loss as to why it should say "Triggered" with no other response or output.   This project has been build 95 times.  Also I have no problem building the documentation locally.

I don't see a away to kill the build or get any other information.  Thanks for your help.

Robert.

**Comment by sjezewski** [comment]
I'm having a similar issue.

- Build # 5208033
- Build URL: https://readthedocs.org/projects/pachyderm/builds/5208033/
- Project URL: docs.pachyderm.io

I've triggered a build since that succeeded just fine. After waiting ~30m I clicked the 'wipe' button hoping that would do something, but an hour later, it has not.

It would be helpful to be able to kill / restart a build.

**Comment by humitos** [comment]
Duplicated of #2471
