### ISSUE TITLE
pydbus dependency fails to install

### ISSUE THREAD

**Issue by martinohanlon** [rtfd/readthedocs.org#2761]
I am trying to build docs for a new project which has a requirement for pydbus [https://github.com/LEW21/pydbus/](https://github.com/LEW21/pydbus/) the pip install works independently but when run as part of the readthedocs build it fails with an error relating to pydbus not being available.

* Project URL: https://readthedocs.org/projects/bluedot/
* Build URL (if applicable): http://bluedot.readthedocs.io/en/latest/
* Read the Docs username (if applicable): martinohanlon

## Expected Result

I was expecting the pydbus module to be installed successfully and the build to be success.

I am not sure if pydbus is a C module and i did try changing the settings so that it uses global site packages but the result is the same.

## Actual Result

https://readthedocs.org/projects/bluedot/builds/5216095/

The error reported is:

`The 'pydbus' distribution was not found and is required by the application`

However I find this confusing because the log states:

```
Processing dependencies for bluedot==0.0.2
Searching for pydbus
Reading https://pypi.python.org/simple/pydbus/
Downloading https://pypi.python.org/packages/58/56/3e84f2c1f2e39b9ea132460183f123af41e3b9c8befe222a35636baa6a5a/pydbus-0.6.0.tar.gz#md5=c6abd44862322679bd4e907bebc3e0d0
Best match: pydbus 0.6.0
Processing pydbus-0.6.0.tar.gz
Writing /tmp/easy_install-_50bhj64/pydbus-0.6.0/setup.cfg
Running pydbus-0.6.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-_50bhj64/pydbus-0.6.0/egg-dist-tmp-wn0qd1qf
```

But at this point an error is reported.

Does anyone have any ideas, thoughts, suggestions?

**Comment by martinohanlon** [comment]
Ok, so I removed pydbus from install_requires in setup.py and the build was successful.

So presumably dbus packages are already installed?

**Comment by humitos** [comment]
Is `pydbus` required to build the documentation? I don't think so. That's why when you removed it RTD worked.

But, if `pydbus` is required for your program to work, you shouldn't remove it from your `setup.py`. Instead, you should provide a specific `requirements.txt` for RTD to use when building the documentation. You can set this in the admin interface of your project and you will also need to remove the installation of your own project in RTD (there is a checkbox for that).

I'm closing this issue. Please, feel free to reopen if you consider.
