### ISSUE TITLE
requirement gmpy errors

### ISSUE THREAD

**Issue by CromefireHD** [rtfd/readthedocs.org#2771]
## Details

* Project URL: https://readthedocs.org/projects/pcunlocker/
* Build URL: https://readthedocs.org/projects/pcunlocker/builds/5236884/
* Read the Docs username: CromefireHD

## Expected Result
It should install it without error

## Actual Result
it errors and stops building

## Tries to fix
``` python
class Mock(MagicMock):
    @classmethod
    def __getattr__(self, item):
        return MagicMock()

MOCK_MODULES = ["gi", "gi.repository", "gmpy"]
sys.modules.update((mod_name, Mock()) for mod_name in MOCK_MODULES)
```
does not work

**Comment by humitos** [comment]
Hello! Is your issue fixed? I see that your last build successes.

On the other hand, `gmpy` requires C libraries so you should remove it from your `requirements.txt` and mock it (if you need it for building the docs) as you pointed in the description of this issue.

RTD fails when trying to install it via pip because it doesn't have the required libraries.

Another solution could be using a `conda` env.

I'm closing this issue since I don't see a RTD specific error. Please, feel free to re open it if you consider. Thanks!

**Comment by CromefireHD** [comment]
The last build succeeded because I removed the dependency on py-seccure temporarily and that is the problem, because I don't have the dependency, but py-seccure has so mocking out didn't work
