### ISSUE TITLE
News Feed Drop Down by Month 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [rtfd/readthedocs.org#2788]
## Details
Hello,

I would like to create a news feed that has one entry in a table that can be sorted by time with most recent news displayed first. 

Also I would like to present news feed for current month and show all previous months hidden that can be viewed if the month has been clicked. Is there any way to do this in sphinx.

I couldn't seem to find anything close to this. 

* Project URL: 
* Build URL (if applicable):
* Read the Docs username (if applicable): 

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

**Comment by humitos** [comment]
This issue is being marked as `Community Effort`. The core team will try to facilitate resolution with this issue, but without the resources to support external installations outside of our production environment, we must rely on the community to help.

You can read more information on our philosophy around supporting Read the Docs as an open source and volunteer run effort here: http://docs.readthedocs.io/en/latest/open-source-philosophy.html

Besides that, you also can use Stack Overflow for this problem and receive more help from the community.

**Comment by humitos** [comment]
This issue is being marked as `Community Effort` since it's not specific to RTD but more related to Sphinx markup or plugins.

You can read more information on our philosophy around supporting Read the Docs as an open source and volunteer run effort here: http://docs.readthedocs.io/en/latest/open-source-philosophy.html

Besides that, you also can use Stack Overflow for this problem and receive more help from the community.
