### ISSUE TITLE
Update translation docs

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2847]
We do a bad job of explaining how to contribute documentation for readthedocs docs and UI.

**Comment by mukul09** [comment]
I want to work on this issue, as far as I got your point is that the contribute documentation should be in other languages also. right?

**Comment by stsewd** [comment]
@mukul09 this issue is about improving the steps for contributing to translations (but also looks like about contributing to documentation and design).

Here are a links about the current docs:
- https://docs.readthedocs.io/en/latest/i18n.html?highlight=translations#administrative-tasks
- https://docs.readthedocs.io/en/latest/contribute.html#helping-on-translations (here there is just a link!)

Note: I think the steps about contributing to documentation are covered on #3498.

**Comment by agjohnson** [comment]
@humitos added a guide on managing translations. That was the piece i was looking to start with here. Closing this issue.
