### ISSUE TITLE
.readthedocs.yml from a submodule is affecting the configuration

### ISSUE THREAD

**Issue by bmerry** [rtfd/readthedocs.org#2855]
## Details

* Project URL: http://spead2.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/spead2/builds/5444021/
* Read the Docs username (if applicable): bmerry-ska

## Expected Result

The build should succeed, as it does for an [old version](https://readthedocs.org/projects/spead2/builds/5444007/), installing requirements from `requirements-readthedocs.txt` as configured in the control panel.

## Actual Result

The build fails with the message
```
Could not open requirements file: [Errno 2] No such file or directory: 'docs/requirements.txt'
```
It is reading the settings from `3rdparty/pybind11/.readthedocs.yml`. It should only look for a `.readthedocs.yml` at the root, as [documented](http://docs.readthedocs.io/en/latest/yaml-config.html).

**Comment by bmerry** [comment]
I don't know if it's related, but part of update was adding a git submodule. It shouldn't be required for building the docs though.

**Comment by bmerry** [comment]
I figured out the problem: the submodule has a `.readthedocs.yml` file, which was overriding the control panel settings. Since the [documentation](http://docs.readthedocs.io/en/latest/yaml-config.html) says that the yml file must be the in root of the repository of the project, I think it is a bug that it is picking up one from the submodule. I'll change the bug title to reflect this.

**Comment by bmerry** [comment]
The good news is putting my own `.readthedocs.yml` in the root (with the appropriate settings) fixes the build.

**Comment by humitos** [comment]
Marking this as a bug since the code does a `find_all`, which looks in the whole project structure recursively instead of just take a look at the root as the documentation says:

1. https://github.com/rtfd/readthedocs.org/blob/416ab4018b6ea82a24c1250e7f6053e72e7f57a8/readthedocs/doc_builder/config.py#L152-L155
2. https://github.com/rtfd/readthedocs-build/blob/864892c17c370c72865c3717c18370368e3e0635/readthedocs_build/config/config.py#L362
3. https://github.com/rtfd/readthedocs-build/blob/864892c17c370c72865c3717c18370368e3e0635/readthedocs_build/config/find.py#L4-L10

**Comment by ericholscher** [comment]
Believe this should be fixed with our deploy a while back. We only use one rtd.yml file now.
