### ISSUE TITLE
Self-hosted readthedocs w/LDAP auth

### ISSUE THREAD

**Issue by jsmartin** [rtfd/readthedocs.org#2856]
## Details

* N/A
* N/A
* N/A
## Expected Result

I want my local install of readthedocs to use a local LDAP server for authentication and authorization 

## Actual Result

I cannot find documentation on where to configure this.

**Comment by humitos** [comment]
This issue is being marked as `Community Effort`. The core team will try to facilitate resolution with this issue, but without the resources to support external installations outside of our production environment, we must rely on the community to help.

You can read more information on our philosophy around supporting Read the Docs as an open source and volunteer run effort here: http://docs.readthedocs.io/en/latest/open-source-philosophy.html

Besides that, you also can use Stack Overflow for this problem and receive more help from the community.
