### ISSUE TITLE
Automatically add "Edit on GitLab" links to documentation pages for repositories hosted on GitLab.com

### ISSUE THREAD

**Issue by mlncn** [rtfd/readthedocs.org#2910]
## Details

Just as "Edit on GitHub" and "Edit on BitBucket" links are automatic, so can "Edit on GitLab" links be.

## Workaround

The functionality is evidently already there (awesome!) as seen on [our project](http://docs.drutopia.org/en/latest/quickstart.html), it only took adding these lines to conf.py:

```
html_context = {
    "display_gitlab": True, # Integrate Gitlab
    "gitlab_user": "drutopia", # Organization or User
    "gitlab_repo": "documentation", # Repo name
    "gitlab_version": "master", # Version
    "conf_py_path": "/", # Path in the checkout to the docs root
}
```
The next step is to make this automatic.

**Comment by ItsPugle** [comment]
Hey, @mlncn,

I'll be adding the **Enhancement** and **Needed: design decision** labels to this ticket with the triage process. As you could imagine, ReadTheDocs receives an extraordinary amount of tickets and issues through GitHub every week, and because of the smaller team, your request may take on the upside of several days to be processed and reviewed by the team.

Thank you for your patience,
ItsPugle - ReadTheDocs Triage Team

**Comment by humitos** [comment]
@benjaminp Hi! This should be working after #3327 got merged and deployed.
