### ISSUE TITLE
"scroll-to-top"-button missing - probably feature request

### ISSUE THREAD

**Issue by kassbohm** [rtfd/readthedocs.org#2917]
## Details

* Project URL: http://docs.readthedocs.io/en/latest/theme.html

## Expected Result

wanted to find a a "scroll-to-top"-button when checking this URL on my phone. Couldn't find it...

**Comment by humitos** [comment]
@kassbohm hi, thanks for your report.

Could you give more details? Where you would add it to not interfere with the rest of the design for example? A simple `a` link is enough?

Probably a better place for this issue is https://github.com/rtfd/sphinx_rtd_theme

Would you like to make a Pull Request?

**Comment by kassbohm** [comment]
Hi thanks for replying.

sorry, actually I wanted to add this to  https://github.com/rtfd/sphinx_rtd_theme ... should we close this here and I ask at https://github.com/rtfd/sphinx_rtd_theme instead?

**Comment by humitos** [comment]
Sure. When you create the issue in the other repository please, paste the link here so they are connected. Thanks!

**Comment by kassbohm** [comment]
https://github.com/rtfd/sphinx_rtd_theme/issues/424

**Comment by kassbohm** [comment]
@humitos 
added two pics about what I mean https://github.com/rtfd/sphinx_rtd_theme/issues/424

any other questions?

**Comment by humitos** [comment]
Thanks!
