### ISSUE TITLE
Download raw build log / improve log interface

### ISSUE THREAD

**Issue by anntzer** [rtfd/readthedocs.org#2921]
The build log interface is a bit tricky to navigate.  For example, it probably makes sense to use a wider display for the log, and wrap overly long lines (as Travis does) instead of requiring the user to scroll them.
Even better may be an option to just get the raw log as a text file, which is easier to grep.

**Comment by edmorley** [comment]
This made debugging builds today harder than it would otherwise have been - the header row for each build step doesn't display enough characters to tell the steps apart.

For example this is what I can see for our builds:
1. `python2.7 -mvirtualenv --no-site-packages --no-download /home/docs/checkouts/readthedocs.org/user`
2. `python /home/docs/checkouts/readthedocs.org/user_builds/treeherder/envs/latest/bin/pip install --`
3. `python /home/docs/checkouts/readthedocs.org/user_builds/treeherder/envs/latest/bin/pip install --`
4. `cat docs/conf.py`
5. `python /home/docs/checkouts/readthedocs.org/user_builds/treeherder/envs/latest/bin/sphinx-build -`
6. `python /home/docs/checkouts/readthedocs.org/user_builds/treeherder/envs/latest/bin/sphinx-build -`
7. `python /home/docs/checkouts/readthedocs.org/user_builds/treeherder/envs/latest/bin/sphinx-build -`

The vast majority of those strings are indistinguishable unless I click and drag the text sideways (I can't even scroll, since there are no scrollbars).

**Comment by humitos** [comment]
I like the idea of a "full log" link that return a simple text file with all the commands and output
