### ISSUE TITLE
Cleanup on removed branches/tags

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2933]
We currently aren't cleaning up removed branches/tags when there are removed from the source repository. We might be able to piggyback on these removals to clean up old versions, but I do see some value in keeping these versions around for historical purposes.

We need to decide:

* Do we need to be opinionated about this?
* What does the removal workflow look like if we do support automatic removal on branch/tag removal?
* Should we instead only remove unbuilt versions?

**Comment by projectgus** [comment]
Hi folks, I'm the user who originally reported this to @agjohnson . Our situation is we accidentally pushed a tag to our master branch, and even though it's been deleted from the master branch it's persisting in readthedocs and inserting itself into the "git rev-parse" version string in the page title of the docs

(Our docs are https://espressif-esp-idf.readthedocs-hosted.com/en/latest/ for repo @ https://github.com/espressif/esp-idf/tags - note the audio-weekly tag does not exist but is in the page title!)

I see Anthony's point knowing how to do automatic removal may be complex, but we really need some kind of manual removal option at minimum - otherwise we're stuck with this misleading tag until we arbitrarily re-tag our repo with something or release a new version.

**Comment by ericholscher** [comment]
@agjohnson I believe the code should be deleting removed versions/tags. If not, there is a bug, but I've checked this a few times and it appears to work in at least some common cases.

**Comment by krzychb** [comment]
Adding to description by @projectgus -  Another (more visible) place where deleted tag shows up is PDF version of docs - https://readthedocs.com/projects/espressif-esp-idf/downloads/pdf/latest/

(A)
![image](https://user-images.githubusercontent.com/12953787/27023887-be37dffc-4f54-11e7-8f25-849219ebf2ca.png)

(B)
The same commit `e7db29b` on community  site https://media.readthedocs.org/pdf/esp-idf/latest/esp-idf.pdf looks as follows: 
![image](https://user-images.githubusercontent.com/12953787/27023957-1cb50104-4f55-11e7-859b-176c2a3cd96b.png)

(C) 
Below is corresponding  latest commit on GitHub
![image](https://user-images.githubusercontent.com/12953787/27024125-a4413fca-4f55-11e7-8c9a-c85cf982f157.png)

**Comment by krzychb** [comment]
Hi guys, could you provide an update on resolution status?

**Comment by stsewd** [comment]
I checked all the links, everything is ok now, @krzychb are you still having this issue?

**Comment by krzychb** [comment]
@stsewd, the latest docs in pdf look fine:
https://readthedocs.com/projects/espressif-esp-idf/downloads/pdf/latest/

**Comment by ericholscher** [comment]
Great!
