### ISSUE TITLE
Enable browser-side caching

### ISSUE THREAD

**Issue by CrazyPython** [rtfd/readthedocs.org#2956]
I'm not sure which repository to open this on, but according to [Google PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdocs.readthedocs.io%2Fen%2Flatest%2Fversions.html&tab=desktop), these resources are missing Cache-control headers:

https://docs.readthedocs.io/en/latest/_static/js/modernizr.min.js (expiration not specified)
https://docs.readthedocs.io/en/latest/_static/logo.svg (expiration not specified)
https://docs.readthedocs.io/en/latest/_static/readthedocs-data.js (expiration not specified)
https://docs.readthedocs.io/…t/_static/readthedocs-dynamic-include.js (expiration not specified)

Readthedocs is quite slow as of now, and this would help improve its performance.

**Comment by ItsPugle** [comment]
Hey, @,

I'll be adding the **Enhancement** and **Needed: design decision** label to this ticket with the triage process. As you could imagine, ReadTheDocs receives an extraordinary amount of tickets and issues through GitHub every week, and because of the smaller team, your request may take on the upside of several days to be processed and reviewed by the team.

Thank you for your patience,
ItsPugle - ReadTheDocs Triage Team

**Comment by markrwilliams** [comment]
Readthedocs should also allow caching of Intersphinx `objects.inv` files.  Even a short `max-age` of 10 to 15 minutes could help reduce the load imposed by busy CI servers.

I'd be happy to contribute this change.

**Comment by humitos** [comment]
Closing in favor of #2955
