### ISSUE TITLE
Package mkdocs not found in conda

### ISSUE THREAD

**Issue by astrofrog** [rtfd/readthedocs.org#2975]
## Details

* Project URL: https://readthedocs.org/projects/astropy/
* Build URL (if applicable): https://readthedocs.org/projects/astropy/builds/5613695/
* Read the Docs username (if applicable):

## Expected Result

The build should pass

## Actual Result

The second step failed with:

```
conda install --yes --name latest sphinx mock pillow sphinx_rtd_theme mkdocs
Fetching package metadata .........


PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels: 
  - mkdocs

You can search for packages on anaconda.org with

    anaconda search -t conda mkdocs

You may need to install the anaconda-client command line client with

    conda install anaconda-client
```

The last successful build was *Completed June 23, 2017. 8:48 a.m*

**Comment by willingc** [comment]
@agjohnson @ericholscher I'm noticing the same thing on Jupyter builds using conda.

**Comment by ericholscher** [comment]
OK. Any suggestions? As I always note, we don't have any core devs who use conda, so we need help diagnosing and fixing these issues.

**Comment by bsipocz** [comment]
Same is seen for https://readthedocs.org/projects/photutils/

**Comment by bsipocz** [comment]
@ericholscher - Would that be possible though that, based on the chosen documentation type, either only sphinx or mkdocs is installed? We use sphinx, and also test on travis whether the docs building is working. 

So overall it would be great if the same, or a very similar env we test for could be used on RTD itself.

**Comment by willingc** [comment]
@ericholscher I will try to take a look tomorrow.

**Comment by mwcraig** [comment]
Not sure what changed on the RTD side, but the problem is that mkdocs is not available on the standard conda channels, only on conda-forge.

So the line that failed should either be:

```
conda install -c conda-forge  --yes --name latest sphinx mock pillow sphinx_rtd_theme mkdocs
```

or

```
conda install --yes --name latest sphinx mock pillow sphinx_rtd_theme 
pip install mkdocs
```

On the package-author side you might be able to fix it immediately by adding a channel list to the top of your environment file and adding mkdocs to your list of depends.

**Comment by willingc** [comment]
As mentioned by @mwcraig (thanks!), adding `mkdocs` to the `environment.yml` and installing from the conda-forge channel does allow the docs to build as expected. For those that are not using mkdocs, which we are not with Jupyter, I needed to add the mkdocs package for installation to the dependencies in the `environment.yml`. See [example file](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/106/files).

**Comment by hans-permana** [comment]
thanks @mwcraig, I did add mkdocs as a dependency and the error is now gone.

**Comment by astrofrog** [comment]
I'm curious why this started breaking though - was there a specific change to RTD that was made around the date/time I indicated? RTD used not to install mkdocs?

**Comment by willingc** [comment]
@astrofrog I think the change made [here](https://github.com/rtfd/readthedocs.org/pull/2876) introduced mkdocs install from conda default channel. I have no idea why it surfaced recently.

**Comment by bsipocz** [comment]
Maybe there is a slight delay in deployment after merging a PR?

**Comment by agjohnson** [comment]
@bsipocz We did a deploy June 8th that should have had the linked change around conda dependencies. We did do a deploy the other day, I don't know what would have changed since then though.

I agree that we should probably be removing the unneeded mkdocs/sphinx dependencies from the pip/conda install step. If anyone wants to submit a patch for this, it should be relatively easy to change and test -- code is here: https://github.com/rtfd/readthedocs.org/blob/rel/readthedocs/doc_builder/python_environments.py#L213-L219 and there is also the vanilla pip install above, which would be good to replicate this logic in.

**Comment by ericholscher** [comment]
This fix should be deployed.

**Comment by willingc** [comment]
Confirming that #2978 resolved this issue. Longer term, #2979 is a better solution and more robust.

Successful build after #2978 merge: https://readthedocs.org/projects/jupyter-notebook/builds/5622632/

Thanks @ericholscher 👍

**Comment by ericholscher** [comment]
Thanks to @willingc & @bsipocz for the patchs!

**Comment by bsipocz** [comment]
I can confirm that the astropy build is passing again, too. Thanks!

I'll  try to finish up #2979 tomorrow.
