### ISSUE TITLE
Buggy search highlighting when searching certain code blocks

### ISSUE THREAD

**Issue by timabbott** [rtfd/readthedocs.org#2995]
## Details

* Project URL: https://zulip.readthedocs.io/en/latest
* Buggy URL: https://zulip.readthedocs.io/en/latest/search.html?q=%22email+mirror%22&check_keywords=yes&area=default#

## Actual Result

https://zulip.readthedocs.io/en/latest/search.html?q=%22email+mirror%22&check_keywords=yes&area=default# looks like this:
![image](https://user-images.githubusercontent.com/2746074/27981977-b02ee3d2-634b-11e7-9760-02a940006b20.png)

It seems clear that something is wrong with the rendering of the search results.

https://github.com/zulip/zulip/blob/master/docs/prod-troubleshooting.md is the source code.

## Expected Result

Searching for "email mirror" should provide reasonable context around the reference in http://zulip.readthedocs.io/en/latest/prod-troubleshooting.html
Some context is available in https://github.com/zulip/zulip/issues/5722

**Comment by ItsPugle** [comment]
Hey, @timabbott,

I'll be adding the **Bug** label to this ticket with the triage process. As you could imagine, ReadTheDocs receives an extraordinary amount of tickets and issues through GitHub every week, and because of the smaller team, your request may take on the upside of several days to be processed and reviewed by the team.

Thank you for your patience,
ItsPugle - ReadTheDocs Triage Team

**Comment by stsewd** [comment]
This looks like it is fixed by now

![screenshot-2017-12-26 search zulip 1 7 1 git documentation](https://user-images.githubusercontent.com/4975310/34370532-c3e89d90-ea92-11e7-9c29-22f69fdd84d5.png)

**Comment by RichardLitt** [comment]
@timabbott Are you still able to replicate this bug?

**Comment by timabbott** [comment]
Yeah, seems to have been fixed.
