### ISSUE TITLE
Cannot write to metadata.json

### ISSUE THREAD

**Issue by Geoglinexos** [rtfd/readthedocs.org#3004]
## Issue

First I'm running a local instance of ReadTheDoc in a **LXC container** with Centos 7.3. 

I have created a virtualenv with RTD inside (python 2.7). The installation seems correct because I can access to the web URL and configure my project but when I tried to build my docs absolutly nothing happens. 

In the debug.log : 
![image](https://user-images.githubusercontent.com/30039459/28267596-031fed28-6afb-11e7-806f-d33515bc5f04.png)

and when I search though the Django's API on the buil section :  
![image](https://user-images.githubusercontent.com/30039459/28263918-05219020-6ae9-11e7-9d9f-0c8039fe26fc.png)

No commands have been launched. 

## URL
You shoud able to see my doc at this url because I have manually created a **user_build** repo in **/checkouts** and copied my doc from my **Test VM** (wich was also a Centos 7.3) : 
* Project URL: http://calise.linexos.fr/docs/calise/fr/latest/

## Details
In my **Test VM** I don't have any issues. I reproduced the same installation on the **LXC container**.

Maybe I have a issue with certains libs from python.

**Comment by Geoglinexos** [comment]
I have the solve the issue by adding the user **test** with : 
./manage.py shell

```
>>> from django.contrib.auth.models import User
>>> user = User.objects.create_user('test','','test')
>>> user.is_staff = True
>>> user.save()

```

But I wanted to change him cause he can create a lot of things. So I added another user with the same permission and edit the **dev.py** or my **local_settings.py** with _SLUMBER_USERNAME_ and _**SLUMBER_PASSWORD**_ but it still doesn't work.

**Comment by ericholscher** [comment]
Thanks for working to get Read the Docs into your organization. We currently don't have time to support local installs for free as a core team. This is explained in more depth here: http://docs.readthedocs.io/en/latest/open-source-philosophy.html#unsupported -- I will close this issue because of this policy. 

We do offer paid hosting for companies at readthedocs.com, as well as [paid support](https://readthedocs.com/services/#open-source-support) for local installs.
