### ISSUE TITLE
Password Reset Email Template Seems to be broken

### ISSUE THREAD

**Issue by dhermes** [rtfd/readthedocs.org#3012]
## Details

* Project URL: Any (password reset is account level, not project level)
* Build URL (if applicable):
* Read the Docs username (if applicable): [dhermes][1]

## Expected Result

The Jinja2 template doesn't show up in the email.

## Actual Result

![beep](https://user-images.githubusercontent.com/520669/28481243-fea66cec-6e18-11e7-8a30-4168b457696e.png)

[1]: https://readthedocs.org/profiles/dhermes/

**Comment by ItsPugle** [comment]
Hey, @dhermes,

I'll be adding the **Bug** and **Sprintable** labels to this ticket with the triage process. As you could imagine, ReadTheDocs receives an extraordinary amount of tickets and issues through GitHub every week, and because of the smaller team, your request may take on the upside of several days to be processed and reviewed by the team.

Thank you for your patience,
ItsPugle - ReadTheDocs Triage Team

**Comment by ericholscher** [comment]
Should be fixed. 🎆

**Comment by dhermes** [comment]
@ericholscher I can confirm it's fixed (I reset my password every 14 days due to #3259 / me not using a password manager)
