### ISSUE TITLE
PR build fails with "bower: command not found"

### ISSUE THREAD

**Issue by gliptak** [rtfd/readthedocs.org#3019]
https://travis-ci.org/rtfd/readthedocs.org/jobs/258352523

```
$ bower install
bower: command not found
The command "bower install" failed and exited with 127 during .
Your build has been stopped.
```

https://github.com/rtfd/readthedocs.org/pull/3017

**Comment by jessetan** [comment]
If I browse through the succesful and failed Travis builds, it looks like all failed builds use the `trusty` distribution, rather than `precise`.
Example fail: https://travis-ci.org/rtfd/readthedocs.org/jobs/255533432/config
Example succes: https://travis-ci.org/rtfd/readthedocs.org/jobs/255492830/config 

This is consistent with [Travis CI plans to switch from Ubuntu Precise to Trusty](https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming).
Probably something changed in availability of bower in Trusty.
