### ISSUE TITLE
Setting to autobuild all tags

### ISSUE THREAD

**Issue by jakirkham** [rtfd/readthedocs.org#3039]
Would be nice to have a setting for simply autobuilding all tags. Currently one needs to go into the settings and enable these one at a time. By having all tags autobuilt, this would smooth out the release process quite a bit.

**Comment by humitos** [comment]
Hi @jakirkham! Thanks for the report.

I mean, I understand that you want to create a new tag and make RTD automatically active it and build it. I assume that this would only works for tags since branches make no too much sense to me, right? I like the idea.

Maybe we can add something to the YAML file like

    autobuild: tags

or

    autobuild: true

or similar.

**Comment by jouvin** [comment]
+1, it would be a very nice new feature. And it would be good if we could also define a maximum number of versions to automatically built, if this is not a version explicitely selected. This would allow to prune old versions automatically.

**Comment by humitos** [comment]
@stsewd this is something that could be considered in #3878

**Comment by stsewd** [comment]
@humitos I don't understand this very clear :/. This seems like a global setting, those aren't going to be handled on the YAML file. Maybe https://github.com/rtfd/readthedocs.org/issues/4001 is better for this use case (If I believe is this)?

**Comment by humitos** [comment]
Closing this in favor of #4001 which is closer to start being implemented.
