### ISSUE TITLE
links to github are broken

### ISSUE THREAD

**Issue by cokelaer** [rtfd/readthedocs.org#3203]
## Details

* Project URL: sequana.readthedocs, bioservices.readthedocs, bioconvert.readtheodocs and more 
* Build URL (if applicable): http://sequana.readthedocs.io/en/master/
* Read the Docs username (if applicable):  cokelaer

## Expected Result

link should work (there were working)

## Actual Result

links broken due to additional "origin" added in the links to github.

**Comment by dlech** [comment]
Broken here too: http://docs.ev3dev.org/en/ev3dev-stretch/index.html

**Comment by leastprivilege** [comment]
We have the same issue

https://identityserver4.readthedocs.io/en/release/

any comment on this? Can we fix that somehow ourselves?

**Comment by cokelaer** [comment]
AFAIC, the problem is still there for the projects mentioned above.

**Comment by humitos** [comment]
I think this is the PR that fixes this issue: https://github.com/rtfd/readthedocs.org/pull/3302

**Comment by benjaoming** [comment]
@humitos I think this issue is specifically about the local remote alias being added to the version name, Github knows nothing of `origin/` which is currently part of `github_version` being used in the template.

**Comment by humitos** [comment]
I've trying to reproduce this bug in my local instance using the `sequana` project but I wasn't able yet. On one hand, the `commit_name` property used in all the Version objects is correct and on the other hand, I wasn't able to build the documentation because the project fail with an issue that's not related to RTD. @cokelaer please, let me know when I can get a success build and I will try again with this project.

I will try to debug this issue again with the other projects linked in this ticket (probably tomorrow) and I will comment here the results. Thanks for the reports.

**Comment by benjaoming** [comment]
@humitos here are some examples of live projects with broken Edit buttons:

http://django-wiki.readthedocs.io/en/master/
http://discretize.simpeg.xyz/en/master/

**Comment by cokelaer** [comment]
Bioservices project has the Same issue and may be easier to install or one of the projet that @benjaoming just mentionned. I believe the issues are all related. Could be pbl with à newer version of sphinx maybe?

**Comment by humitos** [comment]
OK, I think I have "something to say" after my little research.

It seems that this _only happens_ with the `master` branch. I just built `django-wiki` and `discretize` both using `latest` version and links works properly. Then I activated the `master` branch on those projects and the Github link start pointing to the wrong link (adding the "origin" to the URL).

This is happening because in the `Version.commit_name` the value of `self.type` is `unknown` and it doesn't enter to this if, https://github.com/rtfd/readthedocs.org/blob/6fd828216fede4a64259c5d5f199f8e4fd5163e1/readthedocs/builds/models.py#L139
so it returns `self.identifier` which is `origin/master`.

Now, I need to find/understand why the `Version` is detected as `unknown` instead of a `branch`.

**Comment by humitos** [comment]
Sorry, I got confused with `discrete`. It's using the `dev` branch as `latest` and it's has the problem with the links to GH on that branch. It doesn't have the problem in `stable`.

**Comment by humitos** [comment]
I just propose a PR at #3427 that should fix this issue.

**Comment by humitos** [comment]
Hi all! The PR was already deployed. Can you rebuild your projects and let me know if it works as you expects? Thanks!

**Comment by dlech** [comment]
After a wipe and a build, it looks like my link above is working correctly.

**Comment by benjaoming** [comment]
Works for me, too -- no need to "wipe" first, worked on first rebuild :tada: 

Great work @humitos !

**Comment by cokelaer** [comment]
Same for bioconvert.readthedocs.io without a wipe
thanks. @humitos @agjohnson I believe we can close this issue

**Comment by humitos** [comment]
Thank you all for testing, reporting, etc. 

The issue was closed automatically when the PR was merged but I wanted confirmation from your side.

**Comment by paulmeems-waterwatchfoundation** [comment]
I know this issue is closed, but I'm facing the same problem.
Not sure if I should create a new issue.

My project: http://datastandard.globalcoffeeplatform.org
The 'Edit on GitHub' points to 
https://github.com/globalcoffeeplatform/CoffeeDataStandard/blob/origin/master/docs/source/index.rst
but it should point to 
https://github.com/globalcoffeeplatform/CoffeeDataStandard/blob/master/docs/source/index.rst
Without the 'origin' part.

I've rebuild several times. Perhaps I need a different version of some tool?
I'm using Spinx v1.8.4 and sphinx-rtd-theme v0.4.2
Here's my latest build result: https://readthedocs.org/api/v2/build/8790271.txt
