### ISSUE TITLE
Clone a project

### ISSUE THREAD

**Issue by ncoghlan** [rtfd/readthedocs.org#327]
I have a project which is set up the way I want, but because I originally had the name wrong, the URL on RTFD is wrong (beaker-draft-admin-guide instead of beaker-dev-docs).

It would be handy if a project could be cloned in order to get an updated URL slug instead of having to create it from scratch with the corrected name.

**Comment by nanuxbe** [comment]
+1 for this or simply not allowing people to freely change their slug but mirroring project name changes on the project slug.

**Comment by gregmuellegger** [comment]
Regarding setting up a new project with the same config as another one: We are working on some `readthedocs.yml` config that you can put in your repository, similiar to a `.travis.yml`.

@nanuxbe That's a good point. However usually the project slug should be kept stable. Where did you experience the change in the slug after changing the name?

**Comment by nanuxbe** [comment]
@gregmuellegger BitBucket is one example of a name change leading to a slug change.
I can see the need of keeping the slug stable as for search engine and external links but this is also the reason why changing the slug can be important as urls are very important to search-engines. Here's my current situation and why I'm interested in the topic:
I recently had to rename a project because the project's name was a slur word in some language which I was not aware of at time of creation.
Now that the project had been renamed I really don't want that project's read-the-docs pop up as search results for that slur word but in keeping the slug, this is likely to happen.
Also, now that the project has been renamed, people with a new interest in the project might instinctively check https//slug-of-new-name.readthedocs.org

I don't have any insight with RTD name change statistics, but I would guess that people don't change the name of a project that often and that, when they do, they have a good reason to do it and don't want the old name to still be associated with the project (think of name change due to copyright infringement too), which is likely to happen if the project still has its old name as RTD slug.
Now I realize this probably doesn't happen often and should probably not be treated as a high-priority issue but I thought it was still worth raising the question.

**Comment by gregmuellegger** [comment]
That all seems like a valid point. I created a new ticket for this in #1440 as this one has different topic.

**Comment by gregmuellegger** [comment]
Closing this issue as we now have #1440 to keep track of the development of "Allow to change project slug".
