### ISSUE TITLE
Error in YAML configuration docs: default value for `python.setup_py_install` should be `true`

### ISSUE THREAD

**Issue by jonrkarr** [rtfd/readthedocs.org#3334]
Regarding the YAML configuration docs (http://docs.readthedocs.io/en/latest/yaml-config.html), the default for `python.setup_py_install` appears to be `true` rather than `false` which is stated in the documentation

**Comment by RichardLitt** [comment]
Sounds like a small PR is in order. :)

**Comment by jonrkarr** [comment]
Thanks for building the conda feature! This is very helpful for documenting packages that require more complex environments.

One more suggestion: I think it would helpful to expand the conda to note to say that requirements.txt files are not used when the conda option is used. If the conda option is used, all requirements must be invoked by setup.py or stated in environment.yml.

**Comment by humitos** [comment]
Thanks for your report.

> Perhaps there should be a mention of projects that have never had a successful build.

I would suggest you to create a new issue for this since it's different from the one reported. Thanks!

**Comment by JavaDevVictoria** [comment]
Hi, I have submitted a pull request for this issue here: https://github.com/rtfd/readthedocs.org/pull/3357

**Comment by agjohnson** [comment]
I tested that the following were all true:

* Default model value for installing project is False
* Default config value for installing project is False
* Bare project doesn't attempt to install project

So, the documentation still seems correct, this option does not seem to be enabled by default. Feel free to reopen if you have a specific case that shows otherwise, but as it stands, I don't think we need to update our docs.
