### ISSUE TITLE
Port over JSON builder avoidance from pydoc

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#3393]
Pydoc gets around this by building the JSON output into Sphinx. Port this over.

**Comment by ericholscher** [comment]
The existing logic is:

* RTD: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/projects/tasks.py#L730-L735
* Pydoc https://github.com/rtfd/pydoc.io/blob/master/pydoc/sphinx/__init__.py#L32-L55

The quick version is:

* Currently we run an _entire_ second build to output JSON from Sphinx, in order to support search
* We should output the JSON as an artifact of the build process
* This might hit some edge cases in building people's docs, but it would save around 20-25% of our build resources, which would be a *huge win* for us

There will likely be some issues with weird encoding and other things, but I'd really like this to get some focus here soon.

**Comment by ericholscher** [comment]
@safwanrahman you might find this and the attached PR's interesting!
