### ISSUE TITLE
View / Edit doesn't work

### ISSUE THREAD

**Issue by grez911** [rtfd/readthedocs.org#3515]
## Details

* Project URL: https://github.com/HelloZeroNet/Documentation
* Build URL (if applicable): https://zeronet.readthedocs.io/en/latest/
* Read the Docs username (if applicable): 

## Expected Result

Click on `v:latest` in the right bottom corner -> On GitHub -> View / Edit.
It should open https://github.com/HelloZeroNet/Documentation/blob/master/docs/faq.md

## Actual Result

404 Error.

P.S. Please don't close as a duplicate of https://github.com/rtfd/readthedocs.org/issues/1422 or https://github.com/rtfd/readthedocs.org/issues/1483, because it's not fixed.

**Comment by stsewd** [comment]
I think this issue is related to Mkdocs only, with sphinx works fine.

I was able to replicate this on my local instance, looks like the "Edit" url is taken from the `mkdocs.yml` [file.](https://github.com/HelloZeroNet/Documentation/blob/master/mkdocs.yml#L5)

And also noted that the footer url (from the floating v) is incorrect `https://github.com/HelloZeroNet/Documentation/blob/master/home/docs/checkouts/readthedocs.org/user_builds/zeronet/checkouts/latest/docs/.md`

**Comment by stsewd** [comment]
I think the top edit button is related to the theme (not sure, I was unable to find that code), the link on the footer is definitely related to the code base.

**Comment by stsewd** [comment]
After investigating more on this issue, I found you are using a custom theme (based on rtd). So, the real problem is on the templates, isn't a RTD bug.

For the "edit" link you need to update this file https://github.com/HelloZeroNet/Documentation/blob/master/readthedocs/breadcrumbs.html and inject the appropriates values (see http://www.mkdocs.org/about/release-notes/#context-variables).

About the second problem, when #3525 is merged you need to define the global variable `READTHEDOCS_DATA['page']` (something like this https://github.com/HelloZeroNet/Documentation/blob/master/readthedocs/base.html#L25-L29, but must be after this lines https://github.com/HelloZeroNet/Documentation/blob/master/readthedocs/base.html#L38-L40). And everything would work properly.

**Comment by stsewd** [comment]
@grez911 I just see you deleted the whole custom theme, about the edit link please see https://github.com/rtfd/readthedocs.org/issues/3991#issuecomment-383276954

**Comment by stsewd** [comment]
Closing in favor of https://github.com/rtfd/readthedocs.org/issues/3991
