### ISSUE TITLE
Local repository not working properly

### ISSUE THREAD

**Issue by wfer88** [rtfd/readthedocs.org#3573]
##I cloned repository as per https://docs.readthedocs.io/en/latest/install.html but cant connect to social accounts

* Project URL: Local
* Build URL (if applicable):Local
* Read the Docs username (if applicable): fernawil

## Expected Result

*when i clone repository and set it up locally ,it should be able to connect social accounts like github ,gitlab*

## Actual Result

*I cloned repository and it running on http://localhost:8000 on my windows 10 machine. I was able to login but when i try to connect to gitlab or git hub through social accounts then following issue comes: DoesNotExist at /accounts/gitlab/login/  
 SocialApp matching query does not exist. 
Request Method: | GET
http://localhost:8000/accounts/gitlab/login/?process=connect

Also when I try to import manually I dont think it is working  as i build it   bulild stays in triggered state

Please help .
*

**Comment by stsewd** [comment]
You need to create a social app on the admin panel http://127.0.0.1:8000/admin/socialaccount/socialapp/, but first you need to create an application on [GitHub](https://github.com/settings/applications/new) or [GitLab](https://gitlab.com/profile/applications)  to get the secret keys. The callback urls are http://mydomain.com/accounts/gitlab/login/callback/ and http://mydoamain.com/accounts/github/login/callback/ respectively.

Note that your machine needs to be visible to Internet for the callbacks urls work.

**Comment by stsewd** [comment]
> Note that your machine needs to be visible to Internet for the callbacks urls work.

I use [ngrok](https://ngrok.com/) for local testing.

**Comment by humitos** [comment]
This issue is being marked as `Community Effort`. The core team will try to facilitate resolution with this issue, but without the resources to support external installations outside of our production environment, we must rely on the community to help.

You can read more information on our philosophy around supporting Read the Docs as an open source and volunteer run effort here: http://docs.readthedocs.io/en/latest/open-source-philosophy.html

Besides that, you also can use Stack Overflow for this problem and receive more help from the community.

Thanks,

**Comment by stsewd** [comment]
I think the same issue is addressed here #2243

**Comment by stsewd** [comment]
Closing this as a duplicate of #2243 (also moving the `community effort` label there)
