### ISSUE TITLE
Build failing: due inactivity in only 34 seconds

### ISSUE THREAD

**Issue by rhtyd** [rtfd/readthedocs.org#3574]
## Details

* Project URL: https://readthedocs.org/projects/cloudstack-release-notes/builds/
* Build URL (if applicable): https://readthedocs.org/projects/cloudstack-release-notes/builds/6678782/
* Read the Docs username (if applicable): bhaisaab

## Expected Result

Build should pass

## Actual Result

Build failed

**Comment by humitos** [comment]
This build was terminated due to inactivity: `This build was terminated due to inactivity` but the it says that only took 34 seconds.

This is done by a Celery task at https://github.com/rtfd/readthedocs.org/blob/df8079a18ed9c15e9c85f0646e3e9169e725b310/readthedocs/projects/tasks.py#L1048-L1089

I'm marking this report as a bug and changing the title.

**Comment by humitos** [comment]
I found the issue.

* The `Build` object is created immediately when it's triggered (that assign the `date` attribute to now)
* Then, after some time, the Celery worker take the tasks from the queue and execute it

So, the time where the build is created with the time that it's executed _are slightly_ different. In this case, it happen that for some reason Celery workers where busy for too much time and when your tasks was executed by the worker was immediately killed because it seemed an old running build.

* Build creation date: `2018-02-02T05:01:46.347606`
* Build execution started date: `2018-02-02T11:01:53.647017`

(sicen there are 6hs of difference, this seems that there was a problem with Celery)

> You can check those dates in the API, https://readthedocs.org/api/v2/build/6678782/

One possible thing we could do is to check with Celery if the task was deleted/is on queue or similar to make a better decision. Although, I think it doesn't worth the effor on coding that and probably is more error-prone.

The real issue, was that a server problem. I'm closing this issue, but feel free to reopen if you consider.
