### ISSUE TITLE
Moving away from readthedocs.io

### ISSUE THREAD

**Issue by jbednar** [rtfd/readthedocs.org#3577]
* Project URL: http://datashader.readthedocs.io/

My project's documentation is now hosted on S3 in a custom domain (datashader.org), and I no longer want to use readthedocs to build its documentation.  I've pointed readthedocs at a special branch where all the .rst files have been replaced with links to the new site, which should help ensure that people aren't confused. But ideally:

1. readthedocs wouldn't still build or host any datashader-related files anymore (use those resources for another worthy project!)
2. http://datashader.readthedocs.io/* would redirect to http://datashader.org/* automatically (via 301 redirects)

Are either of these two outcomes possible?  I couldn't see anything about redirects *away* from readthedocs.io...

**Comment by davidfischer** [comment]
With respect to redirects to another domain, we don't yet have support for it but there is another PR #2267 tracking it. We would welcome a PR for it and it could be an enhancement to the existing redirects. I think your solution is the current best solution.

Was there a specific reason why you decided to self host? It wasn't just because of a custom domain right (RTD supports that)?

**Comment by jbednar** [comment]
Thanks.  The main reason for moving to our own host is that datashader's website build process involves about 30 GB of data that is impractical to host in github and impractical to download as part of the readthedocs build process.  But it's a project about working with big data, so we're a special case!
