### ISSUE TITLE
Access to media.readthedocs.org/fonts/fontawesome-webfont.woff2 blocked by CORS policy

### ISSUE THREAD

**Issue by aaksarin** [rtfd/readthedocs.org#3586]
## Details

* Project URL: http://django-compressor.readthedocs.io/
* Build URL (if applicable):
* Read the Docs username (if applicable): 

## Expected Result

Page loaded without errors.

## Actual Result

> (index):1 Access to Font at 'https://media.readthedocs.org/fonts/fontawesome-webfont.woff2?v=4.6.3' from origin 'http://django-compressor.readthedocs.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://django-compressor.readthedocs.io' is therefore not allowed access. The response had HTTP status code 404.

**Comment by davidfischer** [comment]
I think the issue is here because the URL https://media.readthedocs.org/fonts/fontawesome-webfont.woff2?v=4.6.3 404s. This shouldn't actually cause any page differences as https://media.readthedocs.org/fonts/fontawesome-webfont.woff is also loaded and loads without issue.

I believe there is a CORS issue because when a successful 200 is returned the `Access-Control-Allow-Origin` header is added. However, because there's a 404, that header isn't there. I think simply uploading the woff2 file to the media server will resolve this.

**Comment by aaksarin** [comment]
@davidfischer yeah, I think you are right. I did pull request with missing file. Thanks.

**Comment by Ayukha** [comment]
@aaksarin  Can i try?

**Comment by aaksarin** [comment]
@Ayukha, yeah, fill free to fix it.

**Comment by fiennyangeln** [comment]
@aaksarin Hi, a newcomer here. I have downloaded the fontawesome file and put the woff2 file. Please check if my way of doing things are correct. Thanks a lot

**Comment by aaksarin** [comment]
@fiennyangeln, Hi. I don't know if this is correct, i'm just posted issue and supposed fix. @RichardLitt, can you look please?

**Comment by RichardLitt** [comment]
@fiennyangeln Looks like a good start! Comments will happen on that PR; when it is merged, this will be fixed. :)

**Comment by fenilgandhi** [comment]
@RichardLitt  @fiennyangeln Is this issue still open ? Or can i fix it ?

**Comment by stsewd** [comment]
@fenilgandhi there is a PR #3602 already.

**Comment by fenilgandhi** [comment]
Ok Thanks

**Comment by agjohnson** [comment]
I believe we fixed this with a previous release. I don't see the behavior on the reported doc site anymore, so safe to close I think.
