### ISSUE TITLE
Dashboard filtering of projects needs your own name 

### ISSUE THREAD

**Issue by pydanny** [rtfd/readthedocs.org#3674]
## Details

* Project URL: https://readthedocs.org/dashboard/import/?
* Build URL (if applicable):
* Read the Docs username (if applicable): pydanny

## Expected Result

I want to be able to select my name as a filter and only see the 200-odd packages I list on Github.

## Actual Result

Because I cannot filter by my own name, I have to paginate through the entire 4000+ packages of conda-forge. This makes the automation system unfortunately useless to me, and I have to manually import projects into RTD.

**Comment by stsewd** [comment]
There is already a PR on progress for this feature https://github.com/rtfd/readthedocs.org/pull/3548

**Comment by pydanny** [comment]
Thanks @stsewd. 

I quit Conda-Forge so as to be able to not have their 4000+ projects listed along with mine. However, those repos are cached against my account so in RTD there is no change. Is there any chance that cache can be reset for just me?

Thanks for all your awesome effort!

**Comment by stsewd** [comment]
@pydanny I don't have access to the database, maybe @humitos could help here.

This is also related to #1887

**Comment by humitos** [comment]
> However, those repos are cached against my account so in RTD there is no change. Is there any chance that cache can be reset for just me?

Mjm... I'd say that this is a bug. Currently the `sync` method for each service is only adding new repositories, but they are never deleted. So, it's not a _real sync_ :)

The code for Github service is at: https://github.com/rtfd/readthedocs.org/blob/0e1112f96e3ba344271a44305028a811072fd10a/readthedocs/oauth/services/github.py#L38-L48

Thought, I think this issue is different that the one that you are reporting in the first description and I suppose the first one should be solved by the PR (linked by @stsewd) that I'm trying to wrap up and get merged.

Please, @pydanny, confirm this so we can address this (update this issue/create a new one).

**Comment by humitos** [comment]
@pydanny just in case, the ability to filter by your own repos is already merged and working. It does not fix this issue but helps on filtering the respo :)

**Comment by stsewd** [comment]
So, the fix for the original issue is already implemented, we can keep track of the other issue in https://github.com/rtfd/readthedocs.org/issues/1899
