### ISSUE TITLE
:ref: target not highlighted in navigation bar

### ISSUE THREAD

**Issue by sda399** [rtfd/readthedocs.org#3679]
## Details

- inside a section
- create a label on a subsection A and link to it with :ref:, from another subsection B

## Expected Result

navigation bar highlights the the target subsection B

## Actual Result

navigation bar highlights the the source subsection A, where the :ref: in called

ref documentation:
http://www.sphinx-doc.org/en/master/markup/inline.html#role-ref

**Comment by stsewd** [comment]
Could you provide more information? (rtd project page, build url, etc). Otherwise this seems to me like a sphinx problem no rtd. Thanks!

**Comment by sda399** [comment]
here is an example of a link to a labeled section:
https://docs.readthedocs.io/en/latest/getting_started.html#in-rst

the navigation tree is not highlight correctly,
but the following link highlights 'in-markdown' section as expected:
https://docs.readthedocs.io/en/latest/getting_started.html#in-markdown

notice that 'in-markdown' label and title are approximately the same, and in-rst and 'in restructuredtext' aren't very close.

maybe a sphinx-doc issue but rtd is the only theme I know that highlights navigation tree, so the mistake might be more obvious here.

**Comment by humitos** [comment]
I found something here. It seems there is an extra `span` labeled `in-rst` but the correct one is `in-restructuredtext`: https://docs.readthedocs.io/en/latest/getting_started.html#in-restructuredtext

![captura de pantalla_2018-02-28_09-51-53](https://user-images.githubusercontent.com/244656/36794017-2267c204-1c6d-11e8-8299-11f8b02d595b.png)

Also, another issue is that clicking twice in the `In reStructuredText` from the navbar it gets highlighted the first one but the second one looses it.

This probably is an error in the RTD Sphinx Theme (https://github.com/rtfd/sphinx_rtd_theme) instead of in the RTD.org source.

**Comment by sda399** [comment]
might be.
Is there a GitHub to transfer an issue to another project? :sweat_smile:

**Comment by humitos** [comment]
What we have done is just open a link in the other project and link it to here. Then close this one.

I'm not very familiarized with the Sphinx them, so I'm pinging @Blendify here since he is our rock star on this topic and maybe can help you in case you want to propose a PR ;)

**Comment by Blendify** [comment]
Yes please open a report for the theme. We have modified the javascript responsible for this since our the last release so I would recommend checking using our master version. Use `pip install -e https://github.com/rtfd/sphinx_rtd_theme/archive/master.zip`

**Comment by Blendify** [comment]
Closing see  https://github.com/rtfd/sphinx_rtd_theme/issues/583
