### ISSUE TITLE
Adding a Maintainer is shown as a Owner

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#3694]
1. Go to your project's Admin page
1. Go to Mainteiners
1. Add a new mainteiner
1. Go to your project's detail page

The mainteiner is shown under a **Owners** title.

![captura de pantalla_2018-02-27_12-51-46](https://user-images.githubusercontent.com/244656/36745276-fe00626e-1bbc-11e8-8054-aa9e854bd3d1.png)

I think we should use the same word for this, either _Mainteiners_ or _Owners_ but not both.

**Comment by ajatprabha** [comment]
Hi @humitos, I would like to implement this. Since I'm new here, can you please tell me the next step towards the process.

**Comment by stsewd** [comment]
This was a question I had the other day, if rtd differences between the main owner (who created the project) and others owners.

**Comment by ajatprabha** [comment]
Hey @stsewd, from what I've inspected in the `Project` model, RTD doesn't differentiate between owner and maintainers. A user(maintainer/owner) can remove another user.
If A is an owner and B is a maintainer, B can remove A, because of `users` attribute (ManyToMany relation with `User` model) and logic implemented.

@humitos, I believe that's why you've considered this a UI enhancement and not a model critical design change. Correct me if I missed something!
But I wanted to know if it is required to differentiate owner and maintainer?

**Comment by humitos** [comment]
Yes. I'm talking about the UI (not the behind the scenes and django modeling).

**Comment by ajatprabha** [comment]
Should it be called owner or maintainer? In my opinion, maintainer is a better choice.

**Comment by ajatprabha** [comment]
@humitos, since this issue is considered under UI improvement, I've created a PR with taking maintainer as the word because it is used in other places as well. Can you please review it?

**Comment by stsewd** [comment]
This was resolved in https://github.com/rtfd/readthedocs.org/pull/3703
