### ISSUE TITLE
Installation instructions shouldn't mention python 2.7 anymore

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#3810]
RTD runs on python 3! Drop the notice around using python 2.7 only.

Docs here:
http://docs.readthedocs.io/en/latest/install.html

**Comment by stsewd** [comment]
I was trying to change that on this PR
https://github.com/rtfd/readthedocs.org/pull/3631#discussion_r168938696

**Comment by rajujha373** [comment]
@agjohnson @stsewd @humitos installation docs for Readthedocs is missing out so much of information and in my opinion should be updated.
Like, I am stuck up with the version of elasticsearch to be used, tests always fail for python 36 (now I know because I was using py27 virtualenv). If there's a way I can contribute updating the docs, I would love to do so.

**Comment by stsewd** [comment]
@rajujha373 this PR #3631 aims to do that, can you take a look and tell if that covers your issues?. Also about elasticsearch, there is a discussion about dropping it from the installation guide for now, since in more cases isn't necessary for start to contributing.

**Comment by stsewd** [comment]
Resolved in https://github.com/rtfd/readthedocs.org/pull/3817
