### ISSUE TITLE
Problem while building your documentation

### ISSUE THREAD

**Issue by sdebionne** [rtfd/readthedocs.org#3876]
## Details

* Project URL: https://readthedocs.org/projects/lima-doc/
* Build URL (if applicable): https://readthedocs.org/projects/lima-doc/builds/6962290/
* Read the Docs username (if applicable): same as GitHub

## Expected Result

My documentation builds fine locally. Only the branch `unsubmodule-doc` is supposed to work (not master) at this point.

## Actual Result

There was a problem with Read the Docs while building your documentation. Compilation fails after `git clean -d -f -f` command.

**Comment by agjohnson** [comment]
We see the following error here. I'm not sure if this is a wonky submodule config or a legitimate issue with our submodule handling:

```
Build failed with unhandled exception: Gitmodule path u'third-party/yat' did not exist in revision of parent commit HEAD
```

This isn't the only build we notice this type of error on, so this is pointing to a bug. Could you elaborate on the submodule config? That might help us determine the cause here, as I'm not quite sure what this error is currently.

**Comment by sdebionne** [comment]
Thank you for you kind support! It was indeed an issue with a ghost submodule. Deleting the submodule was the solution, not sure why I did not catch it when cloning and compiling locally. Thank you again.
