### ISSUE TITLE
Fail.  Check back in a bit!

### ISSUE THREAD

**Issue by anilgursel** [rtfd/readthedocs.org#3890]
## Details

```
          .
         ":"
       ___:____     |"\/"|
     ,'        `.    \  /
     |  O        \___/  |
   ~^~^~^~^~^~^~^~^~^~^~^~^~

   Fail.  Check back in a bit!

```

* Project URL: https://readthedocs.org/projects/squbs/  (I get the above error with this)
* Build URL (if applicable): https://readthedocs.org/projects/squbs/builds/  (I can actually access to this)
* Read the Docs username (if applicable): 

## Expected Result

I would like to be able to access https://readthedocs.org/projects/squbs/ and not required to manually add the "builds", "versions" at the end of the url.

## Actual Result

I see "Fail.  Check back in a bit!" error.

**Comment by stsewd** [comment]
Related to #3892

**Comment by humitos** [comment]
@anilgursel Hi! The problem is your username which has some "weird" characters on it (allowed ones, though) but they are not allowed in the regex that resolves the URL for your profile.

https://github.com/rtfd/readthedocs.org/blob/393e31ad3a9aafee297df64f1a654ffcda7ef04a/readthedocs/profiles/urls/public.py#L10

We should probably change that regex to fit the allowed characters.

... checking the regex, it has a `.` on it, so it should match _any_ character.

**Comment by stsewd** [comment]
I think there is a PR for that issue https://github.com/rtfd/readthedocs.org/pull/3725

**Comment by stsewd** [comment]
@humitos the `.` is inside a character class, so it matches a literal `.`.

**Comment by stsewd** [comment]
This was solved on https://github.com/rtfd/readthedocs.org/pull/3725
