### ISSUE TITLE
Cannot display versions box

### ISSUE THREAD

**Issue by Juanlu001** [rtfd/readthedocs.org#4020]
## Details

* Read the Docs project URL: http://poliastro.readthedocs.io/en/latest
* Build URL (if applicable): https://readthedocs.org/projects/poliastro/builds/7097071/
* Read the Docs username (if applicable): Juanlu001

## Expected Result

*A description of what you wanted to happen*

When clicking the bottom-left `v: latest` arrow, I expected to see the menu, as it properly happens when manually changing the URL to, for example, http://docs.poliastro.space/en/stable/ and clicking in `v: stable`.

## Actual Result

*A description of what actually happened*

The versions box does not display, and I see a

```
JS Error "SphinxRtdTheme.Navigation is undefined"
```

error in the console. I already whitelisted RTD in AdBlocker.

**Comment by humitos** [comment]
This is a known issue on `sphinx-rtd-theme==0.3.0` :disappointed: 

You will need to modify your `requirements.txt` file to pin it as `<0.3` (please, update us if this fixes your issue)

We are working on it at https://github.com/rtfd/readthedocs.org/issues/3925#issuecomment-382452104. Please, subscribe there to get notifications. 

Your latest `stable` (0.8.0) was built with `sphinx-rtd-theme-0.2.4`, that's why it works.

I'm closing this one as it's duplicated of a known problem. Thanks!

> I already whitelisted RTD in AdBlocker.

:heart:
