### ISSUE TITLE
If one social account fails on sync the rest are not executed

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#4076]
While working on #4070 I found that if the user has 3 accounts connected and the first one fails for any reason (revoked token, for example) the other two are not going to be executed.

In this case, the user has two options to workaround this:

1. disconnect the account that it's failing
1. solve the issue with that account

I think we need to solve this from RTD side. The sync is executed in a celery task by looping over the connect accounts from that user and _we need_ the `Exception` raised by this sync since we are using the `state` and the `info['error']` attribute to communicate this to the user in the Javascript polling.

To reproduce this, 

1. connect 2 social accounts to your RTD account and go to the web page of the first one (found in that loop) and revoke the RTD application
1. click on the sync button when importing a project

**Comment by luanfonceca** [comment]
Hey @agjohnson, i would like to fix this one during the Djangocon sprint. It's okay?

**Comment by humitos** [comment]
@luanfonceca yes, the loop is endless because the celery task the server executed crashed, so no proper result is returned to the front end and it keeps trying to get a response.

The solution would be to handle the proper exception risen in the server and continue the execution for the next social account.

**Comment by stsewd** [comment]
@humitos I have some code working for this, but I have a question. I'm returning all the errors like this

![screenshot_2019-01-17 import a remote repository read the docs](https://user-images.githubusercontent.com/4975310/51353244-0c88bc80-1a7e-11e9-8625-9ae47f2a6336.png)

I'm thinking in returning a list for error instead of just one, but for that I need to modify the api from `public_tasks`. Should I go for that way? Or maybe just return the first error?

**Comment by stsewd** [comment]
We only use `public_task` for syncing the repo and for reporting the build commands.

**Comment by humitos** [comment]
That's way better!
