### ISSUE TITLE
Expired certificate for cdnmedia.readthedocs.org 

### ISSUE THREAD

**Issue by janw** [rtfd/readthedocs.org#4082]
## Details

Accessing docs for projects using cdnmedia.readthedocs.org for assets causes bare html output, since browsers are returning a certificate error for expiry (26 days ago). 

* Read the Docs project URL: https://icalendar.readthedocs.io/en/latest/

Overriding the expiry error manually causes all contents to render properly.

## Expected Result

![bildschirmfoto 2018-05-11 um 11 31 38](https://user-images.githubusercontent.com/1690502/39917977-6a9c6b9e-550f-11e8-953d-5e8d3b3708a5.png)

Beautifully styled and fuctional output of docs for Python's icalendar module.

## Actual Result

![bildschirmfoto 2018-05-11 um 11 34 53](https://user-images.githubusercontent.com/1690502/39917968-64333bac-550f-11e8-8709-7f079647676e.png)

CSS and JS resources are not loaded.

**Comment by davidfischer** [comment]
Thanks for reporting this. Read the docs doesn't really use the host cdnmedia.readthedocs.org anymore as all the static media is served from media.readthedocs.org. The reason icalendar is having this issue is that these docs haven't had a successful build in almost 3 years so they are using an old server.

I'm still considering updating the cert but perhaps a better solution is to try to help the icalendar people get a successful build.

**Comment by davidfischer** [comment]
The error in their docs is on this line:

    pkg_resources.get_distribution('icalendar').version

which results in an error.

**Comment by davidfischer** [comment]
I created a PR for them that should fix their docs: https://github.com/collective/icalendar/pull/262

**Comment by janwh** [comment]
Great — thanks! In the end, I decided against using the module anyways, so there's no pressure in that regard 😆

**Comment by agjohnson** [comment]
Closing this as not an issue with RTD.
