### ISSUE TITLE
Enable `PIP_ALWAYS_UPGRADE` feature

### ISSUE THREAD

**Issue by wmayner** [rtfd/readthedocs.org#4156]
The project feature `PIP_ALWAYS_UPGRADE` was merged in PR #3201. I'm wondering if it's possible to use this feature as a user; it looks like it's not exposed yet.

**Comment by stsewd** [comment]
The features options are set by the rtd team by user requesting it. This could be an option for https://github.com/rtfd/readthedocs.org/pull/4084

**Comment by wmayner** [comment]
Oh, gotcha—didn't realize that!

In that case, I'd like to enable it for my project: <https://pyphi.readthedocs.io> (username `wmayner`)

**Comment by wmayner** [comment]
Thanks! It looks like the upgrade flag is working.

I'm still not getting the behavior I expect, however (maybe this should be a separate issue—let me know):

I have my own [fork of `sphinx_rtd_theme`](https://github.com/wmayner/sphinx_rtd_theme), and I'm trying to get the styles from my fork to override the default styles on readthedocs.org. But it looks like the `theme.css` that's served is still the upstream version.

Maybe I'm misunderstanding how the styles are applied? Or maybe it's a caching issue? Any help would be appreciated.

**Comment by humitos** [comment]
I just check this build output (https://readthedocs.org/projects/pyphi/builds/7268449/) and the feature that I added to your project worked since I can see the `--upgrade` option passed to `pip`.

Regarding the css: yes, that seems to be a different issue. Please, open a new one (and close this one) so we can track it there. We will need to research a little more to solve that.
