### ISSUE TITLE
Decide best way to do validation on yaml config

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#4181]
When organizing work for the YAML configuration, I wanted to start with writing a schema first, using `yamale`. This was supposed to be to help formalize our specification in a human and machine readable format.

The next step of the work around the YAML improvements is to start writing the code to ensure the specification implementation matches our schema. The decision here is whether to continue with writing our configuration validation manually [1] or to start using yamale and rewrite this validation and parsing.

Some thoughts:

* We already have already written the validation code around our config [1], it seems like a duplication of effort to rewrite this validation
* We might have to maintain significantly less validation code if we instead use yamale as an application dependency
* We need to be careful of the return error messages to users if we validate with yamale, as all of these might change
* We might need to extend yamale to do what we need to do with defaults and cross-field validation

Let's discuss if it makes sense to make this change, or to just port the config validation and config tests from the build repository.

1: https://github.com/rtfd/readthedocs-build/blob/master/readthedocs_build/config/config.py

**Comment by stsewd** [comment]
Just some thoughts:

- The yamale project doesn't look very active (in adding new features at least), so we may need to fork the project or build around that.
- If we don't use yamale, we need to update the spec and the validation at the same time (or maybe we want to describe all the validation in our code?).
- I think we can improve the current validation system, so there isn't so much duplication and we can describe validations in a better way.
- Yamale return all the error messages joined but is possible to get the original list if we send a patch.

**Comment by humitos** [comment]
I think if we don't use yamale to validate the file we are loosing half of its features and we will end up maintaining two different things: the spec and the validators. I understand that at this point it means extra effort without winning (since our current validator is working) but I think in the future this will save us time, finally. On the other hand, I saw that Santos did some custom validators with a few lines, so it's doesn't seem to be crazy the re-write of custom validators since many of the default ones are useful for us.

The downside of this is, as @stsewd mentioned is that the project is not very active and I don't really like that since it seems that the effort that we can save by using an external library could be "us becoming the maintainers" :( . This is a very tricky point from my point of view.

Is is possible have a mix of both validators and migrate gradually from our current validation system to the Yamale? I mean, for example, all the old fields are validated via our current validator and the new fields are validated by the new things that we write in Yamale.

Final question: can we easly modify the validation error messages that Yamale raises and use our custom ones? I'd prefer to not change them, if possible.

**Comment by stsewd** [comment]
> Final question: can we easly modify the validation error messages that Yamale raises and use our custom ones? I'd prefer to not change them, if possible.

I think we could parse the error, but better would be to modified yamale and return the additional information
https://github.com/23andMe/Yamale/blob/edb7ea4972fc8420e4470907dc60967cb91ad9bb/yamale/schema/schema.py#L45-L56

**Comment by agjohnson** [comment]
For sake of pushing this project forward, it sounds like we can go the path of least resistance and just reuse the current validation and test patterns. We can discuss refactoring to use yamale at the end of the project.

There definitely are some benefits to using yamale for validation, but we're about a month into this project and haven't started with the meat and potatoes of the implementations. If there is time at the end of the project, this could be on our radar though.

I'll create an issue to address potentially adding yamale validation later.
