### ISSUE TITLE
Delete untracked tags on fetch step

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#4258]
Currently, if the user deletes a tag, it needs to wipe the environment for this change be reflected in their version list.

There are some solutions to delete untracked tags (require more than 2 commands). But I found that the newest version of git has the `--prune-tags` option, which is used as `git fetch --prune --prune-tags` (`git >2.17`). We need to update git on the servers (we use 2.7.4) and change the fetch command. Or we can find a way to wipe the environment if we detect something like this case.

Raised in https://github.com/rtfd/readthedocs.org/pull/3913#issuecomment-396673349

**Comment by humitos** [comment]
I think we can implement the command you mentioned here very soon since we are migrating our servers to Ubuntu 18.04 which includes 2.17.1 by default: https://packages.ubuntu.com/bionic/git

The PR needed for this should be very simple and shouldn't have any secondary effect :)

I'm :+1: on adding the `--prune-tags` to our current command.

**Comment by agjohnson** [comment]
Blocking until .com update to 18.04

**Comment by ericholscher** [comment]
Believe that #4811 didn't totally fix this. Reopening for now.

**Comment by stsewd** [comment]
So, tags are being deleted, the sync version is because of another problem, I opened https://github.com/rtfd/readthedocs.org/issues/4875
