### ISSUE TITLE
No warning banner displayed for pre-release versions

### ISSUE THREAD

**Issue by sloria** [rtfd/readthedocs.org#4327]
## Details

* Read the Docs project URL: https://marshmallow.readthedocs.io/en/3.0.0b11/
* Build URL (if applicable):
* Read the Docs username (if applicable): sloria

I have the "Show warning banner" option checked in Admin.

<img width="432" alt="edit advanced project settings read the docs 2018-07-03 17-44-28" src="https://user-images.githubusercontent.com/2379650/42246108-5f49901a-7ee9-11e8-8c57-02c5cbe81aee.png">

## Expected Result

A warning banner on pre-release docs.

## Actual Result

No warning banner is displayed.

**Comment by stsewd** [comment]
RTD doesn't show the warning banner in pre-release versions because this is marked as a higher version, not as an old one.

**Comment by humitos** [comment]
Hi @sloria! Thanks for your raising this issue.

There is a lot of discussion around the warning banner in https://github.com/rtfd/readthedocs.org/issues/3481. Because of all the different cases, we added that option you found which is marked in False by default since it's very complex to support all the different cases the projects need.

Also, I started a personal small sphinx extension to test these different cases. I didn't work too much yet on it and it didn't work dynamically yet, but it's a starting point. You can check it out at https://github.com/humitos/sphinx-version-warning

I think we are not going to add more work around the warning banner _inside_ the RTD code, but _I_ want to work on that extension when I have some free time. I will close this issue here, but feel free to reopen or give us feedback here.
