### ISSUE TITLE
Consider increasing the 900s time limit for projects using conda

### ISSUE THREAD

**Issue by fmaussion** [rtfd/readthedocs.org#4432]
## Details

* Read the Docs project URL: http://xarray.pydata.org/ and http://salem.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/xray/builds/
* Read the Docs username (if applicable): fmaussion

## Expected Result

Two libraries I'm maintaining (https://github.com/pydata/xarray and https://github.com/fmaussion/salem) regularly bump into the 900s time limit. The bottleneck is the conda installation of our dependencies, which often takes more than 500s (depending on bandwith and other parameters).

I know that you guys are offering all this for free and we are grateful for this! I also understand the reasons for defining a build time limit. Here, however, I believe that slightly increasing the timeout limit to 1000 or 1200 s would be mostly beneficial for RTD's resources *on average*, because our current solution is to build and re-build and re-build the docs until it finally comes through (https://readthedocs.org/projects/xray/builds/).

Thanks for your time!

## Actual Result

The builds timeout much more often than not

**Comment by fmaussion** [comment]
Related discussion on the xarray repository: https://github.com/pydata/xarray/issues/2209

**Comment by stsewd** [comment]
This is interesting, the command says it fails because of time out, but the last command says it was killed due to memory consumption

**Comment by humitos** [comment]
@fmaussion hi! Thanks for reporting this.

We have a fixed time of 900s as default for different reasons but we usually increase the time for building a project if the owner asks us and we determinate that is the main reason.

Also, we point users to a guide page that we have under our docs to see if they can speed up the building time by their own avoiding unnecessary calculations: https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html and #4419 . In your particular case, you can consider installing fewer dependencies --which may not be needed to build your docs. If that's the case, we will really appreciate to reduce them to save building time, bandwidth and more from our servers.

On the other hand, if your problem is around memory consumption, that's a more complex problem and we don't have a perfect solution yet: #4403 

In the meantime, I increased `xarray` time limit to 1800s and triggered a new build: https://readthedocs.org/projects/xray/builds/7549108/ . Let's see how it goes.

**Comment by humitos** [comment]
It failed due to memory consumption now :disappointed: 

I increased the memory limit to 1.5g, but as I stayed in #4403 this is risky and I may need to revert this change.

I triggered a new build with 1.5g of memory. Let's see :pray:

**Comment by humitos** [comment]
OK! I'm starting my tests again because, I have to say it, I got confused because the project's name is `xarray` but its slug is `xray`.

So, build with 1800s https://readthedocs.org/projects/xray/builds/7549241/

**Comment by fmaussion** [comment]
Thanks all for your help, this is much appreciated!

> This is interesting, the command says it fails because of time out, but the last command says it was killed due to memory consumption

Yes, I think this is a bug in RTD, because the message always comes after ~ 905s of run time, no matter what.

>  I got confused because the project's name is xarray but its slug is xray.

Sorry about that, our project was renamed from xray to xarray a while ago.

> In your particular case, you can consider installing fewer dependencies --which may not be needed to build your docs. If that's the case, we will really appreciate to reduce them to save building time, bandwidth and more from our servers.

I agree. In our case it is difficult because we support many libraries for IO, and provide an example in our docs for each. We will use the resources as sparingly as we can, though.

May I ask for the same extension for my related project salem? https://readthedocs.org/projects/salem/ 

It extends xarray and therefore has the same dependency issues...

**Comment by humitos** [comment]
Hi @fmaussion! `xarray` and `salem` are already using our preference queue that allows more build time and ram.

Let me know if you find any issue related to this or if you have any feedback. I appreciate.

I'm closing this issue here, but feel free to reopen if you consider.
