### ISSUE TITLE
Edit on Github link pointing to non-existant branch

### ISSUE THREAD

**Issue by ba66e77** [rtfd/readthedocs.org#4441]
## Details

* Read the Docs project URL: http://blt.readthedocs.io/en/latest/ or http://blt.readthedocs.io/en/8.9.x or http://blt.readthedocs.io/en/9.x

## Expected Result

*A description of what you wanted to happen*
I want the Edit on Github link to point to the correct branch on github based on what version of the docs people are looking at, rather than pointing to 'master' on all versions

## Actual Result
Regardless of version of the docs, the Edit on Github link points to the "master" branch, which does not exist in our repo. Seems like there has to be configuration setting there that I'm just not seeing for some reason.  The Default Branch in the Advanced Settings is set to use the 9.x branch.

**Comment by humitos** [comment]
There are some issues related to this one already: #1820 and #1802 

In this particular case, it does worth to mention that it's a `mkdocs` project.

**Comment by ba66e77** [comment]
Thanks for the response, @humitos. I looked at those before posting but, even though they have the same observed issue (the Edit on Github link is inaccurate), they don't seem directly relevant. We're not referencing a tag nor are we using git submodules.

**Comment by danepowell** [comment]
I think this is due to mkdocs' version of the readthedocs theme not supporting reading the active github_version: https://github.com/mkdocs/mkdocs/issues/1578

The fix is pretty simple, downstream projects just need to set `edit_uri` to be the correct path: https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/configuration.md#edit_uri

Obviously it would be ideal if this worked out of the box though, which is why I opened the upstream issue with mkdocs.
