### ISSUE TITLE
should readthedocs.yml have a pip version setting?

### ISSUE THREAD

**Issue by caganze** [rtfd/readthedocs.org#4500]
Hi,

This is the message that I get while trying to build
"You should consider upgrading via the 'pip install --upgrade pip' command", do I have control over this?

Thank you,

**Comment by RichardLitt** [comment]
I believe you should have control over this. Could you try running this command locally, and then seeing if the message comes up when you build again?

**Comment by stsewd** [comment]
The pip version comes from the docker image used to build the docs. See https://github.com/rtfd/readthedocs.org/issues/4127#issuecomment-391522520 (closing in favor of the other issue).

**Comment by ltalirz** [comment]
@stsewd I'm not sure (closed) issue #4127 really covers this issue.

For example, my problem is that I need pip >= 10 in order to build my package.
However, including `pip>=10` in the requirements.txt does not solve this issue, since the newer pip version is required already at install time (see [failed build here](https://readthedocs.org/projects/idea-code/builds/7761509/) ).

In essence, being able to specify the pip version would be a subset of what the [pyproject.toml](https://pip.pypa.io/en/stable/reference/pip/#pep-518-support) can do in pip >= 10.

Is there currently a way to upgrade pip before it tries installing the `requirements.txt`?

P.S. I tried wiping the environment as suggested in #4127 but this does not upgrade pip to >= 10.

**Comment by stsewd** [comment]
@ltalirz Currently there is no way to do that, we need to wait for the next release of the rtd docker image which should include a more recent version of pip.
