### ISSUE TITLE
mkdocs doesn't look in the root of the repo

### ISSUE THREAD

**Issue by AumitLeon** [rtfd/readthedocs.org#4507]
> When you choose Mkdocs as your Documentation Type, we will first look for a mkdocs.yml file in the root of your repository. If we don’t find one, we will generate one for you.

The above is not true. I had a project with `mkdocs.yml` in the root (along with relevant markdown files), and the build failed-- I was getting the same error referenced in #4231.

**Comment by stsewd** [comment]
A link to your rtd project and build would be helpful here, anyway, I think your issue was because of the `docs_dir` was at the same level of the `mkdocs.yml` file instead of a child directory, and btw, I think you mention that moving all inside docs solved the issue. It does, but we are not longer reading your `mkdocs.yml` file, but generating one for you in the root of your project.

**Comment by AumitLeon** [comment]
Ah, you are correct! Just tested this here: https://github.com/AumitLeon/module_starter_cli/pull/35
