### ISSUE TITLE
https error on custom domain

### ISSUE THREAD

**Issue by laserson** [rtfd/readthedocs.org#4511]
Hi RTD-folk,

We host our docs using a custom URL:

docs.airr-community.org

which corresponds to the `airr-standards` RTD project.

When I load

https://airr-standards.readthedocs.io

I can successfully load the page with https.

When I try to load our custom domain with https, we get

>This site is not secure
>
>This might mean that someone’s trying to fool you or steal any info you send to the server. You should close this site immediately.
>
>Details 
>The hostname in the website’s security certificate differs from the website you are trying to visit.
>Error Code: DLG_FLAGS_SEC_CERT_CN_INVALID
>
>One then gets a 403 Forbidden message from cloudflare (presumable the host for readthedocs).

We do not have any CAA records set.

```
$ dig docs.airr-community.org

; <<>> DiG 9.10.6 <<>> docs.airr-community.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63812
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;docs.airr-community.org.	IN	A

;; ANSWER SECTION:
docs.airr-community.org. 735	IN	CNAME	readthedocs.io.
readthedocs.io.		174	IN	A	104.18.231.122
readthedocs.io.		174	IN	A	104.18.227.122
readthedocs.io.		174	IN	A	104.18.230.122
readthedocs.io.		174	IN	A	104.18.228.122
readthedocs.io.		174	IN	A	104.18.229.122

;; Query time: 3 msec
;; SERVER: 10.5.132.10#53(10.5.132.10)
;; WHEN: Mon Aug 13 14:12:48 EDT 2018
;; MSG SIZE  rcvd: 160
```

My read of the RTD docs and issue #2652 is that this is theoretically supposed to just work. Any idea what is wrong? Do we need to configure something differently?

cc @bcorrie @javh

Thanks!

**Comment by davidfischer** [comment]
@laserson, please go to https://readthedocs.org/dashboard/airr-standards/domains/, edit your custom domain, and re-save it. This should re-request a new certificate for your domain.

When did you add this domain to Read the Docs? It looks like previous request timed-out and/or failed presumably because the DNS was recently changed. As a result, the certificate needs to be requested again. Editing the domain will do that. In our next deploy, we will be showing the certificate issuance status on that screen so this should be more obvious but I think adding a note to our docs would also be helpful.

**Comment by davidfischer** [comment]
I added some clarifications in #4514.

**Comment by laserson** [comment]
Looks like that worked.  Thanks!
