### ISSUE TITLE
Deprecate old /github, /bitbucket, /build endpoints

### ISSUE THREAD

**Issue by gjtorikian** [rtfd/readthedocs.org#4568]
Sorry @ericholscher, I should've reached out sooner, but it suddenly occurred to me: is the https://readthedocs.org/ integration into GitHub still using [GitHub Services](https://github.com/github/github-services/blob/a71f251994d146e43843b9e6659da87ecdb03a58/lib/services/read_the_docs.rb)? If so, services [are being deprecated](https://developer.github.com/changes/2018-04-25-github-services-deprecation/), and we suggest [migrating away](https://developer.github.com/v3/guides/replacing-github-services/) as soon as possible.

Please let me know if I can provide any more info or help!

**Comment by agjohnson** [comment]
Thanks for the heads up! We used GitHub services in the past, and there are likely a non-trivial number of projects still using the old service. However, if you sign up your project today, your project will get a webhook, not the service.

An easy path forward for us is to collect projects hitting the mostly deprecated `/github` endpoint and send a warning. We should:

- [ ] Collect projects as the `/github` endpoint is hit
- [ ] Use our notification backend to send site/email notifications for reconnecting project with a webhook integration
- [ ] Announce hard deprecation of old endpoints and GitHub service
- [ ] Also do the `/bitbucket` endpoint deprecation at the same time?
- [ ] Also do the generic endpoint deprecation at the same time?
- [ ] Maybe also implement payload signing on GitHub webhooks, because why not? Also, might as well make sure that new flood of projects on to modern webhooks are set up correctly, as this won't happen again anytime soon.

**Comment by humitos** [comment]
@agjohnson how are you thinking to collect these projects? our logs are not saved for too many days now.

Maybe creating a temporal model in the database and calling `get_or_create` on each `/github`, `/bitbucket`, `/build` and send an email notification every two weeks. After depreciation, we can just remove this model safely. What do you think?

This will cover most of your points. We will need to announce the deprecation (maybe a blog post?) and "signing webhook", but that's a completely different issue for me (I wrote some thoughts on corporate issue tracker, https://github.com/rtfd/readthedocs-corporate/issues/364, that maybe should be moved here)

**Comment by gjtorikian** [comment]
I pulled numbers for you all at one point (I work at GitHub) but forgot to share them. I think there was something like 27,000 users on the old services, with 24,000 of them being enabled (not active -- simply "turned on." I can't pull active numbers.)

I can grab the users and projects associated with the service, but I'm not sure if that's useful.

**Comment by agjohnson** [comment]
@humitos perhaps we don't even need a database to track this. our notification system should be able to deduplicate messages and only send one every 2 weeks. So on requests to the deprecated webhook endpoints, we create a notification for the project owners every two weeks.

@gjtorikian 24000 is way more than i would have guessed! it might help to have this information if it's not a pain to pull it. Feel free to move this conversation to a private channel -- anthony@readthedocs.com and if required, my public pgp is at https://github.com/agjohnson.gpg

If GitHub has announced this, I think announcing the deprecation on our side and alerting users with active deprecated webhooks might be enough.

**Comment by humitos** [comment]
@agjohnson I will write some code today for your idea around notifications.

**Comment by humitos** [comment]
> @humitos perhaps we don't even need a database to track this. our notification system should be able to deduplicate messages and only send one every 2 weeks. So on requests to the deprecated webhook endpoints, we create a notification for the project owners every two weeks.

I'm not seeing this clearly because we have 2 different types of notifications: `site` and `email`. Site allows deduplication since it uses the message storage, but `email` send the email immediately when `.send()` is called and the notification is not saved anywhere to be recovered from a Celery task later.

I opened #4898 to discuss over the code proposed.
