### ISSUE TITLE
Trying to gain access to doctrine.readthedocs.io

### ISSUE THREAD

**Issue by jwage** [rtfd/readthedocs.org#4619]
## Details

* Read the Docs project URL: https://doctrine.readthedocs.io/
* Build URL (if applicable): 
* Read the Docs username (if applicable): jwage

Hi, I am with the Doctrine project (https://github.com/doctrine), we recently changed the way our website and documentation works and I am trying to regain access to doctrine.readthedocs.io.

I am pretty sure I am the one that set it up, but it has been several years and I can't figure out how to get access in order to shut it down. What can I do?

Thanks, Jon

**Comment by davidfischer** [comment]
If I look at the [project page](https://readthedocs.org/projects/doctrine/), it appears to be setup by [somebody else](https://readthedocs.org/profiles/dominics/). Do you know this person? If so, you can contact them and ask them to add you as a co-maintainer or delete the project or whatever. If not, I can contact them and point them to this ticket.

In general, we follow the process in our docs for [abandoned projects](https://docs.readthedocs.io/en/latest/abandoned-projects.html)

**Comment by jwage** [comment]
Hmm, I do not know that person and they aren't affiliated with Doctrine. It looks like they set it up recently. I guess there is nothing stopping someone from setting this up and using our documentation source. But the problem is, people are searching in Google and ending up there instead of on our website domain where we have the same documentation and we're trying to improve our SEO so developers can find what they are looking for.

**Comment by davidfischer** [comment]
I contacted the user and requested that they either grant you access or delete the project.

**Comment by RichardLitt** [comment]
@davidfischer Would a "remindme" bot help you come back to this easier in six weeks?

**Comment by davidfischer** [comment]
I suppose it would

**Comment by davidfischer** [comment]
That sounds like a design decision that should involve more than just myself. I'll ask the team about their thoughts.

**Comment by dominics** [comment]
Hi @jwage, long time follower.

> Hmm, I do not know that person and they aren't affiliated with Doctrine.

Yup, that's true.

> It looks like they set it up recently. 

I set this up in 2012. 

I set it up after the Doctrine 1.2 documentation was completely removed from the website after the launch of 2.0, when plenty of people were still stuck on Symfony 1.4 without an upgrade path. In order to set it up, I had to convert the entire 1.2 documentation to restructured text.

My work was later merged back in under the @doctrine org on Github (see https://github.com/doctrine/doctrine1-documentation/commits/master?after=abcba0f9087dc7d4e3c4a01029db1226762a28c0+69)

> I guess there is nothing stopping someone from setting this up and using our documentation source.

I wasn't intending to squat on the name; at the time, 2.x was still going by `doctrine2` (a la `symfony2`), and you can see the project name of this on RTD is `doctrine1`.

> on our website domain where we have the same documentation

Yep, _now_. After I set this up. Like I said, at the time, the Doctrine 1.2 documentation was abandoned (kinda fair enough given how much trouble it was to convert to rST) and not served anywhere.

> we're trying to improve our SEO so developers can find what they are looking for

Happy to help. Adding you as an admin now (after which I'm happy if I'm removed as an admin - but it looks like you'll have to do that @jwage). I'd just ask that the 1.2 documentation remain accessible _somewhere_.

**Comment by jwage** [comment]
Hi @dominics, no problem. I am happy you kept the doctrine1 docs going when we did not. Thank you!

I have the doctrine1 docs rendering now on the new website and I will continue to maintain it there. https://www.doctrine-project.org/projects/doctrine1/en/latest/index.html

Thanks for your help!

**Comment by stsewd** [comment]
@jwage can we close this, then?

**Comment by jwage** [comment]
Yes. Thanks!
