### ISSUE TITLE
A configuration file was not found (after 2.6.6 update)

### ISSUE THREAD

**Issue by nikolay-bushkov** [rtfd/readthedocs.org#4668]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/deeppavlov
* Build URL (if applicable): https://readthedocs.org/projects/deeppavlov/builds/7851428/
* Read the Docs username (if applicable): same as here.

## Expected Result

Successful build.

## Actual Result

Build failed even in the branch that was not updated. It seems that update to 2.6.6 break it. Any ideas how to fix it?

**Comment by sobolevn** [comment]
I have also seen this error for several project.

I have also tried to specify config file manually in "Advanced settings", but it did not work.
I hope to see a patch! 🙏

**Comment by stsewd** [comment]
I'm going to look at this now

**Comment by williamfgc** [comment]
I have the same problem since this morning: https://readthedocs.org/projects/adios2-adaptable-io-system-version-2/builds/7852603/

**Comment by stsewd** [comment]
Ok, I found the problem (with @nikolay-bushkov's project at least). What happens if that you have a `.readthedocs.yml` file inside your `docs` dir instead of the root of your project (as the docs recommend https://docs.readthedocs.io/en/latest/yaml-config.html). This was working in the past because we try to find a rtd config in the whole project internally, and we didn't use this value to get the absolute path of the conf.py file, but we are changing some stuff to bring a v2 of the config file, and now we are using that value.

Not sure if we want to allow that (`.readthedos.yml` file inside a dir). So, I going to ask the to team if this should be treated like a bug or something else.

**Comment by stsewd** [comment]
@sobolevn can you share your rtd project? Or see if your case is the same as above ^

**Comment by stsewd** [comment]
@williamfgc your case is the same as above https://github.com/ornladios/ADIOS2/blob/master/thirdparty/pybind11/pybind11/.readthedocs.yml

**Comment by stsewd** [comment]
You can solve this by moving your `readthedocs.yml` file at the root of your project.

**Comment by williamfgc** [comment]
@stsewd Thanks for your help! I thought the build was restricted to ./docs/ that yml file is under thridparty. Can I set up a filter?

**Comment by williamfgc** [comment]
@stsewd yeah, I looked into the docs and I couldn't find anything related. IT could be a useful feature. For example, if we have two projects (user_guide, developers_guide) under the same repo, or like in my case if we depend on thirdparty that must not be modified? Since those are common scenarios, what's the best practice?

**Comment by stsewd** [comment]
So, we decide that we don't want to support this behaviour (and looks like it doesn't match our docs anyway). So, if moving the config file to the project's root solve this, we can close this issue, I'll open a new one to track the deletion of the logic that finds config files inside other directories.

**Comment by stsewd** [comment]
>  IT could be a useful feature. For example, if we have two projects (user_guide, developers_guide) under the same repo

I think there are some ideas about having multiple configurations, but I don't think we are going to support that. As we will need to need to find a way to choose which project to run. This is the more close thing that we are going to support https://github.com/rtfd/readthedocs.org/issues/4354#issuecomment-422911487. Also, I think rtd is designed for one documentation per repo.

**Comment by stsewd** [comment]
> like in my case if we depend on thirdparty that must not be modified? 

We are going to remove the finding logic, so that should fix that case.

**Comment by williamfgc** [comment]
@stsewd great! Thanks! Keep up with the great work in rtd!

**Comment by stsewd** [comment]
Just in case, a workaround is creating your own `.readthedocs.yml` file in the root of your project.

**Comment by williamfgc** [comment]
@stsewd adding .readthedocs.yml solved our issue. Thanks!
