### ISSUE TITLE
Design around multiple configurations in one file

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#4705]
Related code https://github.com/rtfd/readthedocs.org/blob/a98441717ea50b19fe6bb0f1ea52df092dbc8190/readthedocs/config/config.py#L988-L988

I'm not sure what use case has. Maybe a monorepo? But still, rtd doesn't support that workflow (more the one doc per project).

**Comment by agjohnson** [comment]
I'm +1 on getting rid of the logic that searches for a readthedocs.yml file. I think we should only support one top-level config file, all of the other UX patterns are weird.

* Config in some other directory: why not just put it top level?
* Multiple configs: which one are we supposed to use?
* Config in submodule or something: why would you want to use it?

**Comment by stsewd** [comment]
Oops, I think I put the wrong title here, for multiple configurations files the issue is #4669. This is for a configuration file with multiple configurations (yaml support having a top level dict)

**Comment by humitos** [comment]
@stsewd I found this issue a bit confusing. Can you expand on the purpose of it and what it's needed to do/decide here?

**Comment by humitos** [comment]
I see...

So,

> But still, rtd doesn't support that workflow (more the one doc per project).

RTD does not support more than one doc per project, but if the repository has multiple translations the use will import the same repo many times as different (sub)projects. In that case, we may want to allow:

1. multiple YAML files
2. multiple configs on the same YAML file
3. none of the above and force to build all the projects with the same YAML since the only thing that should change on each different translation are the `.po` files.

I'm mentioning 3) even though it's not a problem in that particular case, but as an example that it _could_ be useful in some weird case, maybe.

At first, it seems we could kill that code.

**Comment by agjohnson** [comment]
I think our translations workflow needs to be ripped apart eventually. Adding a translation should not require a separate file on the repo. However, currently, you shouldn't need a separate config file for this, the language selector is in the admin UI.

We've discussed in other tickets, but translations will eventually just be another project setting (ie, just enable "Español" translation to your project like you do versions, not add a separate project).

I'm still -1 on multiple config files I think, this is in line with other services like travis and circleci

**Comment by ericholscher** [comment]
+1 on removing multiple configs in a single file. I don't see any use-case for this. I _do_ see value in being able to do something like defining multiple translations for a project, but I don't think having totally different configs in a single file make sense for that currently.
