### ISSUE TITLE
request for increased build time for project oapackage

### ISSUE THREAD

**Issue by eendebakpt** [rtfd/readthedocs.org#4757]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/oapackage/
* Build URL (if applicable): https://readthedocs.org/projects/oapackage/builds/7937692/
* Read the Docs username (if applicable): eendebakpt

https://readthedocs.org/projects/oapackage/builds/7937692/

## Expected Result

The build should have completed succesfully.

## Actual Result

A timeout error was generated.

The package uses conda (because swig is required) and takes some additional time because a C++ extension is build. Mocking the C++ extensions works in reduce the build time, but then the C++ functions are not properly documented. (See https://github.com/rtfd/readthedocs.org/issues/4443)

Can the build time for this package be increased?

**Comment by humitos** [comment]
@eendebakpt I just increased the time for building your project's docs. Let's see how it behaves. It should be enough now.

**Comment by peendebak** [comment]
@humitos Thanks for increasing the build time. Conda now installs properly, but I get a message `Command killed due to excessive memory consumption`. Can you also increase the memory limit? 

https://readthedocs.org/projects/oapackage/builds/7942643/

There are no error details, so I cannot see exactly where in the installation the error is generated.

**Comment by humitos** [comment]
@peendebak I increase the mem limit also and the build passed.

Please, consider reading this guide and reduce the formats that you are building since all of them are not strictly necessary to help Read the Docs servers to not collapse: https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html

Thanks. Much appreciated.

**Comment by eendebakpt** [comment]
@humitos Thanks for increasing the limits. My documentation is building fine now!
