### ISSUE TITLE
readthedocs.yaml not respecting requirements_file directive

### ISSUE THREAD

**Issue by feuGeneA** [rtfd/readthedocs.org#4807]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/0x-order-utils/
* Build URL (if applicable): (multiple, see below)
* Read the Docs username (if applicable): feuGeneA

I have two requirements, and they seem to be supported independently, but not together.

One requirement is that my docs be built from a folder that's deep within my repo source (specifically, `python-projects/order_utils/setup.py`).  For this I can use a requirements.txt file, and if I specify that file in Admin, Advanced settings, then the build will properly find my project.

The other requirement is that my setup.py demands Python >= 3.6.  To work with this, I've put in place a `readthedocs.yaml` file, specifying `python: version: 3.6`, and it does indeed use that version of the interpreter.

However, mixing these two together does not work.  The crux of my problem seems to be that the build isn't using the `requirements_file` specified in my `readthedocs.yaml`.

However, combining these two approaches does not work.

## Expected Result

A build using the interpreter and requirements file specified in `readthedocs.yaml`.

### Using a requirements file but no `readthedocs.yaml`
```
Processing ./python-packages/order_utils
0x-order-utils requires Python '>=3.6, <4' but the running Python is 3.5.2
You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
https://readthedocs.org/projects/0x-order-utils/builds/7994051/
This shows that my requirements file works.

### Using a `readthedocs.yaml` without specifying a `requirements_file`
```
Using base prefix '/home/docs/.pyenv/versions/3.6.2'
...
python: can't open file 'setup.py': [Errno 2] No such file or directory
```
https://readthedocs.org/projects/0x-order-utils/builds/7994020/
This build shows that my `readthedocs.yaml` file is getting me the interpreter I need, but of course it doesn't know how to find my `setup.py`.

### Using a readthedocs.yaml that specifies a `requirements_file`
```
Using base prefix '/home/docs/.pyenv/versions/3.6.2'
...
python: can't open file 'setup.py': [Errno 2] No such file or directory
```
https://readthedocs.org/projects/0x-order-utils/builds/7994617/
This build shows that, even though `readthedocs.yaml` contains `requirements_file: requirements.readthedocs.txt`, the behavior is the same as when it doesn't contain that directive.

**Comment by stsewd** [comment]
`requirements_file` is to indicate a requirements file only, it doesn't mean to change the working directory. But I think your problem is solved, this is from your build https://readthedocs.org/projects/0x-order-utils/builds/7994617

![screenshot_2018-10-24 0x-order-utils read the docs](https://user-images.githubusercontent.com/4975310/47454547-1a87b380-d795-11e8-9a80-6f9dc0a44fbf.png)

As you can see, rtd is installing your requirements file, the next step is falling because you have checked the `install project` option in your dashboard (can you please check that?). RTD combines both, options from the web and from the configuration file.

Also, soon you can install a `setup.py` from any path https://github.com/rtfd/readthedocs.org/pull/4740

**Comment by feuGeneA** [comment]
@stsewd Thank you for the :star2:stellar:star2: support!  I've got everything working great now.
