### ISSUE TITLE
Conda crashes with error 247

### ISSUE THREAD

**Issue by hydrogo** [rtfd/readthedocs.org#4812]
## Details

* Read the Docs project URL:
http://rainymotion.readthedocs.io
* Build URL (if applicable):
https://readthedocs.org/projects/rainymotion/builds/8004144/
* Read the Docs username (if applicable):
@hydrogo

## Expected Result

Should just install the conda environment and make the documentation

## Actual Result

it crashes with error code 247

## Comments

I think that I have the same problem as already has been mentioned in #4447. It is difficult to migrate from `conda` to `pip` requirements file in my project mainly because I am using OpenCV. I also use only one channel `conda-forge` for every package I want to install.

Previously everything was fine, but today I decided to add *ONLY* one additional sentence with a valid reference to our paper in index.rst, and it broke the system :-(

**Comment by stsewd** [comment]
Can you please point me to the new package that was installed? Maybe the new package is causing the build time or memory limit to exceed

**Comment by humitos** [comment]
Following all the path down in #4447 you will arrive to a conda issue itself: https://github.com/conda/conda/issues/5003 

We depend on them to solve this issue of "eating memory". The server just kills the docker container because it's growing on memory a lot.

There is not too much we can do from our side.

I suggest you to subscribe to that issue and we should probably close this one here.

**Comment by hydrogo** [comment]
@stsewd sorry for misunderstanding, I didn't install the new package/packages, just added one row with additional package description to the main .rst file.
