### ISSUE TITLE
Yet another issue about submodules

### ISSUE THREAD

**Issue by bluecmd** [rtfd/readthedocs.org#4865]
Hi,

Project: `u-bmc`
Error: https://readthedocs.org/projects/u-bmc/builds/8054931/

u-bmc uses submodules quite heavily and contains *a lot* of data. There is no earthly reason for readthedocs to check that out and I'd like to disable it.

I found some PRs and some other issues that talks about how this is possible, but I did not see any documentation about how to enable it for my own repo. Am I correct in assuming that:

1. There is a secret internal tag you set on projects for now to disable submodules?
1. There will be support in the upcoming v2 configuration, but there is not in the current v1?

If so, could I ask for the secret flag on u-bmc?
Thanks!

**Comment by stsewd** [comment]
both, 1 and 2 are true. but I think there is something else causing the error, I'll investigate now

**Comment by bluecmd** [comment]
Sure thing! The build time has the suspicious number of 899 seconds, and I read you have a 900 seconds timeout, so if you start a betting pool you know where my bet is ;-).

**Comment by stsewd** [comment]
So, yeah, it's failing on `git submodule update --init --force --recursive u-boot linux`

**Comment by bluecmd** [comment]
Hi again,

Just making sure this didn't fall between the metaphorical chairs. @stsewd , what's the next steps here?

**Comment by stsewd** [comment]
Sorry, I almost forgot, not sure what to do here, but I'll ask the team. Some possibilities could be:

- Wait to release config v2 (probably not the best solution because of the time)
- Set a flag to use the _alfa_ version of v2 (which include submodules settings, but the schema is open to changes, so you'll need to change that on the final release, and we don't have deployed docs)
- Set the current magical flag (we are trying to not abuse of this because v2 is coming soon)

**Comment by agjohnson** [comment]
:+1: on just setting the feature flag for now, if you don't need any of the submodules for the project.

**Comment by bluecmd** [comment]
Sgtm! The submodules are just for building.

**Comment by humitos** [comment]
@bluecmd I added the flag to skip submodules checkout to your project.

I'm closing this issue here, but feel free to reopen if it doesn't work as you expected or give us feedback/update ;)

Thanks!
