### ISSUE TITLE
Multiple Builds per Merge, One per Tag

### ISSUE THREAD

**Issue by ax3l** [rtfd/readthedocs.org#4917]
## Details

* Read the Docs project URL: http://picongpu.readthedocs.io/
* Build URL: https://readthedocs.org/projects/picongpu/builds/
* Repo URL: https://github.com/ComputationalRadiationPhysics/picongpu/
* Read the Docs username: as as on GitHub

## Problem Description

I somehow have the feeling that I ill-configured my project.
Each merge commit is somehow build four times - is that correct?

When I push a tag it only shows up as one build, so I fear I am wasting precious resources. The "single tag build" (including pdf, html, epub) seems to produce all three from one build successfully.

Maybe I somehow double/quadruple trigger builds via the GitHub WebAPI, my `.yaml` file or the project settings in readthedocs.org ...

## Other

Looks similar to #2775. Following [this comment](https://github.com/rtfd/readthedocs.org/issues/3255#issuecomment-373564346) some kind of service might be still on triggering this, but where do remove it? On readthedocs.org or in GitHub.com ? :)

**Comment by humitos** [comment]
Please, check if your project has the GitHub service enabled at https://github.com/ComputationalRadiationPhysics/picongpu/settings/installations. If there is a Read the Docs service there, please remove it since it's deprecated.

Also, go to https://github.com/ComputationalRadiationPhysics/picongpu/settings/hooks and check how many webhooks do you have for Read the Docs (you should have only one there).

**Comment by ax3l** [comment]
Thank you very much for the help. I still had the old service enabled, hooks are at one.
