### ISSUE TITLE
Lots of off-domain references for underlying content

### ISSUE THREAD

**Issue by smontanaro** [rtfd/readthedocs.org#4971]
At my place of employment, most off-site websites need to be whitelisted for access. I recently got *.readthedocs.io and readthedocs.org so enabled. From the spot checks I made, the individual package docs in the readthedocs.io domain work great (they should be mostly self-contained I think), but display of readthedocs.org is suboptimal. Looking at the Sources tab in Chrome, I see references to a bunch of domains I don't recognize. The Network tab shows a number of CSS, JS abd PNG files which failed to load. The main (only?) source of these failures is the rather obscure rtdcommunitypublic.blob.core.windows.net host. Without knowing more, I'd feel quite uncomfortable asking for any of the source domains to be whitelisted. (Still, it does appear to be part of the Microsoft menagerie, so perhaps it's ok.)

While I understand your desire to minimize code duplication, it seems like core usability features of readthedocs.org should all be served from that domain.

**Comment by agjohnson** [comment]
They aren't, due to our infrastructure.  The rtfcommunitypublic url is correct and is a core part of Azure file storage serving. These requests reference assets.readthedocs.org, and there are requests to media.readthedocs.org as well.

Closing this as we won't be changing this and it's not really a bug with RTD.
