### ISSUE TITLE
Remove the `LOCAL_GIT_BRANCHES` setting

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs.org#4985]
We introduced this here to make tests work, but it isn't how things work in production: https://github.com/rtfd/readthedocs.org/pull/4984

We should remove this setting, and make our tests work properly with remote repos. I see a couple ways we could handle this:

* The `make_get_branch` function could manipulate the git repo so that it has a *remote* branch instead of a local branch
* We could mock `repo.branches` in the places we use it. I went down this road briefly, but it was a little bit complex.

I think the first approach is best, but I'm not sure how to do it easily.

**Comment by humitos** [comment]
> I think the first approach is best, but I'm not sure how to do it easily.

We should follow the same workflow that we do in production:

1. The repository is created by another person with all its branches: we can create a temporal repository
1. We clone it from there (localhost)
1. We start running our test over the cloned one instead of the originally created

That way, I suppose that branches will be remotes and the structure of the repository will be pretty similar to what we have in production.

**Comment by stsewd** [comment]
There are some tests that use the clone step, I guess we only need to put that step in our tests
