### ISSUE TITLE
jQuery 2.0.3 has an XSS vulnerability

### ISSUE THREAD

**Issue by remyabel** [rtfd/readthedocs.org#4999]
## Details

* Read the Docs project URL: Any project hosted on RTD, i.e https://bootstrap-datepicker.readthedocs.io/en/latest/
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

Upgrade to jQuery 3.0, or backport the [fix](https://github.com/jquery/jquery/pull/2588)

## Actual Result

RTD uses vulnerable jQuery. See this [issue](https://github.com/jquery/jquery/issues/2432) for background information

**N.B.**: this doesn't affect sites which use the `sphinx_rtd_theme`, only projects hosted on RTD itself.

**Comment by davidfischer** [comment]
Thanks for reporting this. I confirmed that this is an issue on RTD. I'm looking into whether we are going to backport or upgrade and I'll update this issue in the next day with more information.

**Comment by davidfischer** [comment]
I think we are going to take a two pronged approach to resolving this issue. Firstly, we will backport the fix into our hosted `jquery-2.0.3.min.js`. Secondly, new doc builds will no longer use this file and instead will use the version of jquery is bundled with Sphinx (https://github.com/rtfd/readthedocs-sphinx-ext/pull/52).

By default, RTD uses a modern version of sphinx which uses jQuery 3.2.1. We will start to raise warnings to people explicitly building with versions of sphinx using vulnerable versions of jquery (Sphinx 1.4 and before) and at a later date raise an error instead of a warning.

I expect this to be done in the next couple days.

**Comment by remyabel** [comment]
Thanks. Nice response time and nice fixes.

**Comment by ericholscher** [comment]
This is now deployed. 👍
