### ISSUE TITLE
Segfault on a significant percentage of conda installs

### ISSUE THREAD

**Issue by goerz** [rtfd/readthedocs.org#5014]
For a significant number of builds (somewhere between 10-30% would be my estimate), builds that use `conda` fail with a segfault. Example: https://readthedocs.org/projects/weylchamber/builds/8294985/

I'm seeing the same behavior across all my projects.

**Comment by stsewd** [comment]
Conda is very heavy (consumes a lot of memory and time), there isn't much we can do. Same issue as https://github.com/rtfd/readthedocs.org/issues/4574

**Comment by msarahan** [comment]
Hi, I'm one of the conda maintainers. Sorry for the headache. The place where this failed is a strange place to run out of memory. At that point, it looks like it is just doing the final copying of files. We'll look into it and hopefully reduce the memory consumed by conda.

We are in the early stages of monitoring performance and memory usage using air speed velocity. Our benchmarks are at https://conda.github.io/conda-benchmarks/

None of those benchmarks run the part where the crash is reported here, because we had assumed it is just dial operations and not terribly interesting to benchmark. I think we will add that part in.

**Comment by stsewd** [comment]
@msarahan those are great news! thanks!
