### ISSUE TITLE
Add `--pre` option to pip install

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#5018]
Pip by default only finds stable releases https://packaging.python.org/tutorials/installing-packages/#installing-prereleases

We can support packages with pre-releases only by adding the `--pre` option, we could add this as an option for the config file.

Not sure how many users could face this, or if there is a workaround and avoid the `--pre` option.

More background at https://github.com/rtfd/readthedocs.org/issues/5016

**Comment by jezdez** [comment]
@stsewd I'd be interested in helping to implement this and would argue it's a feature that should be implemented as a new column in the Project model. Unless there are plans to deprecate that model in favor of the config file?

Either way, adding the ability to define the --pre option in the config file makes sense to me (additionally) since it's also possible to configure the requirements file there. What do you say?

**Comment by humitos** [comment]
I personally don't think we should put effort on this issue. I think this issue is off from our roadmap at this moment.

Also, I think this won't affect too many users but I'd like to hear more from users with this needing and in that case we should reconsider implementing this option. Otherwise, I'd close it.

**Comment by jezdez** [comment]
Yep, I have a project that needs this for a dependency that has no final release yet ([black](https://black.readthedocs.io/)). I'd argue that not providing the ability to install pre-releases (e.g. beta releases) is more critical than just an edge case ever since pip has decided to not install those by default.

**Comment by humitos** [comment]
@jezdez can you point us your Read the Docs project that depends on `black` to build the docs?

**Comment by jezdez** [comment]
@humitos Sure, https://atmo.readthedocs.io/

**Comment by humitos** [comment]
@jezdez you project is installing `requirements/tests.txt` instead of `requirements/docs.txt`. I think that's the main reason.

On the other hand, I don't understand why black (a linter) would be needed to build documentation.

**Comment by humitos** [comment]
> @jezdez you project is installing `requirements/tests.txt` instead of `requirements/docs.txt`. I think that's the main reason.

Actually, it's `requirements/all.txt`

**Comment by stsewd** [comment]
We decide that adding more flags is not a solution for all this cases. A better solution would be #1083
