### ISSUE TITLE
Increase name and path's max_lenght for ImportedFile model

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#5061]
Some projects have some large filenames/nested directories.

https://github.com/rtfd/readthedocs.org/blob/ae991c4f131e2dd22fd4ce61deec381ae33f3aa4/readthedocs/projects/models.py#L895-L897

Any reason to not do that? Any suggested number? (In sentry the length of the failed file was 256).

Related sentry issue https://sentry.io/read-the-docs/readthedocs-org/issues/659636695/

**Comment by humitos** [comment]
We need to put a number here. So, in case we want to fully support this we should the maximum values for the filesystem that we use (ext4)

> Linux has a maximum filename length of 255 characters for most filesystems (including EXT4), and a maximum path of 4096 characters.

https://unix.stackexchange.com/questions/32795/what-is-the-maximum-allowed-filename-and-folder-size-with-ecryptfs

There are cases where it fails because of the `path` and not the `name` length: https://sentry.io/read-the-docs/readthedocs-org/issues/659636695/events/89c15864ee9c4a33bf05ad764e0c2869/

```
>>> len('glotaran.models.spectral_temporal.spectral_temporal_dataset_descriptor.SpectralTemporalDatasetDescriptor.validate_parameter.rst.txt')
131
>>> len('/home/docs/checkouts/readthedocs.org/user_builds/glotaran/rtd-builds/latest/_sources/api/models/spectral_temporal/spectral_temporal_dataset_descriptor/classes/SpectralTemporalDatasetDescriptor/methods/glotaran.models.spectral_temporal.spectral_temporal_dataset_descriptor.SpectralTemporalDatasetDescriptor.validate_parameter.rst.txt')
332
```

I think we should increase `path` to 4096 to avoid this problem and be safe.
