### ISSUE TITLE
cider.readthedocs.io is not building

### ISSUE THREAD

**Issue by bbatsov** [rtfd/readthedocs.org#5079]
Today I noticed that https://cider.readthedocs.io/en/latest/ hasn't been updated in a while. I don't see any failed builds, so I can't debug the problem myself and I'd appreciate some with it.

**Comment by humitos** [comment]
Hi @bbatsov! How much time do you mean by "in a while"? The last build was 2 weeks ago. Are the docs from the repository newer than that?

Also, I do see in your repo that you have a commit "a day ago" and no build was triggered. So, I suppose your project is configured to use Github Services (can you please confirm this?), which are deprecated and this week the service is completely stopped.

>  January 7th, 2019: GitHub Services will be suspended for a full 7 days. Regular deliveries will resume January 14th, 2019.

https://developer.github.com/changes/2018-11-05-github-services-brownout/

We have a PR #4898 to notify these users with the instructions about how to proceed.

**Comment by bbatsov** [comment]
Yeah, you're right. I guess I'll have to check the new instructions then.

**Comment by stsewd** [comment]
You need to create a new webhook https://docs.readthedocs.io/en/latest/webhooks.html#github. Let us know if you have any problems, closing for now.

**Comment by humitos** [comment]
@stsewd I don't want to close this issue just yet because we are deprecating those endpoints and I'd like to get more feedback from the user regarding the steps that had to follow and if they did work or not.

On the other hand, I'm not 100% sure that this is the exact problem since they [have a commit 4 days ago](https://github.com/clojure-emacs/cider/commit/28a51bc3c028cd153aa241d1470dd46202acccd3) that didn't trigger a build for some reason.

@bbatsov I double check your builds project and I saw that there some new builds now: ~2hs ago and ~5m ago. Did you trigger manually or did you set up the webhooks following the guide? Was it accurate or you have to change something in the flow?

**Comment by bbatsov** [comment]
I just setup the webhooks. The instructions were accurate.  We can safely close this issue.
