### ISSUE TITLE
Tag named "latest" can conflict with RTD "latest"

### ISSUE THREAD

**Issue by metalivedev** [rtfd/readthedocs.org#534]
I found that our repo was stuck on an old version because we had a tag named "latest"

**Comment by agjohnson** [comment]
Agreed. However if we do accept a `latest` version, we should probably have a method for reverting the `latest` version as we originally saw it -- a branch -- to our automatic increment `latest` version.

**Comment by humitos** [comment]
I see two different ideas here:

1. suggest the user that `latest` tag/branch is incompatible with RTD and won't make RTD work properly
1. give the user the ability to choose if he/she wants to use the `latest` from his/her repository or the auto-created by RTD

Which one is the best one? or both?

**Comment by humitos** [comment]
From my understanding this is happening because we don't remove the `Version` instances that are not matching to a branch/tag.

So, if the original branch was called `latest` we create a `Version` instance with the attribute `machine=False` (which means that this is not a version automatically created by RTD). Then, if you remove the branch from the git repository, we don't remove&create that `Versions` with the `machine=True` and it gets stuck in an inconsistent state.

There are a similar issue regarding not deleting/syncing the `Version` properly under https://github.com/rtfd/readthedocs.org/issues/3887 with more information about this.

**Comment by humitos** [comment]
@stsewd does the fix that we talked the other day will fix this problem also, right? (we do have those 2 special cases to consider in the sync method: `stable` and `latest`)

If you haven't done yet, could you add a test case for the `latest` case also in #3887? Thanks.

**Comment by stsewd** [comment]
@humitos yeah, I think this is the same bug

**Comment by stsewd** [comment]
Closing in favor of https://github.com/rtfd/readthedocs.org/issues/3887
