### ISSUE TITLE
Request to increase memory limits for project fireworks-ml

### ISSUE THREAD

**Issue by smk508** [rtfd/readthedocs.org#5516]
## Details

* Read the Docs project URL: fireworks.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/fireworks/builds/8791197/
* Read the Docs username (if applicable): smk508

## Expected Result

Documentation build.

## Actual Result

The build gets cancelled because of excessive memory consumption. This always happens when it tries to pip install torch (pytorch). I have found that even if I make torch the only thing in requirements.txt, this error occurs. I don't know of any way around this because this one package that my project relies on seems to overload the memory.

Build output:

Collecting torch>=0.1.0.post2 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/7a/24/260f228857c652b58ee6f3ff7cacc9d987cea776a1ece6b76d794dcb7058/torch-1.0.1.post2-cp37-cp37m-manylinux1_x86_64.whl (582.5MB)
Killed

Command killed due to excessive memory consumption

**Comment by stsewd** [comment]
Do you really need pytorch to build your docs?

**Comment by smk508** [comment]
I need pytorch to build the package itself, and without that, the autodoc functionality doesn't work. The documentation that I currently have is generated by not having anything in my doc-requirements.txt; this generates everything except for the detailed API reference automodule stuff because it can't import the package itself.
If there's a way to get automodule to work without this issue, then I wouldn't need these build requirements.

**Comment by humitos** [comment]
I had to increase the memory to 2g, which I don't really like because it may break other builds running in the same server.

PyTorch being crazy about memory consumption is not a Read the Docs problem, but I'd like to have a general solution for this situations.

It's known in the PyTorch community this problem:

* https://discuss.pytorch.org/t/out-of-memory-error-with-pytorch-installation/18734
* https://github.com/pytorch/pytorch/issues/6504

We may get some ideas from there.

BTW, @smk508 you build is failing for a different reason now.

**Comment by smk508** [comment]
Hey humitos, 

Thanks for helping out with this. I reran the build and it's still failing with memory error.

**Comment by humitos** [comment]
@smk508 how much memory does `pytorch` require to be installed?

**Comment by smk508** [comment]
I'm not sure. The package itself is 582 MB from PyPi.

**Comment by smk508** [comment]
Hi guys,

I think when you increased the memory limit, you did so for the development branch. That one builds just fine, meaning that 2G of RAM is sufficient. Would it be possible to do that for the master branch of my project so I can have documentation for that?

Thanks

**Comment by humitos** [comment]
@smk508 hi! The increase affect all your branches. Actually, `latest` and `development` are passing properly.

What's the problem that you are experiment?

**Comment by smk508** [comment]
master branch still doesn't build. It gives the same excessive memory consumption error. I temporarily mapped latest to development because of this.

**Comment by stsewd** [comment]
Do you have some substantial changes in master that makes the docs more _heavy_?

**Comment by smk508** [comment]
No, it's currently the same as development branch.

**Comment by humitos** [comment]
Hi @smk508! I increased the memory to 3g (which is crazy to build docs) and I'm still seeing problems when installing `torch`.

`master` branch passed, but `development` and `latest` failed when installing `torch`. So, I'm not sure what it's doing when installing it since it does not behave in the same way on multiples runs.

Also, I created a sample project at (https://test-builds.readthedocs.io/en/install-pytorch/) and it built with just 2g :man_shrugging: 

I think there is not too much we can do and this problem should probably be reported to the PyTorch people, I guess.

> I will leave your project with 3.5g of memory as a test, but I'm not sure and can't guarantee that we can keep it in that way (`latest` and `development` passed this way)

I'm closing this issue because there is no action that we can take at the moment. Feel free to reopen or comment with any other potential solution.
