### ISSUE TITLE
Build fail error

### ISSUE THREAD

**Issue by EDI-N** [rtfd/readthedocs.org#5555]
> ### Build failed without any reason
> 
> Every RTD projects worked ok and yesterday without any **changes_what_can_provide_"fail"** I got **Build fail**. A lot of time I try to fix text/config.... nothing helped, so I think: "ok, happend" and clone wittingly good code from
> https://readthedocs.org/projects/edi-n/
> to
> https://readthedocs.org/projects/for-test/ and got **Build failed**
> ### Reproducible Project
> 
> projects with errors:
> https://readthedocs.org/projects/for-test/
> &
> https://readthedocs.org/projects/icona/
> #### Error Logs/Results
> 
> https://readthedocs.org/projects/for-test/builds/8834547/
> #### Expected Results
> 
> Build completed
> ### Environment Info
> 
>     * Python Version: 2.x
> 
>     * Sphinx Version:
> 
>     * RTD Theme Version:

**Comment by humitos** [comment]
Hi, the build that you mentioned here failed because there are some Unicode characters in the documentation and `pdflatex` fails because it's not well supported.

You may need to use another latex engine, like `xelatex` for example.

Check out this guide: https://docs.readthedocs.io/en/latest/guides/pdf-non-ascii-languages.html

Let me know if that helps.

**Comment by EDI-N** [comment]
Hi, sorry for long time respond: I add new settings ``latex_engine = 'xelatex'``` to **conf.py** file (https://github.com/EDI-N/Test/blob/rock/docs/source/conf.py) and nothing happend - got same error:
https://readthedocs.org/projects/for-test/builds/8858534/
What should I do to fix ```preloaded format=pdflatex```?

**Comment by humitos** [comment]
Hi @EDI-N! I enabled the feature flag mentioned in the guide I linked to your project and now it's building with `xelatex`. See the build at https://readthedocs.org/projects/for-test/builds/8859142/

You will need to adapt the font since it's not properly defined, though.

```
! Package polyglossia Error: The current roman font does not contain the Cyrill
ic script!
(polyglossia)                Please define \cyrillicfont with \newfontfamily.
```

I'm closing this issue. Let me know if you have any further question. Thanks!
