### ISSUE TITLE
Account inactive

### ISSUE THREAD

**Issue by cbleek** [rtfd/readthedocs.org#5652]
## Details

* Read the Docs project URL: https://yawik.readthedocs.io/en/latest/
* Read the Docs username yawik

## Expected Result

successfull login

## Actual Result

I can reset my password. But if I try to login, I receive:

Account Inactive
This account is inactive.

**Comment by davidfischer** [comment]
I can see that this account was marked as inactive although I don't see why. Normally when a user is explicitly banned (typically for spam) there is another setting so that doesn't appear to be the case. From what I can see, it looks like the account hasn't been used since 2014. Regardless, I have activated the account and you should be able to use it.

This account does not have access to any projects. The project you mentioned (also named yawik) is maintained by another user.

**Comment by davidfischer** [comment]
I'm going to close this issue for now as it is resolved.

If you need access to the [yawik project](https://readthedocs.org/projects/yawik/), please start by contacting the user "cross" if you know who that person is.
