### ISSUE TITLE
Guide users more on top level documentation page

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#5675]
We determined that the top level documentation page should probably be restructured and help guide users better. Looking at the types of users that we have viewing our documentation, and the context with which they arrive at the top level documentation page, there were a few changes that we discussed:

* The marketing material is important, but can be reduced. The top level documentation page isn't the best place to sell users -- the main product pages are a better place for this
* The toctree directive just plops all of our headings out in a list, we should instead curate them, group them, and make the flow of our documentation easier for users to digest

**Comment by humitos** [comment]
Kolibri project does this in an interesting way:

![Screenshot_2019-06-06_13-03-22](https://user-images.githubusercontent.com/244656/59028297-8964d900-885b-11e9-88ad-5d525ab3b535.png)

> https://kolibri.readthedocs.io/en/latest/

**Comment by davidfischer** [comment]
> The marketing material is important, but can be reduced. The top level documentation page isn't the best place to sell users -- the main product pages are a better place for this

I agree with this in theory but not strictly in practice. The big issue with docs.readthedocs.io is that it is the top level page. Clicking the logo or "home" goes to that page rather than to readthedocs.org. That is the reason why we need some marketing material ("what is RTD?" and "Why RTD") right at the top of that page.

Comparing our documentation with vaguely similar projects like [Travis CI](https://docs.travis-ci.com/), [Circle CI](https://circleci.com/docs/2.0/) both pages link back to the home page for those respective projects/companies and that's where the bulk of the marketing material lives. Until we do the same, I believe that we need a bit more marketing material.
