### ISSUE TITLE
Conda install needs up to 500MB RAM

### ISSUE THREAD

**Issue by epruesse** [rtfd/readthedocs.org#5693]
## Details

* Read the Docs project URL: https://ymp.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/ymp/builds/

## Expected Result

Conda environment install passing.

## Actual Result

Conda breaks.

Sometimes it's a timeout, sometimes it's an out-of-memory, sometimes it terminates with code 247 (which seems to indicate OOM as well).

## Fixes...

These are just things that are caveats of conda. It needs a ton of memory and it sometimes takes forever. I've got multiple issues open over there, but I doubt fixes will be possible soon.

Do you guys have the resources to increase available memory to 500MB for the `conda create` stage? I've tried many variations of the environment yaml, but nothing I do leads to significant improvements. It needs ~350MB if only using the Conda-Forge channel, ~420MB when also using Bioconda.

One alternate option I can picture is having it install package files. It's possible to get a list of urls via `conda list --explicit` and those urls / the files can be directly installed. That probably takes the least memory. Unfortunately, the files don't work with the normal `conda env create -n name --file env.yaml`.

**Comment by epruesse** [comment]
xref https://github.com/conda/conda/issues/8650

**Comment by humitos** [comment]
Hi @epruesse! This is a known problem, there are several issues on RTD about conda eating memory and also in their own repository.

Currently your build is using 1Gb of memory to build, so if it fails because of memory, it means that it's using more than that.

We have a small guide with some suggestions at https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html. One of this is use `pip` instead of `conda` if that is possible.

**Comment by stsewd** [comment]
If you are still not able to build your docs, let us know and we could increase the memory limits for your project

**Comment by epruesse** [comment]
@stsewd If you don't mind, it would be great to try that. My docs builds still fail occasionally (https://readthedocs.org/projects/ymp/builds/9063498/)

@mbargull - If you have time to work on `conda`, I suppose the memory requirements are really an issue. Since the solver's usage will be hard to trim down, perhaps making `conda env install` accept a solved env (i.e. the `@EXPLICIT` export of `conda list --explicit`) to sidestep the solver completely would be a KISS fix for situations like this one.

Another note: IIRC there were issues with `certifi` here too. In Bioconda, we  add `--single-version-externally-managed` to the `pip` line to avoid that error.

**Comment by stsewd** [comment]
Done, I've triggered a couple of builds of your project, and were successful.

**Comment by stsewd** [comment]
Let us know if you find any other problem

**Comment by epruesse** [comment]
Thanks! Sorry - should have closed this.

**Comment by mbargull** [comment]
> I suppose the memory requirements are really an issue.

Indeed, `conda` is quite memory hungry. IIRC, the bulk of it stems from just two things:
1. Holding the entirety of the channels' repository data in memory (as Python objects).
2. Holding the SAT clauses in memory as Python `tuple` of `int`s.

Where 1. always takes up a big, albeit (somewhat) fixed amount of memory whenever channels are queried and the impact of 2. can sometimes be negligible or (in the very worst cases) chew up some gigabytes.

> Since the solver's usage will be hard to trim down,

Not necessarily hard if you are "just" aiming for a constant factor of maybe 5+ or so. If the Python code that calls the SAT solver where to be turned into compiled code, the clauses could be stored into plain `int32` arrays. As a proxy, compare the following, which is very roughly comparable to the allocation happening on the Python side of `conda`'s SAT solves (for really bad cases):
```sh
> TIME=%M time python -c '
> arr = []
> for i in range(5_000_000):
>     arr.append((i, i+1, i+2))
> ' 2>&1 | numfmt --from-unit=1000 --to=iec-i --format=%fB
840MiB
```
```sh
> TIME=%M time python -c '
> from array import array
> arr = array("i")
> for i in range(5_000_000):
>     arr.extend((i, i+1, i+2, 0))
> ' 2>&1 | numfmt --from-unit=1000 --to=iec-i --format=%fB
83MiB
```
However, in your case here, the solver memory is most likely negligible, because
```sh
> TIME=%M time python -c '
> from json import load
> from urllib.request import urlopen
> channels = (
>     ["https://repo.anaconda.com/pkgs/{}".format(sub_channel) for sub_channel in ("main", "free", "r")]
>     +
>     ["https://conda.anaconda.org/{}".format(channel) for channel in ("conda-forge", "bioconda")]
> )
> repo_data_list = []
> for channel in channels:
>     for subdir in ("linux-64", "noarch"):
>         with urlopen("{}/{}/repodata.json".format(channel, subdir)) as repo_data_json:
>             repo_data_list.append(load(repo_data_json))
> ' 2>&1 | numfmt --from-unit=1000 --to=iec-i --format=%fB
315MiB
```
is a rough proxy for the base memory consumption which stems from holding all (involved) channels' data in memory. (Yes, that needs to be fixed and does not scale with (multiple) big channels, as is apparent.)

Now, the fun fact about using that `@EXPLICIT` list for `conda create --file` is that it sidesteps/ignores not only the dependency resolution/verification but also loading that repository data. Which is why the overall memory consumption is far lower in that case.

> perhaps making `conda env install` accept a solved env (i.e. the `@EXPLICIT` export of `conda list --explicit`) to sidestep the solver completely would be a KISS fix for situations like this one.

<details><summary>personal opinions w.r.t. `conda-env`</summary>

Honestly, for me personally, the KISS solution would be to not use `conda-env` but just let the user provide the files `condarc`, `conda-specs.txt` (or however named; i.e., the input for `conda create --file`), and `pip-requirements.txt`. What I like to do when creating a clean Conda environment is:
```sh
conda create --yes --name=env1
conda activate env1
conda config --env --append channels conda-forge --append channels bioconda --append channels defaults
conda install --yes ymp python=3.7
# If really need be, run `pip install` now.
# However, if another package manger, e.g., `pip`, modified the environment,
# consider it as "tainted" and, for subsequent commands,
# prefer `conda create --name=env2 && conda activate env2 && ...` over `conda install`.
```
I'm just no fan of `conda-env` since it's just a wrapper around `conda` (and `pip` :-/ ) but tends to lag behind and has its own issues. I *do* see the value in having a declarative way to describe a Conda environment's specifics and I know `conda-env` is used downstream in other workflows/tools. It just doesn't cut it for myself -- thus I really never use it.
</details>

I'll open an issue over at `conda`'s issue tracker for supporting `@EXPLICIT` lists in `conda-env`. I've been quite successful in avoiding to touch `conda-env`-related stuff and wouldn't mind keeping on with it ;) -- however, if you or @johanneskoester think that feature is useful in `ymp`/`snakemake`/something, I can take a look (if I'm honest, it shouldn't be much effort since `conda-env` is really mostly just a wrapper, so that its code is  quite "überschaubar").

**Comment by mbargull** [comment]
xref: https://github.com/conda/conda/issues/8852
