### ISSUE TITLE
Rename version with tag

### ISSUE THREAD

**Issue by Harmon758** [rtfd/readthedocs.org#5752]
## Details

According to https://docs.readthedocs.io/en/stable/faq.html#how-do-i-change-the-version-slug-of-my-project, you can rename a tag to change the corresponding version slug.
Upon renaming a tag from `3.7.0` to `v3.7.0` by creating the latter and deleting the former, the RTD version slug is still `3.7.0`. Attempting to delete the new `v3.7.0` tag and pushing `latest` in an attempt to trigger the changes in #4811 didn't seem to do anything, and the `3.7.0` version remained. Recreating the `v3.7.0` tag afterwards also had no effect.
Wiping the build environment for the version and manually triggering a build for it also had no effect.

* Read the Docs project URL: https://readthedocs.org/projects/tweepy/
* Build URL (if applicable): N/A
* Read the Docs username (if applicable): Harmon758

## Expected Result

Based on #4915, the version `3.7.0` should be deleted with the tag and a new version named `v3.7.0` should be created with the new tag.

## Actual Result

The `3.7.0` version remains unchanged, and there is no new `v3.7.0` version.

**Comment by stsewd** [comment]
Hi, I can see the new version under `Inactive versions` https://readthedocs.org/projects/tweepy/versions/

`3.7.0` isn't deleted because is active (under active versions). You should go to `Edit` and disable the `3.7.0` version and activate the `v3.7.0` version.

We don't remove versions marked as active, so users don't see a 404.
New versions are created but no activated by defaul, you can do this by going to `Edit` https://readthedocs.org/dashboard/tweepy/version/v3.7.0/

**Comment by Harmon758** [comment]
Ah, I see. My mistake. Thank you!
