### ISSUE TITLE
SVG support when generating PDF ?

### ISSUE THREAD

**Issue by PowerKiKi** [rtfd/readthedocs.org#905]
Generation of PDF is broken if the documentation include SVG images.

One workaround is to convert SVG into PDF before processing everything with sphinx, as [described there](https://sites.google.com/site/nickfolse/home/sphinx-latexpdf-output-with-svg-images). I successfully implemented that locally. But since readthedocs does not use Makefile, it "skips" the conversion step.

Would it be interesting to support SVG to PDF conversion out of the box for all projects ? That would add step in the build process of reathedocs build server.

Or would another way be preferable ? I suppose we could do something with Virtualenv and ``setup.py install``. But I am not very familiar with that, so I'd rather ask first ...

**Comment by stevepiercy** [comment]
Here's my lame workaround.
https://github.com/Pylons/pyramid/pull/1500

**Comment by andras-tim** [comment]
**+1**

Thx @stevepiercy for workaround!

**Comment by anarcat** [comment]
i found this answer for SVG + LaTeX: http://tex.stackexchange.com/questions/122871/include-svg-images-with-the-svg-package

**Comment by PowerKiKi** [comment]
Does it work on ReadTheDocs ?

**Comment by anarcat** [comment]
it doesn't, but it may be that i have another unrelated problem: https://readthedocs.org/builds/isuma-media-players/2875649/

**Comment by anarcat** [comment]
i get this:

```
LaTeX Warning: File `design3g.*' not found on input line 1996.
```

i think the workaround above implied there was a generated PNG version, which i don't have / want to bother with here...

**Comment by anarcat** [comment]
well, i ended up doing that: i can't make this work SVG in here, even without RFTD, it seems like like a sphinx bug as well - i'd be curious to see what's going on on that side.

because you can't just `\includegraphics{file.svg}` in LaTeX. It just doesn't support SVGs. And that's what Sphinx/RTD is doing... so you need a different directive there. this discussion has also good insight:

http://stackoverflow.com/questions/6473660/using-sphinx-docs-how-can-i-specify-png-image-formats-for-html-builds-and-pdf-im

i ended up using:

```
.. only:: latex

  .. image:: design3g.png

.. only:: html

  .. image:: design3g.svg
```

And in my makefile:

```
%.png: %.svg
	inkscape -z -D --file=$< --export-png=$@
```

When i change the SVG, i do `make file.png` by hand because i suspect RTD will not obey my makefile... as described in the summary above. anyways, inkscape is probably not installed...

**Comment by ericholscher** [comment]
Seems like this is a Sphinx issue, not a Read the Docs one. SVG support would be implemented there, not on our side. Their issue tracker is here: https://github.com/sphinx-doc/sphinx

**Comment by anarcat** [comment]
@ericholscher yet one of the things that was identified in this thread is how Sphinx-only builds would work because they would run the `Makefile` to generate the PNG/PDF files on the fly. RTD skips that, which makes it impossible to not pre-render the PNG files in the git repository, which makes unnecessary overhead.

It would be nice if RTD would at least provide a way to generate those files on the fly...

I opened an issue in Sphinx re. SVG support regardless.

**Comment by PowerKiKi** [comment]
For reference: https://github.com/sphinx-doc/sphinx/issues/1907

**Comment by ericholscher** [comment]
Thanks!
