### ISSUE TITLE
   Fail.  Check back in a bit!

### ISSUE THREAD

**Issue by DaveSenn** [rtfd/readthedocs.org#945]
Whenever I open my dashboard I get the following exception: 

          .
         ":"
       ___:____     |"\/"|
     ,'        `.    \  /
     |  O        \___/  |
   ~^~^~^~^~^~^~^~^~^~^~^~^~

   Fail.  Check back in a bit!

I use the following email address: dave dot jon dot senn at gmail dot com

**Comment by dstrohl** [comment]
I am getting the same error whenever I try to import a project from GitHub.  This is a new account and I have not been able to import anything yet.

I suspected the problem was a lack of requirements.txt file (or something like that) but when I created one it did not go away.  all of the suggestions I have found seem to be after the project is imported and you can look at the logs, but since I cant even get the project imported, I am not sure where (if anywhere) the logs could be found.
